-- Retention in the monolith model, and retention-aware regrain. While history is one coarse monolith
-- spanning the horizon, retain() cannot drop it (retention is suspended over coarse history). regrain() is
-- retention-aware: it copies only the within-horizon sub-ranges and SKIPS the ones entirely below the
-- horizon (it never copies them; their rows are discarded with the coarse source at the swap, never copied
-- and never deleted out of it), so no doomed partition is ever created and a later retain() has nothing to
-- do (issue #91).
--
-- The within-horizon rows are named, not counted (issue #1092). Every assertion here used to hold against a
-- regrain that lost all of [30000, 60000): the aged rows were gone, the copy count, the regrain_aged rows and
-- the fine children all as promised. Each row carries its own payload, and a snapshot taken before the
-- regrain is the authority for which rows must come through it, by (id, payload).
create extension if not exists pgtap;

select plan(8);

create table public.rt7 (id bigint generated by default as identity primary key, payload text);
insert into public.rt7 (payload) select 'p' || g from generate_series(1, 50000) g;   -- ids 1..50000, payload 'p<id>'
call pgpm.transmute('public.rt7', 'id', 10000, p_retain => 30000);   -- monolith [0, 60000); retain 30000 ids
select pgpm.obtain('public.rt7');
insert into public.rt7 (id, payload) values (65000, 'frontier');   -- frontier=65000 -> monolith frozen; horizon boundary = 30000
create temporary table rt7_before as select id, payload from public.rt7;

select is(
  (select count(*) filter (where id < 30000) || ' aged / ' || count(*) filter (where id >= 30000) || ' within: '
          || min(id) filter (where id >= 30000) || '..' || max(id) filter (where id < 60000) || ' and '
          || max(id) || ' / own payloads ' || bool_and(payload = 'p' || id or id = 65000)
     from rt7_before),
  '29999 aged / 20002 within: 30000..50000 and 65000 / own payloads true',
  'LIVENESS: the snapshot holds 29999 aged rows and the 20002 within the horizon, 30000 through 50000 and the frontier, each with its own payload');

select is(
  pgpm.retain('public.rt7'),
  0, 'retention is suspended over the coarse monolith (a partition spanning the horizon cannot be dropped)');

select is(
  (select pgpm.regrain_history('public.rt7'))::int,
  3, 'retention-aware regrain copies only the 3 within-horizon sub-ranges [30000, 60000)');

select is(
  (select count(distinct lo)::int from pgpm.log where parent_table = 'public.rt7'::regclass and action = 'regrain_aged'),
  3, 'the 3 below-horizon sub-ranges are skipped (logged regrain_aged), never copied or materialized');

select is(
  (select count(*)::int from public.rt7 where id < 30000),
  0, 'the aged rows below the horizon are discarded with the coarse source at the swap, never copied');

select bag_eq(
  'select id, payload from public.rt7 where id >= 30000',
  'select id, payload from rt7_before where id >= 30000',
  'every within-horizon row survives the regrain by identity: 30000 through 50000 and the frontier, none lost, none added, none altered');

select is(
  pgpm.retain('public.rt7'),
  0, 'a later retain() is a no-op: regrain already reclaimed the aged ranges (no materialize-then-drop churn)');

select ok(
  to_regclass('public.rt7_p' || lpad('0', 19, '0')) is null
    and to_regclass('public.rt7_p' || lpad('30000', 19, '0')) is not null,
  'no doomed aged fine child was materialized; the within-horizon children exist');

select * from finish();
