-- The archive path carries a partition's identity as a NAME, and nothing anchored it (issue #421).
--
-- pgpm._archive_step selects `child_name` out of pgpm.part and every step after it re-resolves that
-- string independently: _is_write_blocked matches it against pg_class, _next_archive_chunk reads
-- %I.%I to pick the chunk, and the archive_fn is handed the bare name. None of them asserted that
-- the relation answering to it is the partition pgpm.part was recorded for.
--
-- This needs no race. If the name stops meaning what it meant -- an operator renames a partition
-- aside, something else takes the name (pgpm.forget_missing exists precisely because pgpm already
-- knows this state is reachable) -- then the chunk is picked from the substitute's rows and a
-- pgpm.archive_ledger row records a coverage claim for a range those rows never came from. That
-- ledger is what pgpm._archive_fully_covered consults as retire()'s drop precondition, so a bad
-- export does not merely put a wrong object in the bucket: it satisfies the gate that authorises a
-- DROP. Pre-fix, the run below ended with the substitute destroyed and the pgpm.part row deleted.
--
-- The fix anchors the partition's identity in pgpm.part.child_oid, recorded where a partition ENTERS
-- the catalog (not at retirement, the way #407's retiring_oid is -- that is null for every partition
-- the archive step ever touches), and checks it once per candidate at the top of _archive_step,
-- before any read of the child.
create extension if not exists pgtap;

select plan(25);

-- Monolith [0, 1000) with 7 rows, sibling [1000, 2000) with 3, retention leaving exactly those two
-- eligible (frontier 20000 - retain 18000 = boundary 2000). Three distinct row counts across the
-- three relations involved -- 7 real, 3 sibling, 2 substitute -- so no claim any of them makes can
-- be mistaken for another's, and no pair of compensating errors can cancel into a passing count.
create table public.ai102 (id bigint generated by default as identity primary key, payload text);
insert into public.ai102 (payload) select 'x' from generate_series(1, 7);              -- ids 1..7
call pgpm.transmute('public.ai102', 'id', 1000, p_retain => 18000, p_paused => false); -- monolith [0,1000)
insert into public.ai102 (id, payload) select g, 'y' from generate_series(1001, 1003) g;  -- [1000,2000)
insert into public.ai102 (id, payload) values (20000, 'frontier');                     -- boundary 2000

-- _archive_noop is a real archive_fn (a genuine regprocedure dispatch through
-- _run_archive_strategy, not a null-strategy special case) that reads the child BY NAME, which is
-- exactly the contract surface this test is about. archive_batch null so one _archive_step call
-- attempts every candidate: the sibling's archiving in the same call is the liveness witness that
-- the step ran at all, and a batch of 1 would take the refused monolith's slot and prove nothing.
update pgpm.config
   set archive_fn = 'pgpm._archive_noop(regclass,name,text,text)'::regprocedure,
       archive_batch = null
 where parent_table = 'public.ai102'::regclass;

select child_name as ai_doomed from pgpm.part
  where parent_table = 'public.ai102'::regclass and lo = '0' \gset
select child_name as ai_sib from pgpm.part
  where parent_table = 'public.ai102'::regclass and lo = '1000' \gset
select format('public.%I', :'ai_doomed')::regclass::oid as ai_real \gset

select is((select count(*)::int from public.ai102 where id < 1000), 7,
  'fixture: the monolith holds 7 rows');
select is((select count(*)::int from public.ai102 where id >= 1000 and id < 2000), 3,
  'fixture: the sibling holds 3 -- a different count, so neither can stand in for the other');
select is(
  (select count(*)::int from pgpm.part
    where parent_table = 'public.ai102'::regclass and attached and hi::numeric <= 2000),
  2, 'fixture: exactly two partitions are past the retention horizon');

-- the write blocks a maintain() tick installs, before anything is disturbed
select pgpm._enforce_write_blocks('public.ai102');

-- LIVENESS. Every assertion after the substitution is a negative -- the substitute was not archived,
-- not covered, not dropped -- and a run that never recorded an identity, or never set one up,
-- satisfies all of them just as well. Pin the anchor before disturbing it.
select is(
  (select child_oid from pgpm.part
    where parent_table = 'public.ai102'::regclass and child_name = :'ai_doomed'),
  :'ai_real'::oid,
  'LIVENESS: pgpm.part records WHICH relation this partition is, by oid, from the moment it was created');

-- THE SUBSTITUTION. No race and no detach: the partition pgpm meant is renamed aside (still attached,
-- still holding its rows, so a wrong drop is visible) and an unrelated relation takes the name it
-- vacated, holding rows inside the partition's own range so the substitute's claim looks plausible.
select format('alter table public.%I rename to ai102_kept', :'ai_doomed') \gexec
select format('create table public.%I (like public.ai102)', :'ai_doomed') \gexec
select format('insert into public.%I (id, payload) values (501, ''impostor''), (502, ''impostor'')',
              :'ai_doomed') \gexec
select format('public.%I', :'ai_doomed')::regclass::oid as ai_impostor \gset

select isnt(:'ai_impostor'::oid, :'ai_real'::oid,
  'LIVENESS: the name now answers to a DIFFERENT relation than pgpm recorded');
select is((select to_regclass('public.ai102_kept')::oid), :'ai_real'::oid,
  'LIVENESS: and the one it did mean is still here, moved aside, so a wrong drop would be visible');
select is((select count(*)::int from public.ai102_kept), 7,
  'LIVENESS: still holding all 7 of its rows, still attached to the parent');
select is((select count(*)::int from pg_inherits i
            where i.inhparent = 'public.ai102'::regclass and i.inhrelid = :'ai_real'::oid),
  1, 'LIVENESS: the rename did not detach it -- the parent still routes reads to it');

-- The substitute has to be WRITE-BLOCKED to be an archive candidate at all: _archive_step's query
-- gates on _is_write_blocked, so without a trigger here the step never reaches it and every refusal
-- below would pass against a step that did nothing.
--
-- Installed by hand, and the reason matters (#429). Until #429 this state arrived on its own: the
-- per-tick write-block pass resolved child_name and put the trigger on whatever held it, which is
-- exactly how maintenance manufactured its own bad candidate. pgpm now refuses to do that, so the
-- only remaining way in is the one modelled here -- an install that ran a PRE-#429 pgpm, which left
-- the trigger behind before upgrading. That is precisely why the check below is still worth having
-- and is not made redundant by #429: _is_write_blocked stays name-based on purpose, so a trigger
-- from any source still makes a substituted name eligible, and this is the backstop for it.
-- ENABLE ALWAYS as well (#651): _is_write_blocked counts only a block in force, so an origin-only
-- trigger, as that pre-#429 pgpm left it, would not make the name a candidate at all. A block in force
-- on the substitute (an operator enabling it ALWAYS, say) is the state the backstop still has to catch.
select format($$ create trigger pgpm_write_block before insert or update or delete
                   on public.%I for each row execute function pgpm._write_block_raise() $$,
              :'ai_doomed') \gexec
select format('alter table public.%I enable always trigger pgpm_write_block', :'ai_doomed') \gexec

select ok(pgpm._is_write_blocked('public.ai102', :'ai_doomed'),
  'LIVENESS: the substitute is write-blocked, so it satisfies _archive_step''s eligibility test');
select ok(not pgpm._archive_fully_covered('public.ai102', :'ai_doomed'),
  'LIVENESS: and it is not yet covered -- absent the anchor, the step would archive it');

-- THE REFUSAL. One call, two candidates: the substituted name is refused, the sibling is archived.
select is(pgpm._archive_step('public.ai102'), 1,
  'the step records exactly one chunk: it refused the substituted name and carried on to the sibling');

select is(
  (select count(*)::int from pgpm.archive_ledger
    where parent_table = 'public.ai102'::regclass and child_name = :'ai_doomed'),
  0, 'no ledger row claims coverage for the substituted partition');
select is(
  (select rows_archived from pgpm.archive_ledger
    where parent_table = 'public.ai102'::regclass and child_name = :'ai_sib'),
  3::bigint,
  'and the one row it did write is the SIBLING''s, carrying the sibling''s own 3 rows');

select results_eq(
  $$ select action, lo, hi from pgpm.log
      where parent_table = 'public.ai102'::regclass and action = 'fail_archive_identity' $$,
  $$ values ('fail_archive_identity'::text, '0'::text, '1000'::text) $$,
  'refused as exactly fail_archive_identity, naming the partition''s own range');

-- THE CONSEQUENCE. The refusal is only worth anything if it keeps the drop gate shut. The previous
-- assertion is the coverage-specific claim; this one is only that the DROP does not happen. Since
-- #428 there are two independent reasons it does not -- coverage never completed, AND retire()'s own
-- identity check now consults child_oid on the one-step path too -- so this no longer isolates the
-- archive gate by itself, and it logs a fail_retain_identity alongside the archive refusals (counted
-- at the end of this file).
select ok(not pgpm._archive_fully_covered('public.ai102', :'ai_doomed'),
  'the coverage gate stays shut: nothing was archived, so nothing claims it was');
select ok(not pgpm.retire('public.ai102', :'ai_doomed'),
  'so retire() refuses the drop -- pre-fix this returned true and destroyed the substitute');

-- to_regclass, not a ::regclass cast: a run in which the substitute WAS dropped must report a failed
-- assertion naming what happened, not die on an unresolvable name and take the rest of the file with it.
select is((select to_regclass(format('public.%I', :'ai_doomed'))::oid), :'ai_impostor'::oid,
  'the substitute is untouched -- the same relation, not merely a relation of that name');
select is((select count(*)::int from public.ai102 where id in (501, 502)), 0,
  'and its rows are foreign to the managed table -- a coverage claim built from them would have been a claim about data the partition never held');
select is((select to_regclass('public.ai102_kept')::oid), :'ai_real'::oid,
  'the partition pgpm did mean is untouched too: refusing is not re-guessing');
select is((select count(*)::int from public.ai102_kept), 7,
  'with all 7 rows still in it');
select is(
  (select count(*)::int from pgpm.part
    where parent_table = 'public.ai102'::regclass and child_name = :'ai_doomed'),
  1, 'the pgpm.part row stays, so the partition is visibly wedged rather than quietly finished');

-- A STANDING WEDGE, not a deferral. There is no later tick on which the name goes back to meaning
-- the right relation, so this must keep refusing and keep saying so.
select is(pgpm._archive_step('public.ai102'), 0,
  'a second call archives nothing at all: the sibling is covered and the substitute is still refused');
select is(
  (select count(*)::int from pgpm.archive_ledger where parent_table = 'public.ai102'::regclass),
  1, 'and writes no further ledger row -- the sibling''s is still the only one');
select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.ai102'::regclass and action = 'fail_archive_identity'),
  2, 'both refusals are logged: this never clears itself');
-- 3, not 2: the two fail_archive_identity above plus the one fail_retain_identity the retire() call
-- logged, which since #428 refuses the same substituted name on its own anchor. Spelled out rather
-- than left as a bare number, because a count that silently absorbs a new action value is exactly
-- how a since-last-progress counter stops meaning anything.
select is(
  (select retain_drop_failures from pgpm.status() where parent = 'public.ai102'::regclass),
  3::bigint,
  'status() counts all three alongside the other things that stall retention, so an operator sees the wedge');

select * from finish();
