-- retire()'s ordinary one-step DROP was unanchored (issue #428).
--
-- #407 gave retire() an identity check, but scoped it to the defect #407 was about: the dispatch
-- gap. Its anchor, pgpm.part.retiring_oid, is set only inside the `if v_referenced` branch, as
-- retire() dispatches a concurrent detach. For a partition nothing points a foreign key at -- the
-- overwhelmingly common case, and the one retire()'s own comment calls "the overwhelmingly common
-- path stays byte-identical" -- it is null on every call, the check is skipped whole, and the
-- `drop table %I.%I` at the end destroys whatever answers to the name.
--
-- pgpm.part.child_oid (#421) is the anchor that path was missing: recorded where the partition
-- ENTERS the catalog, so it is populated for every partition, referenced or not. This file covers
-- the two things widening the check to consult it has to get right.
--
-- PART A is #428 proper: an unreferenced partition on an archive_fn-null table, which is the state
-- in which nothing else stands between the write block and the DROP.
--
-- PART B is why the two anchors are checked INDEPENDENTLY rather than one falling back to the other.
-- retiring_oid is itself resolved by NAME, out of pg_inherits, at dispatch time -- so a substitution
-- that landed before the dispatch is adopted BY the anchor, and comparing the name against it passes
-- forever. Only child_oid still remembers the original. `coalesce(retiring_oid, child_oid)` would
-- pick the adopted one and never fire; checking both fires.
create extension if not exists pgtap;

select plan(33);

-- The substitute's name is generated, so it cannot be written into a query literally. Count its rows
-- through its oid instead, which is also the stronger claim: it says THAT relation still has them,
-- not that something of that name does.
--
-- Takes an oid and re-derives the name, rather than taking a regclass: on a run where the defect IS
-- present the relation has been dropped, and a dangling regclass renders as the bare oid number, so
-- `count(*) from %s` raises a syntax error and takes the rest of the file with it. Returning null
-- makes that case a clean failed assertion instead -- which matters because the discriminate harness
-- reads "how many assertions ran" as its own liveness check.
create schema pgpm_test103;
create function pgpm_test103.rowcount(p_oid oid) returns int language plpgsql as $$
declare v_n int; v_rel text;
begin
  select format('%I.%I', n.nspname, c.relname) into v_rel
    from pg_class c join pg_namespace n on n.oid = c.relnamespace where c.oid = p_oid;
  if v_rel is null then return null; end if;
  execute format('select count(*) from %s', v_rel) into v_n;
  return v_n;
end;
$$;

-- ============================ PART A: the unreferenced one-step DROP ============================

-- Monolith [0, 1000) with 7 rows, sibling [1000, 2000) with 3, retention leaving exactly those two
-- eligible (frontier 20000 - retain 18000 = boundary 2000). Three distinct row counts across the
-- three relations involved -- 7 real, 3 sibling, 2 substitute -- so no claim any of them makes can
-- be mistaken for another's.
create table public.ri103 (id bigint generated by default as identity primary key, payload text);
insert into public.ri103 (payload) select 'x' from generate_series(1, 7);              -- ids 1..7
call pgpm.transmute('public.ri103', 'id', 1000, p_retain => 18000, p_paused => false); -- monolith [0,1000)
insert into public.ri103 (id, payload) select g, 'y' from generate_series(1001, 1003) g;  -- [1000,2000)
insert into public.ri103 (id, payload) values (20000, 'frontier');                     -- boundary 2000

select child_name as ri_doomed from pgpm.part
  where parent_table = 'public.ri103'::regclass and lo = '0' \gset
select child_name as ri_sib from pgpm.part
  where parent_table = 'public.ri103'::regclass and lo = '1000' \gset
select format('public.%I', :'ri_doomed')::regclass::oid as ri_real \gset

-- SETUP WITNESSES. retire() has three ways to return false before it ever reaches the DROP -- the
-- archive-coverage gate, the referenced-partition branch, and the identity check. Pin the first two
-- open, or "it returned false" below proves nothing about the third.
select is((select archive_fn from pgpm.config where parent_table = 'public.ri103'::regclass),
  null::regprocedure,
  'fixture: no archive strategy, so the coverage gate is wide open and cannot be what refuses');
select is(
  (select count(*)::int from pg_constraint
    where confrelid = 'public.ri103'::regclass and contype = 'f' and conparentid = 0),
  0, 'fixture: nothing references this parent, so retirement takes the one-step bare-DROP path');
select is((select count(*)::int from public.ri103 where id < 1000), 7,
  'fixture: the monolith holds 7 rows');
select is((select count(*)::int from public.ri103 where id >= 1000 and id < 2000), 3,
  'fixture: the sibling holds 3 -- a different count, so neither can stand in for the other');

-- LIVENESS, and the one that says this file is not a duplicate of tests/77: the anchor #407 added is
-- absent here, which is exactly the gap. A run in which retiring_oid happened to be set would be
-- exercising #407's check, not #428's.
select is(
  (select retiring_oid from pgpm.part
    where parent_table = 'public.ri103'::regclass and child_name = :'ri_doomed'),
  null::oid,
  'LIVENESS: retiring_oid is null -- this is precisely the path #407''s anchor does not cover');
select is(
  (select child_oid from pgpm.part
    where parent_table = 'public.ri103'::regclass and child_name = :'ri_doomed'),
  :'ri_real'::oid,
  'LIVENESS: but child_oid records WHICH relation this partition is, by oid');

-- THE SUBSTITUTION. No race and no detach: the partition pgpm meant is renamed aside (still attached,
-- still holding its rows, so a wrong drop is visible) and an unrelated relation takes the name.
select format('alter table public.%I rename to ri103_kept', :'ri_doomed') \gexec
select format('create table public.%I (like public.ri103)', :'ri_doomed') \gexec
select format('insert into public.%I (id, payload) values (501, ''impostor''), (502, ''impostor'')',
              :'ri_doomed') \gexec
select format('public.%I', :'ri_doomed')::regclass::oid as ri_impostor \gset

select isnt(:'ri_impostor'::oid, :'ri_real'::oid,
  'LIVENESS: the name now answers to a DIFFERENT relation than pgpm recorded');
select is((select to_regclass('public.ri103_kept')::oid), :'ri_real'::oid,
  'LIVENESS: and the one it did mean is still here, moved aside, so a wrong drop would be visible');
select is((select count(*)::int from pg_inherits i
            where i.inhparent = 'public.ri103'::regclass and i.inhrelid = :'ri_real'::oid),
  1, 'LIVENESS: the rename did not detach it -- it is still a live partition of the parent');
select is((select count(*)::int from public.ri103_kept), 7,
  'LIVENESS: still holding all 7 of its rows');
select is((select count(*)::int from public.ri103 where id in (501, 502)), 0,
  'LIVENESS: and the substitute''s 2 rows are foreign to the managed table entirely');

-- LIVENESS, the load-bearing one. Every assertion after this is "retire() did NOT drop the
-- substitute", which is equally satisfied by a table on which retire() cannot drop anything at all.
-- The sibling is in the identical state minus the substitution, so its drop proves the fixture
-- really is drop-ready and isolates the refusal to the one thing that differs.
select ok(pgpm.retire('public.ri103', :'ri_sib'),
  'LIVENESS: the untouched sibling retires normally, so this table IS in a drop-ready state');
select is(
  (select count(*)::int from pgpm.part
    where parent_table = 'public.ri103'::regclass and child_name = :'ri_sib'),
  0, 'LIVENESS: and it is really gone -- a true return, not a claim');

-- THE REFUSAL.
select ok(not pgpm.retire('public.ri103', :'ri_doomed'),
  'retire() refuses the substituted name -- pre-fix this returned true and dropped it');

select results_eq(
  $$ select action, lo, hi from pgpm.log
      where parent_table = 'public.ri103'::regclass and action = 'fail_retain_identity' $$,
  $$ values ('fail_retain_identity'::text, '0'::text, '1000'::text) $$,
  'refused as exactly fail_retain_identity, naming the partition''s own range');
select ok(
  (select method like '%recorded for this partition when it was created%' from pgpm.log
    where parent_table = 'public.ri103'::regclass and action = 'fail_retain_identity'),
  'and the reason names child_oid as the anchor that disagreed, not retiring_oid');

-- to_regclass, not a ::regclass cast: a run in which the substitute WAS dropped must report a failed
-- assertion naming what happened, not die on an unresolvable name and take the rest of the file with it.
select is((select to_regclass(format('public.%I', :'ri_doomed'))::oid), :'ri_impostor'::oid,
  'the substitute is untouched -- the same relation, not merely a relation of that name');
select is(pgpm_test103.rowcount(:'ri_impostor'::oid), 2,
  'and it still holds both its rows');
select is((select to_regclass('public.ri103_kept')::oid), :'ri_real'::oid,
  'the partition pgpm did mean is untouched too: refusing is not re-guessing');
select is((select count(*)::int from public.ri103_kept), 7,
  'with all 7 rows still in it');
select is(
  (select count(*)::int from pgpm.part
    where parent_table = 'public.ri103'::regclass and child_name = :'ri_doomed'),
  1, 'the pgpm.part row stays, so the partition is visibly wedged rather than quietly finished');

-- A STANDING WEDGE, not a deferral.
select ok(not pgpm.retire('public.ri103', :'ri_doomed'),
  'a second call refuses again: no later tick makes the name mean the right relation');
select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.ri103'::regclass and action = 'fail_retain_identity'),
  2, 'both refusals are logged: this never clears itself');
select is(
  (select retain_drop_failures from pgpm.status() where parent = 'public.ri103'::regclass),
  2::bigint,
  'status() counts them, and counts them SINCE the sibling''s successful drop -- a wedge behind real progress');

-- ================== PART B: both anchors set, and only child_oid disagrees ==================
--
-- retiring_oid is read out of pg_inherits BY NAME at dispatch time, so a substitution that landed
-- before the dispatch is what the anchor records. Comparing the name against it then passes forever.
-- Going forward the widened check refuses before any dispatch, so retire() can no longer PRODUCE
-- this divergence -- which is why the state is built here by hand. It is what a pre-#428 pgpm left
-- behind, and an upgrade inherits it.
create table public.rb103 (id bigint generated by default as identity primary key, payload text);
insert into public.rb103 (payload) select 'x' from generate_series(1, 5);
call pgpm.transmute('public.rb103', 'id', 1000, p_retain => 18000, p_paused => false);
insert into public.rb103 (id, payload) values (20000, 'frontier');

select child_name as rb_doomed from pgpm.part
  where parent_table = 'public.rb103'::regclass and lo = '0' \gset
select format('public.%I', :'rb_doomed')::regclass::oid as rb_real \gset

-- The substitution in the only shape that matters for a DROP: the impostor is a genuine partition of
-- the same parent under the same name, so nothing downstream would fail loudly on it.
select format('alter table public.rb103 detach partition public.%I', :'rb_doomed') \gexec
select format('alter table public.%I rename to rb103_kept', :'rb_doomed') \gexec
select format('create table public.%I (like public.rb103)', :'rb_doomed') \gexec
select format('alter table public.rb103 attach partition public.%I for values from (0) to (1000)',
              :'rb_doomed') \gexec
select format('public.%I', :'rb_doomed')::regclass::oid as rb_impostor \gset

-- what a pre-#428 dispatch recorded: the oid the NAME resolved to at that moment, which is the impostor
update pgpm.part set retiring_at = now(), retiring_oid = :'rb_impostor'::oid
 where parent_table = 'public.rb103'::regclass and child_name = :'rb_doomed';

select is(
  (select child_oid from pgpm.part
    where parent_table = 'public.rb103'::regclass and child_name = :'rb_doomed'),
  :'rb_real'::oid,
  'LIVENESS: child_oid still records the relation the partition was created as');
select is(
  (select count(*)::int from pg_inherits i join pg_class c on c.oid = i.inhrelid
    where i.inhparent = 'public.rb103'::regclass and c.oid = :'rb_impostor'::oid),
  1, 'LIVENESS: the impostor really is attached to the same parent -- a DROP would land on it cleanly');

-- THE WITNESS THIS PART EXISTS FOR. #407's anchor agrees with the name, so #407's check alone passes
-- here, and so would any implementation that merely falls back from retiring_oid to child_oid.
select is(
  (select retiring_oid from pgpm.part
    where parent_table = 'public.rb103'::regclass and child_name = :'rb_doomed'),
  (select to_regclass(format('public.%I', :'rb_doomed'))::oid),
  'LIVENESS: retiring_oid AGREES with what the name resolves to -- #407''s check alone is satisfied');
select isnt(
  (select retiring_oid from pgpm.part
    where parent_table = 'public.rb103'::regclass and child_name = :'rb_doomed'),
  (select child_oid from pgpm.part
    where parent_table = 'public.rb103'::regclass and child_name = :'rb_doomed'),
  'LIVENESS: and the two anchors disagree with each other, which is the whole case');

select ok(not pgpm.retire('public.rb103', :'rb_doomed'),
  'retire() refuses anyway: the anchors are checked independently, not coalesced');
select ok(
  (select method like '%recorded for this partition when it was created%' from pgpm.log
    where parent_table = 'public.rb103'::regclass and action = 'fail_retain_identity'),
  'and says so: child_oid is the anchor that disagreed');
select ok(
  (select method not like '%dispatched a detach for%' from pgpm.log
    where parent_table = 'public.rb103'::regclass and action = 'fail_retain_identity'),
  'and does NOT blame retiring_oid, which matched -- the message distinguishes them');

select is((select to_regclass(format('public.%I', :'rb_doomed'))::oid), :'rb_impostor'::oid,
  'the impostor is untouched');
select is((select to_regclass('public.rb103_kept')::oid), :'rb_real'::oid,
  'and so is the relation the partition actually was');

select * from finish();
