-- _install_write_block created its trigger on whatever answered to the name (issue #429).
--
-- pgpm._install_write_block resolves `%I.%I` from the parent's namespace and p_child and issues
-- CREATE TRIGGER against the result, with no assertion that the relation is the partition
-- pgpm.part recorded -- or a partition of this parent at all. _enforce_write_blocks calls it for
-- every attached child on every maintain() tick, so a relation that has taken a partition's name
-- gets a pgpm trigger that rejects all of its INSERTs, UPDATEs and DELETEs, and nothing in pgpm's
-- own catalog records that it did this.
--
-- The second consequence is what made #421 reproducible rather than theoretical: _archive_step's
-- candidate query gates on _is_write_blocked, so a substituted name is only ever ELIGIBLE for
-- archiving because this step made it so. Maintenance manufactured its own candidate.
--
-- PART A is the refusal, and it is asserted through the per-tick path (_enforce_write_blocks) AND
-- through a direct call, because the check lives in _install_write_block itself rather than in the
-- loop -- so that a future caller cannot reintroduce the defect by not knowing about it.
--
-- PART B is the deliberate asymmetry: _remove_write_block is NOT anchored. Refusing to install is
-- protective; refusing to REMOVE would strand a trigger a pre-#429 pgpm already put on a substituted
-- relation, leaving that relation rejecting every write forever with no way for pgpm to lift it.
-- Cleanup stays name-based on purpose, and this proves it still works.
create extension if not exists pgtap;

select plan(26);

-- ======================= PART A: the install refuses a substituted name =======================

-- Monolith [0, 1000) with 7 rows, sibling [1000, 2000) with 3, retention leaving exactly those two
-- eligible (frontier 20000 - retain 18000 = boundary 2000).
create table public.wb104 (id bigint generated by default as identity primary key, payload text);
insert into public.wb104 (payload) select 'x' from generate_series(1, 7);
call pgpm.transmute('public.wb104', 'id', 1000, p_retain => 18000, p_paused => false);
insert into public.wb104 (id, payload) select g, 'y' from generate_series(1001, 1003) g;
insert into public.wb104 (id, payload) values (20000, 'frontier');

select child_name as wb_doomed from pgpm.part
  where parent_table = 'public.wb104'::regclass and lo = '0' \gset
select child_name as wb_sib from pgpm.part
  where parent_table = 'public.wb104'::regclass and lo = '1000' \gset
select format('public.%I', :'wb_doomed')::regclass::oid as wb_real \gset

select is(
  (select count(*)::int from pgpm.part
    where parent_table = 'public.wb104'::regclass and attached and hi::numeric <= 2000),
  2, 'setup: exactly two partitions are past the retention horizon, so both are due a write block');
select is(
  (select child_oid from pgpm.part
    where parent_table = 'public.wb104'::regclass and child_name = :'wb_doomed'),
  :'wb_real'::oid,
  'LIVENESS: pgpm.part records WHICH relation this partition is, by oid');

-- THE SUBSTITUTION, before any write-block pass has run: the partition is renamed aside and an
-- unrelated relation takes the name it vacated.
select format('alter table public.%I rename to wb104_kept', :'wb_doomed') \gexec
select format('create table public.%I (like public.wb104)', :'wb_doomed') \gexec
select format('public.%I', :'wb_doomed')::regclass::oid as wb_impostor \gset

select isnt(:'wb_impostor'::oid, :'wb_real'::oid,
  'LIVENESS: the name now answers to a DIFFERENT relation than pgpm recorded');
select is((select count(*)::int from pg_inherits i
            where i.inhparent = 'public.wb104'::regclass and i.inhrelid = :'wb_real'::oid),
  1, 'LIVENESS: the relation pgpm meant is still a live partition of the parent, merely renamed');
select is(
  (select count(*)::int from pg_trigger where tgrelid = :'wb_impostor'::oid and not tgisinternal),
  0, 'LIVENESS: the substitute carries no triggers at all going in');

-- ONE ORDINARY TICK'S WORTH of write-block reconciliation.
select pgpm._enforce_write_blocks('public.wb104');

-- LIVENESS, the load-bearing one. "The substitute did not get a trigger" is equally satisfied by a
-- pass that installed nothing anywhere. The sibling is eligible and unsubstituted, so its trigger
-- proves the pass ran and still does its job.
select ok(pgpm._is_write_blocked('public.wb104', :'wb_sib'),
  'LIVENESS: the untouched sibling IS write-blocked, so the pass ran and still installs');

select ok(not pgpm._is_write_blocked('public.wb104', :'wb_doomed'),
  'the substitute did NOT get pgpm''s write-block trigger');
select is(
  (select count(*)::int from pg_trigger where tgrelid = :'wb_impostor'::oid and not tgisinternal),
  0, 'and got no trigger of any kind: pgpm issued no DDL at all against a relation it had not identified');

select results_eq(
  $$ select action, lo, hi from pgpm.log
      where parent_table = 'public.wb104'::regclass and action = 'fail_write_block_identity' $$,
  $$ values ('fail_write_block_identity'::text, '0'::text, '1000'::text) $$,
  'refused as exactly fail_write_block_identity, naming the partition''s own range');
select ok(
  (select method like '%recorded for this partition%' from pgpm.log
    where parent_table = 'public.wb104'::regclass and action = 'fail_write_block_identity'),
  'and the reason carries the oids, so an operator can see what took the name');
select is(
  (select retain_drop_failures from pgpm.status() where parent = 'public.wb104'::regclass),
  1::bigint,
  'status() counts it: no write block means no archiving and no drop, so retention is stalled');

-- THE CHECK IS IN THE FUNCTION, NOT THE LOOP. A direct call has to refuse too, or a caller that is
-- not _enforce_write_blocks reintroduces the whole defect.
select lives_ok(
  format($$ select pgpm._install_write_block('public.wb104', %L) $$, :'wb_doomed'),
  'a direct _install_write_block call on the substituted name is refused, not raised');
select is(
  (select count(*)::int from pg_trigger where tgrelid = :'wb_impostor'::oid and not tgisinternal),
  0, 'and it too created nothing');
select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.wb104'::regclass and action = 'fail_write_block_identity'),
  2, 'and logged its own refusal: the check travels with the function');

select is((select to_regclass('public.wb104_kept')::oid), :'wb_real'::oid,
  'the partition pgpm did mean is untouched');
select is((select count(*)::int from public.wb104_kept), 7,
  'with all 7 rows still in it');

-- ============= PART B: removal stays name-based, so a stranded trigger can be lifted =============
--
-- A pre-#429 pgpm installed its write block on whatever held the name, so an install upgrading into
-- this fix can already have one sitting on a relation it never managed -- rejecting every write to
-- it. Anchoring _remove_write_block too would be symmetrical and would leave that relation read-only
-- permanently, because pgpm would then refuse to touch the very trigger it wrongly created. Removal
-- is therefore deliberately left resolving by name.
create table public.wb104b (id bigint generated by default as identity primary key, payload text);
insert into public.wb104b (payload) select 'x' from generate_series(1, 5);
call pgpm.transmute('public.wb104b', 'id', 1000, p_retain => 18000, p_paused => false);
insert into public.wb104b (id, payload) select g, 'y' from generate_series(1001, 1002) g;
insert into public.wb104b (id, payload) values (20000, 'frontier');

select child_name as wc_doomed from pgpm.part
  where parent_table = 'public.wb104b'::regclass and lo = '0' \gset
select child_name as wc_sib from pgpm.part
  where parent_table = 'public.wb104b'::regclass and lo = '1000' \gset

-- block the legitimate children first, exactly as a tick would
select pgpm._enforce_write_blocks('public.wb104b');

-- ...then substitute, and put the trigger on the substitute BY HAND: this is what a pre-#429 pgpm
-- left behind, and the state an upgrade inherits. It cannot be produced through pgpm any more,
-- which is the whole point of part A.
select format('alter table public.%I rename to wb104b_kept', :'wc_doomed') \gexec
select format('create table public.%I (like public.wb104b)', :'wc_doomed') \gexec
select format($$ create trigger pgpm_write_block before insert or update or delete
                   on public.%I for each row execute function pgpm._write_block_raise() $$,
              :'wc_doomed') \gexec

-- Presence, read from pg_trigger rather than _is_write_blocked: that counts only a block enabled ALWAYS
-- (#651), and the trigger a pre-#429 pgpm left is origin-only, so it would read false here and, below,
-- read "lifted" whether or not the removal arm touched it.
select ok(exists (select 1 from pg_trigger where tgname = 'pgpm_write_block'
                     and tgrelid = format('public.%I', :'wc_doomed')::regclass),
  'LIVENESS: the substitute carries a stranded write-block trigger, as a pre-#429 install would have left it');
select throws_like(
  format($$ insert into public.%I (id, payload) values (9001, 'z') $$, :'wc_doomed'),
  '%past its retention boundary%',
  'LIVENESS: and it really is read-only because of it -- the harm being cleaned up is real');
select ok(pgpm._is_write_blocked('public.wb104b', :'wc_sib'),
  'LIVENESS: a legitimate child is blocked too, so the pass below has real work on both');

-- retention off entirely: nothing is eligible, so the reconciler's removal arm runs for every child
update pgpm.config set retain = null where parent_table = 'public.wb104b'::regclass;
select pgpm._enforce_write_blocks('public.wb104b');

select ok(not pgpm._is_write_blocked('public.wb104b', :'wc_sib'),
  'LIVENESS: the legitimate child is unblocked, so the removal arm of the pass really ran');
select ok(not exists (select 1 from pg_trigger where tgname = 'pgpm_write_block'
                         and tgrelid = format('public.%I', :'wc_doomed')::regclass),
  'and the stranded trigger is lifted off the substitute too: removal is name-based on purpose');
select lives_ok(
  format($$ insert into public.%I (id, payload) values (9002, 'z') $$, :'wc_doomed'),
  'so the relation pgpm should never have touched accepts writes again');

-- ============ PART C: a name that resolves to NOTHING is not this check's business ============
--
-- retire() and _archive_step both fire their identity checks on a name resolving to nothing as well,
-- because the next thing either would do is act on the relation. This one does not, and the boundary
-- is asserted here rather than left to be inferred: a dropped partition has no wrong relation to act
-- on, the `::regclass` cast raises, and _enforce_write_blocks' per-child handler logs
-- skip_write_block carrying the real error -- the behaviour issue #360 built and tests/94 proves.
-- Intercepting it would replace an accurate report with a misleading one (this refusal means
-- "something else holds the name") AND would stop tests/94's poison raising at all, quietly
-- retiring the loop-isolation coverage that file exists for.
create table public.wb104c (id bigint generated by default as identity primary key, payload text);
insert into public.wb104c (payload) select 'x' from generate_series(1, 5);
call pgpm.transmute('public.wb104c', 'id', 1000, p_retain => 18000, p_paused => false);
insert into public.wb104c (id, payload) values (20000, 'frontier');

select child_name as wd_doomed from pgpm.part
  where parent_table = 'public.wb104c'::regclass and lo = '0' \gset

-- gone entirely, not substituted: the pgpm.part row survives pointing at nothing
select format('drop table public.%I', :'wd_doomed') \gexec

select is((select to_regclass(format('public.%I', :'wd_doomed'))::text), NULL,
  'LIVENESS: the name resolves to nothing at all, and the pgpm.part row still points at it');
select lives_ok(
  $$ select pgpm._enforce_write_blocks('public.wb104c') $$,
  'the pass still absorbs it rather than raising');
select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.wb104c'::regclass and action = 'fail_write_block_identity'),
  0, 'and does NOT call it an identity mismatch: nothing took the name, the partition is simply gone');
select ok(
  (select method from pgpm.log
    where parent_table = 'public.wb104c'::regclass and action = 'skip_write_block') like '%does not exist%',
  'it keeps the pre-existing skip_write_block path, carrying the real underlying error');

select * from finish();
