-- untransmute's one-way door is decided under the lock that acts on it (issue #443).
--
-- untransmute refuses when any row lives outside the original monolith, because a metadata-only reverse
-- would drop it with the parent. That check used to run once, under ACCESS SHARE, and the DETACH and DROP
-- that acted on its answer took their ACCESS EXCLUSIVE later. A writer whose insert into a forward
-- partition was uncommitted at the check, and committed before that lock was granted, lost its row, and
-- pgpm.log recorded the untransmute as a success. Now untransmute takes the lock explicitly and asks
-- again under it.
--
-- The race needs a second session, which a pgTAP file gets through dblink, the way tests/60 and 77 do:
-- a WRITER connection holds an uncommitted forward-partition insert; an UNTRANSMUTE connection runs the
-- reverse asynchronously (dblink_send_query) and parks on the parent's ACCESS EXCLUSIVE, behind the
-- writer's ROW EXCLUSIVE; this session polls pg_locks until it sees that wait, records the writer's state
-- at that instant (the liveness witnesses), then commits the writer and collects untransmute's verdict.
-- No sleep is load-bearing: the writer holds until told, so the state being witnessed cannot be missed.
--
-- WHILE UNTRANSMUTE WAITS, THIS SESSION MUST NOT TOUCH public.ur109. A new ACCESS SHARE request queues
-- behind a PENDING ACCESS EXCLUSIVE, so a read of the table here would block until the writer commits,
-- which this session is the one meant to do. Every witness in that window reads pg_locks and
-- pg_stat_activity only. bench/untransmute_race.sh is the same choreography from three OS processes;
-- this file gives the version matrix the same race.
create extension if not exists pgtap;
create extension if not exists dblink;

select plan(23);

-- ---- fixture: a transmuted table with empty forward partitions, the state untransmute reverses ----
create table public.ur109 (
  id         bigint      generated by default as identity,
  created_at timestamptz not null default now(),
  body       text,
  primary key (created_at, id)
);
insert into public.ur109 (created_at, body)
  select now() - (g || ' minutes')::interval, 'b' || g from generate_series(1, 100) g;
call pgpm.transmute('public.ur109', 'created_at', interval '1 month');
select pgpm.obtain('public.ur109');

-- the monolith (smallest lo), and a timestamp one hour past its hi: the first forward partition
select child_name as mon, hi as mon_hi from pgpm.part
  where parent_table = 'public.ur109'::regclass and attached order by lo::timestamptz limit 1 \gset
select (:'mon_hi'::timestamptz + interval '1 hour')::text as late_ts \gset
select child_name as fwd from pgpm.part
  where parent_table = 'public.ur109'::regclass and attached
    and lo::timestamptz <= :'late_ts'::timestamptz and hi::timestamptz > :'late_ts'::timestamptz \gset
select isnt(:'fwd'::text, :'mon'::text,
  'fixture: the late row targets a forward partition, not the monolith');

-- ============================ (A) the race, deterministically ============================
-- The WRITER: one row into a forward partition, left uncommitted.
select dblink_connect('w109', 'dbname=' || current_database());
select dblink_exec('w109', $$set application_name = 'ur109_writer'$$);
select dblink_exec('w109', 'begin');
select dblink_exec('w109', format(
  $$insert into public.ur109 (id, created_at, body) values (7777, %L, 'late')$$, :'late_ts'));

select is(
  (select count(*)::int from pg_locks l join pg_stat_activity a on a.pid = l.pid
    where a.application_name = 'ur109_writer'
      and l.locktype = 'relation' and l.relation = 'public.ur109'::regclass
      and l.mode = 'RowExclusiveLock' and l.granted),
  1, 'LIVENESS: the writer holds ROW EXCLUSIVE on the parent, its insert in flight');
-- The last read of public.ur109 this session makes until untransmute has returned (see the header).
select is((select count(*)::int from public.ur109 where id = 7777), 0,
  'LIVENESS: and its row is invisible to everyone else, as it will be to untransmute''s first check');

-- UNTRANSMUTE, in a session of its own, asynchronously: it passes its unlocked check and parks on the lock.
select dblink_connect('u109', 'dbname=' || current_database());
select dblink_exec('u109', $$set application_name = 'ur109_untransmute'$$);
select dblink_send_query('u109', $$select pgpm.untransmute('public.ur109')$$);

-- Poll for the WAIT, not for a guessed interval. Bounded at 30 s so a broken fixture fails rather than hangs.
-- pg_stat_activity is read once per transaction and then frozen (the documented snapshot; a DO block is
-- one transaction), so the loop clears it each turn (#713). It happened to work without that: pg_locks is
-- live, and the backend it joins was in the first snapshot with its application_name already set.
do $$
begin
  for i in 1 .. 600 loop
    perform pg_stat_clear_snapshot();
    exit when exists (select 1 from pg_locks l join pg_stat_activity a on a.pid = l.pid
                       where a.application_name = 'ur109_untransmute'
                         and l.locktype = 'relation' and l.relation = 'public.ur109'::regclass
                         and l.mode = 'AccessExclusiveLock' and not l.granted);
    perform pg_sleep(0.05);
  end loop;
end $$;

-- The witnesses that make the verdict below mean something: untransmute has already run its unlocked
-- check (it is past it, waiting for the lock), and the row it did not see is still uncommitted.
select is(
  (select count(*)::int from pg_locks l join pg_stat_activity a on a.pid = l.pid
    where a.application_name = 'ur109_untransmute' and a.query like '%pgpm.untransmute%'
      and l.locktype = 'relation' and l.relation = 'public.ur109'::regclass
      and l.mode = 'AccessExclusiveLock' and not l.granted),
  1, 'LIVENESS: untransmute passed its first check and is waiting for ACCESS EXCLUSIVE on the parent');
select is(
  (select count(*)::int from pg_stat_activity
    where application_name = 'ur109_writer' and backend_xid is not null),
  1, 'LIVENESS: while the writer''s insert is still uncommitted (open xid)');

-- Release: the writer commits, untransmute gets its lock, and what it does next is the property.
select dblink_exec('w109', 'commit');
select throws_like(
  $$ select * from dblink_get_result('u109') as t(r text) $$,
  '%rows now live outside the original monolith%',
  'untransmute refuses: the row that committed while it waited is outside the monolith');
select dblink_disconnect('u109');
select dblink_disconnect('w109');

-- Identity, not cardinality: WHICH row survived, and WHERE.
select is((select body from public.ur109 where id = 7777), 'late',
  'row 7777 is still reachable through the parent');
select is(
  (select relname::text from pg_class where oid = (select tableoid from public.ur109 where id = 7777)),
  :'fwd'::text, 'in the forward partition it was written to');
select is((select relkind::text from pg_class where oid = 'public.ur109'::regclass), 'p',
  'the parent is still the partitioned table: the refusal rolled the whole call back');
select is((select count(*)::int from pgpm.config where parent_table = 'public.ur109'::regclass), 1,
  'pgpm still manages it');
select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.ur109'::regclass and action = 'untransmute'),
  0, 'and no untransmute success row was logged');
select ok(
  (select string_agg(id::text, ',' order by id) from public.ur109 where id <> 7777)
    = (select string_agg(g::text, ',' order by g) from generate_series(1, 100) g),
  'rows 1..100 are all still there, by identity');

-- ============================ (B) the refusal is clean, and not a count ============================
-- Two committed strays in DIFFERENT forward partitions, removed one at a time: refused at two, refused
-- at one (so the gate is not counting to two), open at none. An asymmetric fixture, so a check that
-- passed for the wrong reason would have to be wrong twice in compensating ways.
insert into public.ur109 (id, created_at, body)
  values (8888, :'late_ts'::timestamptz + interval '40 days', 'later');
select isnt(
  (select tableoid::regclass::text from public.ur109 where id = 8888),
  (select tableoid::regclass::text from public.ur109 where id = 7777),
  'the two strays sit in different forward partitions');
select throws_like(
  $$ select pgpm.untransmute('public.ur109') $$,
  '%rows now live outside the original monolith%',
  'two committed strays: refused');
delete from public.ur109 where id = 8888;
select throws_like(
  $$ select pgpm.untransmute('public.ur109') $$,
  '%rows now live outside the original monolith%',
  'one stray left: still refused');
delete from public.ur109 where id = 7777;
select lives_ok(
  $$ select pgpm.untransmute('public.ur109') $$,
  'no row outside the monolith: the reverse goes through');
select is((select relkind::text from pg_class where oid = 'public.ur109'::regclass), 'r',
  'ur109 is an ordinary table again');
select ok(
  (select string_agg(id::text, ',' order by id) from public.ur109)
    = (select string_agg(g::text, ',' order by g) from generate_series(1, 100) g),
  'holding exactly rows 1..100');
select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.ur109'::regclass and action = 'untransmute'),
  1, 'with the one successful reverse logged');

-- ============================ (C) the under-lock check needs READ COMMITTED ============================
-- The second check is only worth something if its snapshot postdates the lock. REPEATABLE READ pins the
-- transaction's first snapshot, taken before untransmute is entered, so the re-check would be blind to
-- the very row it exists to see. untransmute refuses up front rather than proceed on a stale snapshot.
create table public.ur109_rr (
  id         bigint      generated by default as identity,
  created_at timestamptz not null default now(),
  body       text,
  primary key (created_at, id)
);
insert into public.ur109_rr (created_at, body)
  select now() - (g || ' minutes')::interval, 'r' || g from generate_series(1, 10) g;
call pgpm.transmute('public.ur109_rr', 'created_at', interval '1 month');

begin isolation level repeatable read;
select throws_like(
  $$ select pgpm.untransmute('public.ur109_rr') $$,
  '%READ COMMITTED%',
  'under REPEATABLE READ untransmute refuses up front');
commit;
select is((select relkind::text from pg_class where oid = 'public.ur109_rr'::regclass), 'p',
  'and leaves the table managed and partitioned');
select lives_ok(
  $$ select pgpm.untransmute('public.ur109_rr') $$,
  'the same call under READ COMMITTED goes through');
select is((select relkind::text from pg_class where oid = 'public.ur109_rr'::regclass), 'r',
  'and restores the ordinary table');

select * from finish();
