-- The archive strategy's return was recorded as fact, and it is only a claim (issue #454).
--
-- pgpm._archive_step hands the configured archive_fn one chunk [p_lo, p_hi) of a write-blocked
-- partition and writes whatever covered_hi it returns straight into pgpm.archive_ledger. That ledger
-- is what pgpm._archive_fully_covered consults as retire()'s drop precondition. So a strategy bug
-- that answers with a covered_hi past the chunk (the bug hunt's repro: chunk [0,15) answered with
-- 15000 and rows_archived 0) marks the partition fully covered on the spot, and the next retain()
-- drops it with nothing archived. archive_fn is a published extension point, so the bug is not
-- hypothetical: it is any user-authored strategy that gets the arithmetic wrong once.
--
-- Three more returns were just as unchecked and each wedged or poisoned retention differently:
-- covered_hi = p_lo wrote a (lo, lo) ledger row, and since the next tick resumes from max(hi) = lo
-- it hands the strategy the same chunk and collides on the ledger's primary key forever (the
-- zero-progress wedge); a null covered_hi wrote a null hi; and a value that is not even a native
-- grid value went into the text hi column unchallenged, after which every max(hi::numeric) over the
-- ledger raised. Pre-fix, maintain() would have reported the last two as a skip_archive DEFERRAL,
-- tick after tick, for what is a permanent strategy bug.
--
-- The fix holds the return to the promise the call made: covered_hi must be a native value with
-- p_lo < covered_hi <= p_hi. On a breach _archive_step writes no ledger row, logs exactly
-- fail_archive_contract with the chunk, the value returned and the rule it broke, and moves on;
-- status().retain_drop_failures counts it alongside the other things that stall retention. Every
-- refusal below is paired with the strategy's own record of the call it received, so a run in
-- which the strategy was never handed that chunk cannot satisfy the negative assertions by accident.
create extension if not exists pgtap;

select plan(36);

create schema pgpm_test115;

-- What each strategy was actually asked. This is the liveness witness for every refusal below: the
-- rule under test is "the return was rejected", which a run that never made the call also satisfies.
create table pgpm_test115.calls (strategy text, p_child name, p_lo text, p_hi text);

-- Four misbehaving strategies, one per way the return can break the contract. Each records its call
-- and returns rows_archived = 0, as the bug hunt's strategy did.
create function pgpm_test115.overshoot(p_parent regclass, p_child name, p_lo text, p_hi text)
returns pgpm.archive_result language plpgsql as $$
declare v pgpm.archive_result;
begin
  insert into pgpm_test115.calls values ('overshoot', p_child, p_lo, p_hi);
  v.covered_hi := (p_hi::numeric * 1000)::text;   -- the issue's 15000 for [0,15): a thousand times past the chunk
  v.rows_archived := 0;
  return v;
end $$;

create function pgpm_test115.stall(p_parent regclass, p_child name, p_lo text, p_hi text)
returns pgpm.archive_result language plpgsql as $$
declare v pgpm.archive_result;
begin
  insert into pgpm_test115.calls values ('stall', p_child, p_lo, p_hi);
  v.covered_hi := p_lo;   -- "no progress": the (lo, lo) row that wedges the ledger on its primary key
  v.rows_archived := 0;
  return v;
end $$;

create function pgpm_test115.blank(p_parent regclass, p_child name, p_lo text, p_hi text)
returns pgpm.archive_result language plpgsql as $$
declare v pgpm.archive_result;
begin
  insert into pgpm_test115.calls values ('blank', p_child, p_lo, p_hi);
  v.covered_hi := null;
  v.rows_archived := 0;
  return v;
end $$;

create function pgpm_test115.garbage(p_parent regclass, p_child name, p_lo text, p_hi text)
returns pgpm.archive_result language plpgsql as $$
declare v pgpm.archive_result;
begin
  insert into pgpm_test115.calls values ('garbage', p_child, p_lo, p_hi);
  v.covered_hi := 'not a number';   -- the ledger's hi is text, so pre-fix this went in and poisoned every later max(hi::numeric)
  v.rows_archived := 0;
  return v;
end $$;

-- Monolith [0,1000) holding 7 rows, and a frontier row at 20000 with retain 19000, so the retention
-- horizon is exactly 1000 and the monolith is the ONLY eligible partition: every _archive_step call
-- below has one candidate and one chunk, [0, 1000), so what each strategy was handed is fixed.
create table public.ac115 (id bigint generated by default as identity primary key, payload text);
insert into public.ac115 (payload) select 'x' from generate_series(1, 7);                    -- ids 1..7
call pgpm.transmute('public.ac115', 'id', 1000, p_retain => 19000, p_paused => false);       -- monolith [0,1000)
insert into public.ac115 (id, payload) values (20000, 'frontier');                           -- horizon 1000

select child_name as ac_child from pgpm.part
  where parent_table = 'public.ac115'::regclass and lo = '0' \gset

select is((select count(*)::int from public.ac115 where id < 1000), 7,
  'fixture: the monolith holds 7 rows');
select is((select pgpm._retain_boundary(c) from pgpm.config c where c.parent_table = 'public.ac115'::regclass),
  '1000', 'fixture: the retention horizon is exactly the monolith''s hi, so it is the only eligible partition');

-- the write block a maintain() tick installs; archiving only ever picks up an already-blocked child
select pgpm._enforce_write_blocks('public.ac115');

-- The first strategy is set BEFORE the liveness checks: with archive_fn still null (strategy 'none')
-- _archive_fully_covered is trivially true and "not yet covered" would be asserting nothing.
select pgpm.set_archive_fn('public.ac115', 'pgpm_test115.overshoot(regclass,name,text,text)'::regprocedure);

select ok(pgpm._is_write_blocked('public.ac115', :'ac_child'),
  'LIVENESS: the monolith is write-blocked, so it is an archive candidate');
select ok(not pgpm._archive_fully_covered('public.ac115', :'ac_child'),
  'LIVENESS: and not yet covered, so the step will hand its chunk to the strategy');

-- ============================ overshoot: covered_hi past the chunk ============================
-- The issue's own repro. Pre-fix this wrote ledger (0, 1000000), _archive_fully_covered went true,
-- and retire() dropped the monolith with 0 rows archived.
select is(pgpm._archive_step('public.ac115'), 0,
  'overshoot: the step records no chunk (and does not raise)');
select results_eq(
  $$ select p_child, p_lo, p_hi from pgpm_test115.calls where strategy = 'overshoot' $$,
  format($$ values (%L::name, '0'::text, '1000'::text) $$, :'ac_child'),
  'LIVENESS: the strategy was called exactly once, for the monolith''s chunk [0, 1000)');
select is((select count(*)::int from pgpm.archive_ledger where parent_table = 'public.ac115'::regclass), 0,
  'overshoot: no ledger row was written from the claim');
select results_eq(
  $$ select action, lo, hi from pgpm.log
      where parent_table = 'public.ac115'::regclass and action like 'fail_%' $$,
  $$ values ('fail_archive_contract'::text, '0'::text, '1000'::text) $$,
  'overshoot: refused as exactly fail_archive_contract, naming the chunk handed to the strategy');
select ok(
  (select method from pgpm.log where parent_table = 'public.ac115'::regclass and action = 'fail_archive_contract')
    like '%pgpm_test115.overshoot(regclass,name,text,text)%covered_hi ''1000000''%[0, 1000)%must not exceed hi%',
  'overshoot: method names the strategy, the value it returned, the chunk, and the rule it broke');
select ok(not pgpm._archive_fully_covered('public.ac115', :'ac_child'),
  'overshoot: the coverage gate stays shut');
select ok(not pgpm.retire('public.ac115', :'ac_child'),
  'overshoot: so retire() refuses the drop; pre-fix this returned true');
select is((select count(*)::int from public.ac115 where id < 1000), 7,
  'overshoot: all 7 rows are still in the monolith');

-- ============================ stall: covered_hi = p_lo (the zero-progress wedge) ============================
select pgpm.set_archive_fn('public.ac115', 'pgpm_test115.stall(regclass,name,text,text)'::regprocedure);

select is(pgpm._archive_step('public.ac115'), 0,
  'stall: the step records no chunk');
select results_eq(
  $$ select p_child, p_lo, p_hi from pgpm_test115.calls where strategy = 'stall' $$,
  format($$ values (%L::name, '0'::text, '1000'::text) $$, :'ac_child'),
  'LIVENESS: the stalling strategy was handed the same chunk [0, 1000)');
select is((select count(*)::int from pgpm.archive_ledger where parent_table = 'public.ac115'::regclass), 0,
  'stall: no (lo, lo) ledger row was written');
select ok(
  (select method from pgpm.log where parent_table = 'public.ac115'::regclass
     and action = 'fail_archive_contract' order by id desc limit 1)
    like '%pgpm_test115.stall(regclass,name,text,text)%covered_hi ''0''%[0, 1000)%must be above lo%',
  'stall: method names the strategy, the returned lo, the chunk, and the rule it broke');
-- Pre-fix the FIRST stalled tick wrote (0, 0) and the SECOND died on the ledger's primary key, and
-- every tick after it. Post-fix a second tick is just another refusal.
select is(pgpm._archive_step('public.ac115'), 0,
  'stall: a second tick is refused again rather than dying on the ledger''s primary key');
select is((select count(*)::int from pgpm_test115.calls where strategy = 'stall'), 2,
  'LIVENESS: the stalling strategy was called on both ticks');

-- ============================ blank: covered_hi null ============================
select pgpm.set_archive_fn('public.ac115', 'pgpm_test115.blank(regclass,name,text,text)'::regprocedure);

select is(pgpm._archive_step('public.ac115'), 0,
  'null: the step records no chunk');
select results_eq(
  $$ select p_child, p_lo, p_hi from pgpm_test115.calls where strategy = 'blank' $$,
  format($$ values (%L::name, '0'::text, '1000'::text) $$, :'ac_child'),
  'LIVENESS: the null-returning strategy was handed the same chunk [0, 1000)');
select is((select count(*)::int from pgpm.archive_ledger where parent_table = 'public.ac115'::regclass), 0,
  'null: no ledger row was written');
select ok(
  (select method from pgpm.log where parent_table = 'public.ac115'::regclass
     and action = 'fail_archive_contract' order by id desc limit 1)
    like '%pgpm_test115.blank(regclass,name,text,text)%covered_hi null%[0, 1000)%',
  'null: method names the strategy, the null it returned, and the chunk');

-- ============================ garbage: covered_hi not a native value, through a whole maintain() tick ============================
-- Driven through maintain() rather than _archive_step directly: pre-fix the garbage went into the
-- text hi column and every later coverage check raised, which maintain() reported as skip_archive
-- and skip_retain deferrals, tick after tick, for a permanent strategy bug. Post-fix the tick
-- completes, the refusal is a fail_ row, and no deferral is logged.
select pgpm.set_archive_fn('public.ac115', 'pgpm_test115.garbage(regclass,name,text,text)'::regprocedure);

call pgpm.maintain('public.ac115');

select results_eq(
  $$ select p_child, p_lo, p_hi from pgpm_test115.calls where strategy = 'garbage' $$,
  format($$ values (%L::name, '0'::text, '1000'::text) $$, :'ac_child'),
  'LIVENESS: the garbage-returning strategy was handed the same chunk [0, 1000) by the maintain() tick');
select is((select count(*)::int from pgpm.archive_ledger where parent_table = 'public.ac115'::regclass), 0,
  'garbage: no ledger row was written, so nothing downstream ever casts it');
select ok(
  (select method from pgpm.log where parent_table = 'public.ac115'::regclass
     and action = 'fail_archive_contract' order by id desc limit 1)
    like '%pgpm_test115.garbage(regclass,name,text,text)%covered_hi ''not a number''%[0, 1000)%not a numeric value%',
  'garbage: method names the strategy, the value it returned, the chunk, and that it is not a native value');
select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.ac115'::regclass and action like 'skip_%'),
  0, 'garbage: the tick logged no skip_ deferral; a contract breach is a failure, not something to retry as-is');

-- ============================ the tally ============================
select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.ac115'::regclass and action = 'fail_archive_contract'),
  5, 'five refusals logged in all: overshoot, stall twice, null, garbage');
select is(
  (select retain_drop_failures from pgpm.status() where parent = 'public.ac115'::regclass),
  5::bigint,
  'status() counts all five alongside the other things that stall retention, so an operator sees the wedge');
select is(
  (select count(*)::int from pgpm.part where parent_table = 'public.ac115'::regclass and child_name = :'ac_child'),
  1, 'the monolith is still a tracked partition');
select is((select count(*)::int from public.ac115 where id < 1000), 7,
  'and still holds all 7 rows: four bad strategies and five ticks archived nothing and dropped nothing');

-- ============================ positive control: a well-behaved strategy on the SAME chunk ============================
-- Nothing above should have moved the ledger, so a correct strategy is handed the very same chunk
-- and retention proceeds from there: the breach is retryable, unlike the identity refusals.
select pgpm.set_archive_fn('public.ac115', 'pgpm._archive_noop(regclass,name,text,text)'::regprocedure);

call pgpm.maintain('public.ac115');

select results_eq(
  $$ select lo, hi, child_name, rows_archived from pgpm.archive_ledger where parent_table = 'public.ac115'::regclass $$,
  format($$ values ('0'::text, '1000'::text, %L::name, 7::bigint) $$, :'ac_child'),
  'control: the well-behaved strategy''s claim for the same chunk [0, 1000) is recorded, with its real 7 rows');
select is(
  (select count(*)::int from pgpm.part where parent_table = 'public.ac115'::regclass and child_name = :'ac_child'),
  0, 'control: coverage complete, so the same tick''s retain() dropped the monolith');
select results_eq(
  $$ select lo, hi from pgpm.log where parent_table = 'public.ac115'::regclass and action = 'retain_drop' $$,
  $$ values ('0'::text, '1000'::text) $$,
  'control: exactly one retain_drop, for the monolith');
select results_eq(
  $$ select id from public.ac115 order by id $$,
  $$ values (20000::bigint) $$,
  'control: the 7 archived rows are gone with the partition and the frontier row is untouched');
select is(
  (select retain_drop_failures from pgpm.status() where parent = 'public.ac115'::regclass),
  0::bigint,
  'control: the since-last-progress count is back at zero once a real drop lands');
select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.ac115'::regclass and action = 'fail_archive_contract'),
  5, 'control: the well-behaved strategy added no refusal of its own');

select * from finish();
