-- _detach_reap must finalize an ABANDONED concurrent detach and leave a LIVE one alone (issue #453).
--
-- THE BUG. _detach_reap finalized every `pg_inherits.inhdetachpending` row under a managed parent, with
-- no check that the session running the detach was gone. The pgpm_detach job and maintain_all share a
-- cadence, and a concurrent detach's wait phase lasts exactly as long as the longest open transaction on
-- the parent, so maintain_all routinely met a detach that was alive and waiting, and finalized it. That
-- skips PostgreSQL's wait-for-old-snapshots phase (the whole point of CONCURRENTLY) and the real detacher
-- then fails with `relation ... is not a partition of relation ...`, once per tick, into cron's log.
--
-- MEASURED, and load-bearing for the fix: a detacher parked in its wait phase holds NO relation lock.
-- Its first transaction (SHARE UPDATE EXCLUSIVE on parent and partition, set the flag) COMMITS before it
-- starts waiting, and the wait is a bare VirtualXactLock() on each lock holder's vxid. Its only pg_locks
-- rows are its own vxid and a not-granted ShareLock on the holder's. So "does anyone hold a lock on the
-- partition" cannot tell a waiting detacher from a dead one, and the reaper reads three signals instead,
-- any one of which means the detach is live:
--   1. some other backend holds or awaits SHARE UPDATE EXCLUSIVE or ACCESS EXCLUSIVE on the partition:
--      the detacher's finalizing transaction (any role can see pg_locks);
--   2. some other backend is executing a DETACH PARTITION ... CONCURRENTLY naming the partition:
--      every phase, but pg_stat_activity.query is masked for a backend owned by another role;
--   3. some other backend is parked on the vxid of a transaction that holds a lock on the parent:
--      the wait phase, from any role, pg_locks only.
-- Each section below is built so that exactly one thing separates pass from fail:
--   1. live, same role: the reaper leaves a waiting detach alone and the detacher then completes;
--   2. live, wait phase, reaper as a role for which the statement is masked: signal 3 alone;
--   3. live, finalizing phase parked behind a reader's lock on the partition, masked: signal 1 alone;
--   4. abandoned (backend terminated), holder still open on the parent: finalized, exactly one.
--
-- HOLDER SHAPE. Read committed, not repeatable read (tests/77's choice). Any isolation level keeps the
-- parent's AccessShareLock to commit, and the lock is what parks the detach. But FINALIZE also waits for
-- older SNAPSHOTS, and a repeatable-read holder pins one, so against the pre-fix code it would BLOCK the
-- reaper rather than let it finalize, and the defect would present as a hang instead of a red
-- assertion. Read committed drops its snapshot at statement end and keeps the lock. The read is pruned to
-- the frontier partition so the holder locks the parent and NOT the doomed child, for the same reason:
-- a lock on the child blocks FINALIZE for a different reason and again hides the defect behind the
-- instrument. Both facts are asserted as REACHABLE witnesses before the reap.
--
-- PROBE COST. The wait phase is held open by the holder's transaction and ends only when this file
-- commits it, so the window cannot expire under the poll; and the poll reads pg_inherits and pg_locks
-- only, locking nothing the detach needs, so it cannot starve the code under test.
create extension if not exists pgtap;
create extension if not exists dblink;

select plan(42);

-- ======================================= fixture =======================================
-- 50000 rows -> monolith [0,60000); frontier at 110000; retain 30000 puts the horizon at 80000. Each
-- section detaches ONE child, by name, and asserts on that name: the monolith (which holds every row,
-- so "rows invisible through the parent" is a real witness) for section 1, then one empty forward child
-- for each of the others. Eligibility does not matter to _detach_reap, only inhdetachpending does.
create table public.lv116 (id bigint generated by default as identity primary key, payload text);
insert into public.lv116 (payload) select 'x' from generate_series(1, 50000);
call pgpm.transmute('public.lv116', 'id', 10000, p_retain => 30000);
select pgpm.obtain('public.lv116');
insert into public.lv116 (id, payload) values (110000, 'frontier');

select child_name as c_live   from pgpm.part where parent_table = 'public.lv116'::regclass and lo = '0' \gset
select child_name as c_masked from pgpm.part where parent_table = 'public.lv116'::regclass and lo = '60000' \gset
select child_name as c_final  from pgpm.part where parent_table = 'public.lv116'::regclass and lo = '70000' \gset
select child_name as c_dead   from pgpm.part where parent_table = 'public.lv116'::regclass and lo = '80000' \gset

create schema pgpm_test116;

-- Poll until the detach on p_parent has committed its flag AND session p_pid is parked on a lock of the
-- given type (virtualxid in the wait phase, relation in the finalizing phase). One transaction per call,
-- reading catalogs only.
create function pgpm_test116.parked(p_parent regclass, p_pid int, p_locktype text)
returns boolean language plpgsql as $$
begin
  for i in 1 .. 600 loop
    if exists (select 1 from pg_inherits where inhparent = p_parent and inhdetachpending)
       and exists (select 1 from pg_locks where pid = p_pid and locktype = p_locktype and not granted)
    then return true; end if;
    perform pg_sleep(0.05);
  end loop;
  return false;
end $$;

-- Poll until p_pid has left pg_stat_activity: pg_terminate_backend returns before the backend is gone.
-- pg_stat_activity is read once per transaction and then frozen (the documented snapshot; a function is
-- one transaction), so without clearing it each turn this loop saw its first read 600 times and passed
-- only when the backend had already gone: it ran out on a merge group (#713).
create function pgpm_test116.gone(p_pid int)
returns boolean language plpgsql as $$
begin
  for i in 1 .. 600 loop
    perform pg_stat_clear_snapshot();
    if not exists (select 1 from pg_stat_activity where pid = p_pid) then return true; end if;
    perform pg_sleep(0.05);
  end loop;
  return false;
end $$;

-- Collect an async dblink command's outcome without letting a failure abort the file: one row, either
-- the command tag or the error message. `is(err, null)` then names the failure instead of hiding it.
create table pgpm_test116.outcome (section int, tag text, err text);
create function pgpm_test116.collect(p_conn text, p_section int)
returns void language plpgsql as $$
begin
  insert into pgpm_test116.outcome
    select p_section, t.r, null from dblink_get_result(p_conn) as t(r text);
exception when others then
  insert into pgpm_test116.outcome values (p_section, null, sqlerrm);
end $$;

-- A reaper role that can run _detach_reap's read path but is not the detacher's role and is not
-- pg_read_all_stats, so pg_stat_activity shows it `<insufficient privilege>` for the detacher's row.
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'pgpm_test116_reaper') then
    execute 'drop owned by pgpm_test116_reaper'; execute 'drop role pgpm_test116_reaper';
  end if;
end $$;
create role pgpm_test116_reaper nologin;
grant usage on schema pgpm to pgpm_test116_reaper;
grant select on pgpm.config to pgpm_test116_reaper;

-- A reaper that attempts a FINALIZE it should not can queue behind a lock this file releases only
-- later (section 3's reader holds the partition). Bound that, so a wrong answer is a red assertion
-- rather than a hang.
set lock_timeout = '2s';

-- ======================= 1. live, same role: a waiting detach survives the reap =======================
select dblink_connect('h', 'dbname=' || current_database());
select dblink_exec('h', 'begin');
select * from dblink('h', 'select count(*) from public.lv116 where id = 110000') as t(c bigint);
select * from dblink('h', 'select pg_backend_pid()') as t(hpid int) \gset

select dblink_connect('d', 'dbname=' || current_database());
select * from dblink('d', 'select pg_backend_pid()') as t(dpid int) \gset
select dblink_send_query('d',
  format('alter table public.lv116 detach partition public.%I concurrently', :'c_live'));

select ok(pgpm_test116.parked('public.lv116', :dpid, 'virtualxid'),
  'LIVENESS: the detach committed its flag and its session is parked in the wait phase');

-- WITNESSES. Every negative below ("did not finalize", "logged nothing") is satisfied by a run in which
-- there was never a live detach to spare, or in which FINALIZE could not have gone through anyway.
select is(
  (select count(*)::int from pg_inherits i join pg_class c on c.oid = i.inhrelid
    where i.inhparent = 'public.lv116'::regclass and c.relname = :'c_live' and i.inhdetachpending),
  1, 'LIVENESS: the named partition is pending detach');

select is(
  (select state || '/' || wait_event_type || '/' || wait_event from pg_stat_activity where pid = :dpid),
  'active/Lock/virtualxid', 'LIVENESS: the detacher is alive and waiting on the holder''s vxid');

select cmp_ok((select count(*) from public.lv116), '<', 50001::bigint,
  'LIVENESS: the pending state is real: the rows are already invisible through the parent');

select is((select count(*)::int from pg_locks where pid = :dpid and locktype = 'relation'), 0,
  'MEASURED: a waiting detacher holds no relation lock, so a lock on the partition cannot vouch for it');

select ok((select backend_xmin is null from pg_stat_activity where pid = :hpid),
  'REACHABLE: the holder pins the parent''s lock but no snapshot, so FINALIZE would not block on it');

select is(
  (select count(*)::int from pg_locks
    where locktype = 'relation' and relation = format('public.%I', :'c_live')::regclass
      and pid <> pg_backend_pid()),
  0, 'REACHABLE: and nobody locks the doomed partition, so FINALIZE would not block on that either');

-- THE REAP. Pre-fix this returned 1, removed the pg_inherits row and logged detach_reap.
select is(pgpm._detach_reap(), 0,
  '_detach_reap() finalizes nothing while the detach''s own session is alive and waiting');

select is(
  (select count(*)::int from pg_inherits i join pg_class c on c.oid = i.inhrelid
    where i.inhparent = 'public.lv116'::regclass and c.relname = :'c_live' and i.inhdetachpending),
  1, 'the pending row is left for the session that owns it');

select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.lv116'::regclass
    and action in ('detach_reap', 'fail_detach_reap', 'skip_detach_reap')),
  0, 'and nothing is logged: a detach in progress is the expected state, not a deferral');

select is(
  (select state || '/' || wait_event_type || '/' || wait_event from pg_stat_activity where pid = :dpid),
  'active/Lock/virtualxid', 'the detacher is still parked, undisturbed by the reap');

-- Release the holder; the detacher must now complete on its own.
select dblink_exec('h', 'commit');
select pgpm_test116.collect('d', 1);

select is((select tag from pgpm_test116.outcome where section = 1), 'ALTER TABLE',
  'the detacher then completes on its own: its wait-for-old-snapshots phase ran to the end');
select is((select err from pgpm_test116.outcome where section = 1), null,
  'and did not fail with "is not a partition", which is what a premature FINALIZE does to it');

select is(
  (select count(*)::int from pg_inherits i join pg_class c on c.oid = i.inhrelid
    where i.inhparent = 'public.lv116'::regclass and c.relname = :'c_live'),
  0, 'the partition is detached, by the session that started the detach');
select isnt((select to_regclass(format('public.%I', :'c_live'))::text), NULL,
  'and left standing: neither the detach nor the reaper drops anything');

select dblink_disconnect('h');
select dblink_disconnect('d');

-- ============ 2. live, wait phase, reaper role for which the statement is masked: signal 3 ============
-- The deployment's two cron jobs share a role, so the reaper normally sees the detacher's statement. An
-- operator's hand-run detach under another role is the case that cannot be seen that way, and the
-- reaper must still not finalize it. pg_locks is never masked.
select dblink_connect('h', 'dbname=' || current_database());
select dblink_exec('h', 'begin');
select * from dblink('h', 'select count(*) from public.lv116 where id = 110000') as t(c bigint);

select dblink_connect('d', 'dbname=' || current_database());
select * from dblink('d', 'select pg_backend_pid()') as t(dpid int) \gset
select dblink_send_query('d',
  format('alter table public.lv116 detach partition public.%I concurrently', :'c_masked'));

select ok(pgpm_test116.parked('public.lv116', :dpid, 'virtualxid'),
  'LIVENESS: the second detach is pending and parked in its wait phase');

-- pgTAP's bookkeeping lives in this session's temp objects, which the reaper role cannot touch, so its
-- observations go through set_config and are asserted after `reset role`. A reaper that wrongly
-- attempts the FINALIZE fails on ownership as this role; catch that and assert on it, so the wrong
-- answer is a red assertion naming the error rather than an aborted file.
set role pgpm_test116_reaper;
select set_config('t116.masked_query',
  (select query from pg_stat_activity where pid = :dpid), false);
select set_config('t116.masked_state',
  coalesce((select state from pg_stat_activity where pid = :dpid), '<null>'), false);
do $$ begin
  perform set_config('t116.reaped', pgpm._detach_reap()::text, false);
exception when others then
  perform set_config('t116.reaped', 'ERROR: ' || sqlerrm, false);
end $$;
reset role;

select is(current_setting('t116.masked_query'), '<insufficient privilege>',
  'DISCRIMINATION: from the reaper''s role the detacher''s statement is masked');
select is(current_setting('t116.masked_state'), '<null>',
  'DISCRIMINATION: and so is its state, so pg_stat_activity can vouch for nothing here');

select is(current_setting('t116.reaped'), '0',
  'the reaper still finalizes nothing: a waiter parked on the vxid of a lock holder on the parent is live');

select is(
  (select count(*)::int from pg_inherits i join pg_class c on c.oid = i.inhrelid
    where i.inhparent = 'public.lv116'::regclass and c.relname = :'c_masked' and i.inhdetachpending),
  1, 'the pending row is untouched');

select dblink_exec('h', 'commit');
select pgpm_test116.collect('d', 2);

select is((select tag from pgpm_test116.outcome where section = 2), 'ALTER TABLE',
  'and the masked detacher completes on its own');
select is((select err from pgpm_test116.outcome where section = 2), null,
  'without "is not a partition"');

select is(
  (select count(*)::int from pg_inherits i join pg_class c on c.oid = i.inhrelid
    where i.inhparent = 'public.lv116'::regclass and c.relname = :'c_masked'),
  0, 'the second partition is detached, by its own session');

select dblink_disconnect('h');
select dblink_disconnect('d');

-- ===== 3. live, finalizing phase parked behind a reader's lock on the partition, masked: signal 1 =====
-- No holder on the parent this time, so the detach skips straight past its wait phase, and a reader
-- with AccessShareLock on the partition ITSELF parks its third transaction on the ACCESS EXCLUSIVE it
-- needs. Nothing waits on a vxid, the statement is masked: only the lock request on the partition says
-- a detacher is here. Pre-fix, the reaper's FINALIZE queued behind the same lock, stalled maintain_all
-- for the reader's whole transaction, then failed with "is not a partition" once the detacher won.
select dblink_connect('r', 'dbname=' || current_database());
select dblink_exec('r', 'begin');
select format('select count(*) from public.%I', :'c_final') as rd \gset
select * from dblink('r', :'rd') as t(c bigint);

select dblink_connect('d', 'dbname=' || current_database());
select * from dblink('d', 'select pg_backend_pid()') as t(dpid int) \gset
select dblink_send_query('d',
  format('alter table public.lv116 detach partition public.%I concurrently', :'c_final'));

select ok(pgpm_test116.parked('public.lv116', :dpid, 'relation'),
  'LIVENESS: the third detach is pending and parked on a relation lock');

select is(
  (select mode || '/' || granted from pg_locks
    where pid = :dpid and locktype = 'relation'
      and relation = format('public.%I', :'c_final')::regclass),
  'AccessExclusiveLock/false',
  'LIVENESS: that lock is the ACCESS EXCLUSIVE its finalizing transaction wants on the partition');

select is((select count(*)::int from pg_locks where pid = :dpid and locktype = 'virtualxid' and not granted),
  0, 'DISCRIMINATION: it waits on no vxid, so the wait-phase signal is silent here');

set role pgpm_test116_reaper;
select set_config('t116.masked_query',
  (select query from pg_stat_activity where pid = :dpid), false);
do $$ begin
  perform set_config('t116.reaped', pgpm._detach_reap()::text, false);
exception when others then
  perform set_config('t116.reaped', 'ERROR: ' || sqlerrm, false);
end $$;
reset role;

select is(current_setting('t116.masked_query'), '<insufficient privilege>',
  'DISCRIMINATION: and the statement is masked, so the lock request is the only signal left');

select is(current_setting('t116.reaped'), '0',
  'the reaper finalizes nothing: a lock request on the partition itself is a live detacher');

select is(
  (select count(*)::int from pg_inherits i join pg_class c on c.oid = i.inhrelid
    where i.inhparent = 'public.lv116'::regclass and c.relname = :'c_final' and i.inhdetachpending),
  1, 'the pending row is untouched');

select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.lv116'::regclass
    and action in ('detach_reap', 'fail_detach_reap', 'skip_detach_reap')),
  0, 'and still nothing is logged across all three live cases');

select dblink_exec('r', 'commit');
select pgpm_test116.collect('d', 3);

select is((select tag from pgpm_test116.outcome where section = 3), 'ALTER TABLE',
  'the detacher completes once the reader lets go');
select is((select err from pgpm_test116.outcome where section = 3), null,
  'without "is not a partition"');

select dblink_disconnect('r');
select dblink_disconnect('d');

-- ================== 4. abandoned, holder still open on the parent: finalized, exactly one ==================
-- Same setup as section 1, then the detacher is killed in its wait phase. The holder stays OPEN through
-- the reap: a reaper that read "some transaction has the parent locked" as liveness would wrongly
-- defer here, and this is what tells the three signals from that shortcut.
select dblink_connect('h', 'dbname=' || current_database());
select dblink_exec('h', 'begin');
select * from dblink('h', 'select count(*) from public.lv116 where id = 110000') as t(c bigint);
select * from dblink('h', 'select pg_backend_pid()') as t(hpid int) \gset

select dblink_connect('d', 'dbname=' || current_database());
select * from dblink('d', 'select pg_backend_pid()') as t(dpid int) \gset
select dblink_send_query('d',
  format('alter table public.lv116 detach partition public.%I concurrently', :'c_dead'));

select ok(pgpm_test116.parked('public.lv116', :dpid, 'virtualxid'),
  'LIVENESS: the fourth detach is pending and parked in its wait phase before it is killed');

select pg_terminate_backend(:dpid);
select ok(pgpm_test116.gone(:dpid), 'LIVENESS: the detacher''s backend is gone');

select is(
  (select count(*)::int from pg_inherits i join pg_class c on c.oid = i.inhrelid
    where i.inhparent = 'public.lv116'::regclass and c.relname = :'c_dead' and i.inhdetachpending),
  1, 'LIVENESS: the killed detach really did leave the named partition pending: the hazard is real');

select is(
  (select count(*)::int from pg_locks
    where pid = :hpid and locktype = 'relation' and relation = 'public.lv116'::regclass and granted),
  1, 'DISCRIMINATION: the holder still has the parent locked, exactly as it did for the live cases');

select is(
  (select count(*)::int from pg_locks w
     join pg_locks h on h.locktype = 'virtualxid' and h.granted and h.virtualxid = w.virtualxid
    where w.locktype = 'virtualxid' and not w.granted and h.pid = :hpid),
  0, 'DISCRIMINATION: but nobody is parked on its vxid any more: the waiter is what died');

select is(pgpm._detach_reap(), 1,
  '_detach_reap() finalizes the abandoned detach, and only that one');

select is(
  (select count(*)::int from pg_inherits where inhparent = 'public.lv116'::regclass and inhdetachpending),
  0, 'the parent carries no pending detach afterwards');

select isnt((select to_regclass(format('public.%I', :'c_dead'))::text), NULL,
  'finalized, not dropped: the reaper never drops');

select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.lv116'::regclass
    and action = 'detach_reap' and lo = '80000'),
  1, 'logged as exactly detach_reap, for exactly this partition');

select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.lv116'::regclass
    and action in ('detach_reap', 'fail_detach_reap', 'skip_detach_reap')),
  1, 'and that is the only reap row in the file: no live detach was ever finalized by pgpm');

select dblink_exec('h', 'commit');
select dblink_disconnect('h');
select dblink_disconnect('d');

-- ======================================= clean up =======================================
reset lock_timeout;
drop table if exists public.lv116 cascade;
-- the four detached children left the parent's tree, so the cascade above does not reach them
select format('drop table if exists public.%I', :'c_live') \gexec
select format('drop table if exists public.%I', :'c_masked') \gexec
select format('drop table if exists public.%I', :'c_final') \gexec
select format('drop table if exists public.%I', :'c_dead') \gexec
drop schema pgpm_test116 cascade;
drop owned by pgpm_test116_reaper;
drop role pgpm_test116_reaper;

select * from finish();
