-- untransmute hands back the monolith with none of pgpm's OWN apparatus left on it (issue #508).
--
-- untransmute captures and replays the PARENT's row triggers (#277, #499) and DETACH strips the clones of
-- those from the monolith. Neither touches the triggers MAINTENANCE puts directly on the monolith child, so
-- until this fix the restored table came back carrying them, with pgpm.config and pgpm.part gone so no tick
-- could ever lift them:
--
--   pgpm_write_block (retention's fence, _install_write_block). A monolith retention has reached but not
--   dropped, because archiving was deferred (skip_archive) or because coverage kept the block after the
--   frontier regressed (#452, skip_write_block_lift), was handed back as an unmanaged table that rejected
--   every INSERT/UPDATE/DELETE with "past its retention boundary".
--
--   pgpm_regrain_capture and pgpm_regrain_truncate_guard (an in-flight regrain, #267/#449). Pre-swap the
--   monolith still holds every row and the door is open, but the capture trigger depends on the per-parent
--   function untransmute drops at the end, so the whole call died with "cannot drop function ... because
--   other objects depend on it"; and the not-yet-attached fine copies are standalone relations the
--   parent's DROP never reaches, so a reverse that got past that would have orphaned them.
--
-- Now, under the lock and after the second gate, untransmute lifts the write block through
-- _remove_write_block and abandons an in-flight regrain through regrain_cancel (trigger and guard off,
-- copies dropped, delta truncated, cursor cleared, one regrain_cancel log row), then reverses as before.
--
-- Every negative below ("no pgpm trigger on the restored table", "the copies are gone") is paired with a
-- witness that the thing was really there to remove, and rows are asserted by WHICH ids are present.
-- Both write-block fixtures are id-kind on purpose: a time-kind monolith's hi sits at the next grid step
-- past now(), so retention cannot reach it without a clock advance; an id table's horizon is
-- max(control) - retain, which a single frontier row moves. The trigger and the reverse are the same
-- code for every control kind.
create extension if not exists pgtap;

select plan(45);

create schema ur508;

-- ======================================================================================================
-- (A) the block retention is still holding: archiving deferred, no coverage recorded (F10-05)
-- ======================================================================================================
create function ur508.s3_down(p regclass, c name, lo text, hi text) returns pgpm.archive_result
  language plpgsql as $$ begin raise exception 'object store unreachable'; end $$;

create table public.ur508a (id bigint generated by default as identity primary key, payload text);
insert into public.ur508a (payload) select 'a' || g from generate_series(1, 7) g;     -- ids 1..7, monolith [0,1000)
call pgpm.transmute('public.ur508a', 'id', 1000, p_retain => 18000, p_paused => false);
select pgpm.set_archive_fn('public.ur508a', 'ur508.s3_down(regclass,name,text,text)'::regprocedure);
select child_name as mon_a from pgpm.part where parent_table = 'public.ur508a'::regclass and lo = '0' \gset

insert into public.ur508a (id, payload) values (20000, 'frontier');       -- horizon 2000: the monolith is eligible
call pgpm.maintain('public.ur508a');                                       -- block installed; archive raises

select is(
  (select array_agg(action order by id) from pgpm.log
    where parent_table = 'public.ur508a'::regclass and action in ('skip_archive', 'retain_detach', 'retain_drop')),
  array['skip_archive'],
  'LIVENESS: (A) archiving was deferred exactly once and nothing was dropped');
select ok(pgpm._is_write_blocked('public.ur508a', :'mon_a'),
  'LIVENESS: (A) the monolith carries pgpm_write_block');
select is(
  (select tgenabled::text from pg_trigger where tgrelid = format('public.%I', :'mon_a')::regclass and tgname = 'pgpm_write_block'),
  'A', 'LIVENESS: (A) and it is ENABLE ALWAYS, the state that survives DETACH untouched');
select throws_like($$ insert into public.ur508a (id, payload) values (8, 'blocked') $$, '%past its retention boundary%',
  'LIVENESS: (A) before the reverse the block really rejects a write into the monolith');

delete from public.ur508a where id = 20000;                                -- nothing outside the monolith now
select is((select array_agg(id order by id) from public.ur508a), array[1,2,3,4,5,6,7]::bigint[],
  'LIVENESS: (A) exactly ids 1..7 remain, all inside the monolith, so the door is open');

select lives_ok($$ select pgpm.untransmute('public.ur508a') $$, '(A) untransmute goes through');
select is((select relkind::text from pg_class where oid = 'public.ur508a'::regclass), 'r',
  'LIVENESS: (A) the reverse really happened: the table is plain again');
select is(
  (select coalesce(array_agg(tgname::text order by tgname), '{}') from pg_trigger
    where tgrelid = 'public.ur508a'::regclass and not tgisinternal),
  '{}'::text[],
  '(A) the restored table carries no trigger at all: pgpm_write_block went with the reverse');
select lives_ok($$ insert into public.ur508a (id, payload) values (8, 'after') $$,
  '(A) and it accepts an insert');
select lives_ok($$ update public.ur508a set payload = 'a7x' where id = 7 $$,
  '(A) and an update');
select lives_ok($$ delete from public.ur508a where id = 1 $$,
  '(A) and a delete');
select is((select array_agg(id || ':' || payload order by id) from public.ur508a),
  array['2:a2','3:a3','4:a4','5:a5','6:a6','7:a7x','8:after'],
  '(A) exactly the original rows less the deleted one, the update applied, plus the new one');
select is((select count(*)::int from pgpm.config where parent_table::oid = 'public.ur508a'::regclass::oid), 0,
  '(A) no pgpm.config row points at the restored table');

-- ======================================================================================================
-- (B) the block pgpm KEEPS on purpose: coverage recorded, then the frontier regressed (#452, F4-03)
-- ======================================================================================================
-- covers the first chunk it is handed, then can make no progress: coverage exists and never completes
create function ur508.one_chunk(p regclass, c name, lo text, hi text) returns pgpm.archive_result
  language plpgsql as $$
declare r pgpm.archive_result;
begin
  if exists (select 1 from pgpm.archive_ledger where parent_table = p and child_name = c) then
    raise exception 'object store unreachable';
  end if;
  r.covered_hi := (lo::numeric + 1)::text; r.rows_archived := 1; return r;
end $$;

create table public.ur508b (id bigint generated by default as identity primary key, payload text);
insert into public.ur508b (payload) select 'b' || g from generate_series(1, 7) g;
call pgpm.transmute('public.ur508b', 'id', 1000, p_retain => 18000, p_paused => false);
select pgpm.set_archive_fn('public.ur508b', 'ur508.one_chunk(regclass,name,text,text)'::regprocedure);
select child_name as mon_b from pgpm.part where parent_table = 'public.ur508b'::regclass and lo = '0' \gset

insert into public.ur508b (id, payload) values (20000, 'frontier');
call pgpm.maintain('public.ur508b');                                       -- block + first chunk
call pgpm.maintain('public.ur508b');                                       -- strategy raises: skip_archive
select is(
  (select array_agg(child_name || ':' || lo || '-' || hi order by hi) from pgpm.archive_ledger
    where parent_table = 'public.ur508b'::regclass),
  array[:'mon_b' || ':0-1'],
  'LIVENESS: (B) exactly one chunk of coverage is recorded for the monolith, and it is not complete');
delete from public.ur508b where id = 20000;                                -- the frontier regresses to 7
call pgpm.maintain('public.ur508b');
select is(
  (select array_agg(action order by id) from pgpm.log
    where parent_table = 'public.ur508b'::regclass and action = 'skip_write_block_lift'),
  array['skip_write_block_lift'],
  'LIVENESS: (B) retention no longer reaches the monolith and pgpm kept the block on purpose, logged once');
select ok(pgpm._is_write_blocked('public.ur508b', :'mon_b'),
  'LIVENESS: (B) the block is still on the monolith');
select is((select count(*)::int from pgpm.part where parent_table = 'public.ur508b'::regclass and child_name = :'mon_b'), 1,
  'LIVENESS: (B) and the monolith was not dropped (coverage incomplete)');
select throws_like($$ insert into public.ur508b (id, payload) values (8, 'blocked') $$, '%past its retention boundary%',
  'LIVENESS: (B) before the reverse the kept block really rejects a write');
select is((select array_agg(id order by id) from public.ur508b), array[1,2,3,4,5,6,7]::bigint[],
  'LIVENESS: (B) exactly ids 1..7 remain, so the door is open');

select lives_ok($$ select pgpm.untransmute('public.ur508b') $$, '(B) untransmute goes through');
select is((select relkind::text from pg_class where oid = 'public.ur508b'::regclass), 'r',
  'LIVENESS: (B) the table is plain again');
select is(
  (select coalesce(array_agg(tgname::text order by tgname), '{}') from pg_trigger
    where tgrelid = 'public.ur508b'::regclass and not tgisinternal),
  '{}'::text[],
  '(B) the restored table carries no trigger: the coverage-kept block went with the reverse too');
select lives_ok($$ insert into public.ur508b (id, payload) values (8, 'after') $$,
  '(B) and it accepts a write');
select is((select array_agg(id order by id) from public.ur508b), array[1,2,3,4,5,6,7,8]::bigint[],
  '(B) exactly the original seven rows plus the new one');

-- ======================================================================================================
-- (C) an in-flight regrain on the monolith (F4-05)
-- ======================================================================================================
create table public.ur508c (id bigint generated by default as identity primary key, payload text);
insert into public.ur508c (payload) select 'c' || g from generate_series(1, 7) g;
call pgpm.transmute('public.ur508c', 'id', 1000, p_paused => false);
insert into public.ur508c (id, payload) values (20000, 'frontier');       -- freezes the monolith [0,1000)
select 'public.ur508c'::regclass::oid as parent_c \gset
select child_name as mon_c from pgpm.part where parent_table = 'public.ur508c'::regclass and lo = '0' and attached \gset
select is(pgpm.regrain_step('public.ur508c', :'mon_c', '100', 3), 'prepared',
  'LIVENESS: (C) regrain capture is installed on the monolith');
-- #266 may have renamed the source to its transitional name; re-read it
select child_name as mon_c from pgpm.part where parent_table = 'public.ur508c'::regclass and lo = '0' and attached \gset
select is(pgpm.regrain_step('public.ur508c', :'mon_c', '100', 3), 'copied:3',
  'LIVENESS: (C) one microbatch of three rows copied into a fine child: the regrain is in flight, mid-sub-range');
select is(
  (select array_agg(tgname::text order by tgname) from pg_trigger
    where tgrelid = format('public.%I', :'mon_c')::regclass and not tgisinternal),
  array['pgpm_regrain_capture', 'pgpm_regrain_truncate_guard'],
  'LIVENESS: (C) the capture trigger and the TRUNCATE guard sit on the monolith child');
select is((select count(*)::int from pg_proc where proname = 'ur508c_pgpm_regrain_capture'), 1,
  'LIVENESS: (C) the per-parent capture function exists, and the trigger depends on it');
select is((select count(*)::int from pgpm.part where parent_table = 'public.ur508c'::regclass and not attached), 1,
  'LIVENESS: (C) one not-yet-attached fine copy is recorded');
select child_name as copy_c from pgpm.part where parent_table = 'public.ur508c'::regclass and not attached \gset
select isnt(to_regclass(format('public.%I', :'copy_c')), null,
  'LIVENESS: (C) and it is a real standalone relation, which the parent''s DROP would not reach');
select is((select count(*)::int from pgpm.config where parent_table = 'public.ur508c'::regclass and regrain_cursor is not null), 1,
  'LIVENESS: (C) config.regrain_cursor marks the regrain as in flight');

delete from public.ur508c where id = 20000;                                -- nothing outside the monolith
update public.ur508c set payload = 'c7x' where id = 7;                     -- a change the capture trigger sees
select is(pgpm._regrain_delta_count('public.ur508c'), 2::bigint,
  'LIVENESS: (C) the capture trigger is live: the update landed old + new in the delta');
select is((select array_agg(id order by id) from public.ur508c), array[1,2,3,4,5,6,7]::bigint[],
  'LIVENESS: (C) exactly ids 1..7 remain, so the door is open');

select lives_ok($$ select pgpm.untransmute('public.ur508c') $$,
  '(C) untransmute mid-regrain goes through: it does not die on its own capture apparatus');
select is((select relkind::text from pg_class where oid = 'public.ur508c'::regclass), 'r',
  'LIVENESS: (C) the table is plain again');
select is(
  (select coalesce(array_agg(tgname::text order by tgname), '{}') from pg_trigger
    where tgrelid = 'public.ur508c'::regclass and not tgisinternal),
  '{}'::text[],
  '(C) the restored table carries no trigger: capture and TRUNCATE guard both went with the reverse');
select is((select count(*)::int from pg_proc where proname = 'ur508c_pgpm_regrain_capture'), 0,
  '(C) the per-parent capture function is gone');
select is(to_regclass('public.ur508c_pgpm_regrain_delta'), null,
  '(C) and so is the delta table');
select is(to_regclass(format('public.%I', :'copy_c')), null,
  '(C) the abandoned fine copy is gone, not orphaned');
select is((select count(*)::int from pgpm.part where parent_table::oid = :parent_c), 0,
  '(C) no pgpm.part row survives for the dropped parent');
select is(
  (select array_agg(action order by id) from pgpm.log
    where parent_table::oid = :parent_c and action in ('regrain_cancel', 'untransmute')),
  array['regrain_cancel'],
  '(C) the abandonment is on the record as regrain_cancel against the parent, exactly once');
select is(
  (select array_agg(action order by id) from pgpm.log
    where parent_table = 'public.ur508c'::regclass and action = 'untransmute'),
  array['untransmute'],
  '(C) and the reverse itself is logged against the restored table');
select lives_ok($$ insert into public.ur508c (id, payload) values (8, 'after') $$,
  '(C) the restored table accepts a write');
select is((select array_agg(id || ':' || payload order by id) from public.ur508c),
  array['1:c1','2:c2','3:c3','4:c4','5:c5','6:c6','7:c7x','8:after'],
  '(C) exactly the original rows, the mid-regrain update kept, plus the new one');
select lives_ok($$ truncate public.ur508c $$,
  '(C) and TRUNCATE is no longer refused: the in-flight guard is gone with the regrain');

select * from finish();
