-- A resumed transmute reuses the zone its bound was computed in, not the resuming session's (issue #506).
--
-- transmute's phase 1 computes the monolith's bound in the transmuting session's zone (#455) and records it
-- in pgpm.transmute_inflight, so that a re-run after a failure between the phases resumes on the recorded
-- bound rather than recomputing one (#275). The claim did not record the ZONE. A resume from a session in
-- another zone therefore reused the bound (the right instants, on the first session's lattice) and then
-- registered config.partition_tz from its own session: the monolith sat on one lattice and every later
-- grid computation ran on another. obtain's first candidates half-overlapped the monolith and were
-- skipped, a hole one whole step wide was left right past the monolith's hi (writes there failed with
-- "no partition of relation found for row"), and set_partition_tz refused to repair it, because the grid
-- built past the hole was on the wrong lattice for the original zone.
--
-- The claim now carries partition_tz, and a resume takes the zone from the claim along with the bound. A
-- claim recorded before the column existed has null there and the resume keeps the session's zone, which
-- is what it did before.
--
-- The failing first conversion runs in a dblink session pinned to New York (tests/112's instrument: a
-- committing procedure cannot run inside throws_ok, and pg_prove runs this file under ON_ERROR_STOP, so a
-- failing top-level CALL would end it). Its backend's exit is asynchronous once the connection closes, so
-- the claim's owner is cleared before the re-run rather than polled for (tests/101's stand-in for a
-- session that has ended). Every negative below ("every bound is a boundary in the recorded zone", "no
-- hole") is paired with a witness that the two lattices really differ and that the re-run really RESUMED.
-- bench/transmute_resume_zone.sh runs this file against a mutant whose resume ignores the recorded zone
-- (transmute_resume_session_zone), so it is also required to FAIL there.
create extension if not exists pgtap;
create extension if not exists dblink;
select plan(16);

-- phase2_stray(rel, row_sql, call_sql, tz): make call_sql fail in phase 2 on a stray row, deterministically
-- (#668). transmute now reads the table's maximum and refuses or covers a future-dated row before phase 1,
-- so a stray already in the table no longer reaches VALIDATE. One that is committed AFTER that read does:
-- session pw inserts row_sql and holds it uncommitted (its ROW EXCLUSIVE lock blocks phase 1's ADD), session
-- pa starts call_sql, which reads the maximum without seeing the row and then waits on phase 1's ACCESS
-- EXCLUSIVE; once pa is seen waiting, pw commits, the ADD ... NOT VALID proceeds without checking existing
-- rows, and phase 2's VALIDATE finds the row. Returns whether pa was seen waiting when pw committed (the
-- ordering witness: nothing of phase 1 had run yet, so VALIDATE could only come after the commit) and the
-- error pa's CALL ended with. The poll reads pg_locks only, which takes no lock on the table.
create function pg_temp.phase2_stray(p_rel regclass, p_row_sql text, p_call_sql text, p_tz text default 'UTC',
                                     out waited boolean, out err_state text, out err_msg text)
language plpgsql as $f$
declare v_pid int;
begin
  perform dblink_connect('pw', 'dbname=' || current_database());
  perform dblink_exec('pw', 'begin');
  perform dblink_exec('pw', p_row_sql);
  perform dblink_connect('pa', 'dbname=' || current_database());
  perform dblink_exec('pa', format('set timezone = %L', p_tz));
  select pid into v_pid from dblink('pa', 'select pg_backend_pid()') as t(pid int);
  perform dblink_send_query('pa', p_call_sql);
  waited := false;
  err_state := 'none';
  err_msg := 'the CALL did not fail';
  for i in 1 .. 400 loop
    if exists (select 1 from pg_locks where pid = v_pid and relation = p_rel
                  and mode = 'AccessExclusiveLock' and not granted) then
      waited := true;
      exit;
    end if;
    perform pg_sleep(0.01);
  end loop;
  perform dblink_exec('pw', 'commit');
  begin
    perform * from dblink_get_result('pa') as t(r text);
  exception when others then
    err_state := sqlstate;
    err_msg := sqlerrm;
  end;
  perform dblink_disconnect('pa');
  perform dblink_disconnect('pw');
end
$f$;

set timezone = 'UTC';
create table public.rz (id bigint generated by default as identity, ts timestamptz not null default now(),
                        primary key (ts, id));
insert into public.rz (ts) select now() - (g || ' days')::interval from generate_series(1, 20) g;
select isnt((date_trunc('month', now() at time zone 'America/New_York') + interval '1 month') at time zone 'America/New_York',
            (date_trunc('month', now() at time zone 'UTC') + interval '1 month') at time zone 'UTC',
  'LIVENESS: the New York and UTC month boundaries above now() are different instants, so the two lattices genuinely differ');

-- session A, in New York: phase 1 commits the bound and the claim, phase 2 fails on a stray row committed
-- after A read the maximum (phase2_stray), A ends
select * from pg_temp.phase2_stray('public.rz',
  $$insert into public.rz (ts) values (now() + interval '3 months')$$,
  $$call pgpm.transmute('public.rz', 'ts', interval '1 month', p_obtain => 0)$$, 'America/New_York') \gset rz_
select is(:'rz_waited'::boolean, true,
  'LIVENESS: the stray''s writer committed while the New York session waited on phase 1''s lock, before any VALIDATE');
select is(:'rz_err_state' || ': ' || :'rz_err_msg', '23514: check constraint "pgpm_monolith_bound" of relation "rz" is violated by some row',
  'LIVENESS: the New York session''s conversion fails in phase 2, on the stray row');
select is((select count(*)::int from pgpm.transmute_inflight where parent_table = 'public.rz'::regclass), 1,
  'LIVENESS: the claim row is still there');
select hi as claimed_hi from pgpm.transmute_inflight where parent_table = 'public.rz'::regclass \gset
select is(:'claimed_hi'::timestamptz,
  (date_trunc('month', now() at time zone 'America/New_York') + interval '1 month') at time zone 'America/New_York',
  'LIVENESS: the claimed bound is midnight on the 1st in New York');
select ok(exists (select 1 from public.rz where ts >= :'claimed_hi'::timestamptz),
  'LIVENESS: the stray is committed in rz, past the claimed hi (the bound was computed without it)');
select is((select partition_tz from pgpm.transmute_inflight where parent_table = 'public.rz'::regclass), 'America/New_York',
  'the claim records the zone its bound was computed in');

-- the re-run, from THIS session, in UTC
delete from public.rz where ts > now();
update pgpm.transmute_inflight set owner_pid = null, owner_backend_start = null
 where parent_table = 'public.rz'::regclass;
call pgpm.transmute('public.rz', 'ts', interval '1 month', p_obtain => 0);   -- p_obtain 0: every forward child below is obtain's work, from this UTC session
select is((select relkind::text from pg_class where oid = 'public.rz'::regclass), 'p', 'LIVENESS: the re-run completed the conversion');
select is((select count(*)::int from pgpm.log where parent_table = 'public.rz'::regclass and action = 'transmute_resume'), 1,
  'LIVENESS: it RESUMED on the recorded bound rather than starting over');
select is((select partition_tz from pgpm.config where parent_table = 'public.rz'::regclass), 'America/New_York',
  'the table is registered in the zone the bound was computed in, not the resuming session''s UTC');
select is(
  (select string_agg(format('%s: hi %s floors to %s in %s', p.child_name, p.hi,
                            pgpm._grid_floor(c.control_kind, c.partition_step, c.partition_anchor, p.hi, c.partition_tz), c.partition_tz), '; ')
     from pgpm.part p join pgpm.config c on c.parent_table = p.parent_table
    where p.parent_table = 'public.rz'::regclass and p.attached
      and pgpm._grid_floor(c.control_kind, c.partition_step, c.partition_anchor, p.hi, c.partition_tz)::timestamptz <> p.hi::timestamptz),
  null::text, 'every attached bound is a grid boundary in the recorded partition_tz');

-- and the grid maintenance builds, from this UTC session, continues the monolith's lattice
select pgpm.set_obtain('public.rz', 3);
select cmp_ok(pgpm.obtain('public.rz'), '>', 0, 'LIVENESS: obtain built forward partitions under the UTC session');
select is(
  (select string_agg(child_name || ' ends ' || hi || ' but the next starts ' || nlo, '; ' order by lo)
     from (select child_name, lo::timestamptz as lo, hi::timestamptz as hi,
                  lead(lo::timestamptz) over (order by lo::timestamptz) as nlo
             from pgpm.part where parent_table = 'public.rz'::regclass and attached) w
    where nlo is not null and hi <> nlo),
  null::text, 'the forward grid is contiguous with the monolith: no hole past its hi');
select is(
  (select child_name::text from pgpm.part where parent_table = 'public.rz'::regclass and attached
    and lo::timestamptz = :'claimed_hi'::timestamptz),
  'rz_p' || to_char(:'claimed_hi'::timestamptz at time zone 'America/New_York', 'YYYY_MM'),
  'the first forward child starts exactly at the monolith''s hi and is named for its New York month');
insert into public.rz (ts) values (:'claimed_hi'::timestamptz + interval '1 hour');
select is(
  (select c.relname::text from public.rz e join pg_class c on c.oid = e.tableoid where e.ts = :'claimed_hi'::timestamptz + interval '1 hour'),
  'rz_p' || to_char(:'claimed_hi'::timestamptz at time zone 'America/New_York', 'YYYY_MM'),
  'a write an hour past the monolith''s hi lands in that child (it had nowhere to go before)');
select is((select count(*)::int from pgpm.transmute_inflight where parent_table = 'public.rz'::regclass), 0,
  'the completed conversion released the claim');

select * from finish();
