-- _enforce_write_blocks discarded a partition's VALID archive coverage when something else held its
-- name (issue #518).
--
-- The #452 rule is that coverage found on a partition without its write block is discarded: the
-- watermark describes the partition's contents only because the trigger has been on it since the
-- first chunk was recorded, so ledger rows on an unblocked child can only mean the block left by a
-- path pgpm did not guard. _enforce_write_blocks made that test BY NAME, _is_write_blocked(child_name),
-- at the top of its loop body, before the #429 identity check that _install_write_block makes further
-- down. A relation squatting on a partition's name has no trigger, so the tick read "coverage without
-- its block", deleted the pgpm.archive_ledger rows describing the REAL partition (still attached,
-- still write-blocked, unchanged, merely renamed aside) and logged archive_coverage_reset, in the same
-- tick that logged fail_write_block_identity for the same child. No row was lost, but ledger rows
-- naming archived objects were destroyed on the strength of a relation that was not the partition,
-- and archiving started over from lo once the name was sorted out.
--
-- The rule now: the loop resolves each child's name against pgpm.part.child_oid FIRST, with the same
-- predicate as the install (a null anchor compares as nothing; a name resolving to nothing stays on
-- the skip_write_block path), and a name that resolves to a different relation suppresses the reset.
-- The identity refusal is then the whole of what the tick does for that child, which is what the
-- guide promises: every step that would act on the name checks it first.
--
-- PART A is the defect: substitute, tick, and the real partition's ledger row is still there, by
-- identity; then sort the name out and the next tick archives from the WATERMARK, not from lo, which
-- is what keeping the row is for.
-- PART B is the positive counterpart, so the negative in A ("no archive_coverage_reset") cannot be
-- satisfied by a tick that never resets anything: identity intact and the trigger really gone, the
-- reset still fires.
-- PART C is the unanchored case (child_oid null, as on an install upgrading into identity anchoring):
-- nothing to compare is not a mismatch, so the reset proceeds by name exactly as before, and an
-- upgrade never keeps coverage it cannot vouch for.
create extension if not exists pgtap;

select plan(31);

create schema pgpm_test129;

-- Every row the strategy is handed lands here, so a row handed twice (once per archiving pass) shows
-- up as two copies and a row never handed as absent: "resumed from the watermark" versus "started over
-- from lo" is a question about WHICH ids were handed, and how many times, not how many rows. Two ids
-- of range per call, so a partition's first chunk covers [lo, lo+2) and its second [lo+2, lo+4).
create table pgpm_test129.handed (parent regclass, id bigint);
create function pgpm_test129.recorder(p_parent regclass, p_child name, p_lo text, p_hi text)
returns pgpm.archive_result language plpgsql as $$
declare v_hi numeric := least(p_lo::numeric + 2, p_hi::numeric); v_rows bigint; v_result pgpm.archive_result;
begin
  execute format('insert into pgpm_test129.handed (parent, id) select %s::regclass, id from public.%I where id >= %L and id < %L',
                 p_parent::oid, p_child, p_lo, v_hi::text);
  get diagnostics v_rows = row_count;
  v_result.covered_hi := v_hi::text;
  v_result.rows_archived := v_rows;
  return v_result;
end;
$$;

-- ============ PART A: a substituted name does not discard the real partition's coverage ============
-- Monolith [0, 1000) with ids 1..7; the frontier row 20000 with retain 18000 puts the horizon at 2000,
-- so the monolith is eligible: blocked on the first tick and archived one chunk per tick after that.
create table public.cr129a (id bigint generated by default as identity primary key, payload text);
insert into public.cr129a (payload) select 'x' from generate_series(1, 7);
call pgpm.transmute('public.cr129a', 'id', 1000, p_retain => 18000, p_paused => false);
select pgpm.set_archive_fn('public.cr129a', 'pgpm_test129.recorder(regclass,name,text,text)'::regprocedure);
insert into public.cr129a (id, payload) values (20000, 'frontier');

select child_name as a_doomed from pgpm.part where parent_table = 'public.cr129a'::regclass and lo = '0' \gset
select child_name as a_sib from pgpm.part where parent_table = 'public.cr129a'::regclass and lo = '1000' \gset
select format('public.%I', :'a_doomed')::regclass::oid as a_real \gset

call pgpm.maintain('public.cr129a');   -- block, and the first chunk

select is(
  (select child_oid from pgpm.part where parent_table = 'public.cr129a'::regclass and child_name = :'a_doomed'),
  :'a_real'::oid, 'LIVENESS: (A) pgpm.part records WHICH relation the monolith is, by oid');
select ok(exists (select 1 from pg_trigger where tgrelid = :'a_real'::oid and tgname = 'pgpm_write_block'),
  'LIVENESS: (A) the monolith carries its write block');
select results_eq(
  $$ select child_name, lo, hi from pgpm.archive_ledger where parent_table = 'public.cr129a'::regclass $$,
  format($$ values (%L::name, '0'::text, '2'::text) $$, :'a_doomed'),
  'LIVENESS: (A) one chunk of coverage, [0, 2), is recorded for the monolith under its name');
select results_eq(
  $$ select id from pgpm_test129.handed where parent = 'public.cr129a'::regclass order by id $$,
  $$ values (1::bigint) $$,
  'LIVENESS: (A) id 1 is the one row handed so far, so the watermark is real and partial');

-- THE SUBSTITUTION: the real partition moves aside (still attached, still blocked) and a plain table
-- with no trigger on it takes the name.
select format('alter table public.%I rename to cr129a_kept', :'a_doomed') \gexec
select format('create table public.%I (id bigint primary key, payload text)', :'a_doomed') \gexec
select format('public.%I', :'a_doomed')::regclass::oid as a_impostor \gset

select isnt(:'a_impostor'::oid, :'a_real'::oid,
  'LIVENESS: (A) the name now answers to a DIFFERENT relation than pgpm recorded');
select is((select count(*)::int from pg_inherits
            where inhparent = 'public.cr129a'::regclass and inhrelid = :'a_real'::oid),
  1, 'LIVENESS: (A) the relation pgpm meant is still a live partition of the parent, merely renamed');
select ok(exists (select 1 from pg_trigger where tgrelid = :'a_real'::oid and tgname = 'pgpm_write_block'),
  'LIVENESS: (A) and still has the trigger nothing has removed, so its coverage is true');
select ok(not pgpm._is_write_blocked('public.cr129a', :'a_doomed'),
  'LIVENESS: (A) the substitute has no trigger, so a by-name test reads "coverage without its block"');

call pgpm.maintain('public.cr129a');

-- The witness that the tick ran and saw the mismatch: exactly one refusal, naming the monolith's range.
select results_eq(
  $$ select action, lo, hi from pgpm.log
      where parent_table = 'public.cr129a'::regclass and action = 'fail_write_block_identity' $$,
  $$ values ('fail_write_block_identity'::text, '0'::text, '1000'::text) $$,
  'LIVENESS: (A) the tick saw the identity mismatch and refused, once, against the monolith''s range');

-- The witness that the tick's archive step ran and simply passed over the substituted name: with the
-- monolith no longer a candidate (the name it would be found under has no trigger), the one chunk
-- this tick records at archive_batch's default of 1 is the eligible, untouched sibling's first.
select results_eq(
  format($$ select lo, hi from pgpm.archive_ledger where parent_table = 'public.cr129a'::regclass and child_name = %L $$, :'a_sib'),
  $$ values ('1000'::text, '1002'::text) $$,
  'LIVENESS: (A) the archive step ran this tick, recording the sibling''s first chunk, so it did reach the ledger');

-- THE PROPERTY: the real partition's coverage is not discarded on the strength of a relation that is not it.
select results_eq(
  format($$ select child_name, lo, hi from pgpm.archive_ledger where parent_table = 'public.cr129a'::regclass and child_name = %L $$, :'a_doomed'),
  format($$ values (%L::name, '0'::text, '2'::text) $$, :'a_doomed'),
  'the ledger row describing the real partition is still there, unchanged');
select is((select count(*)::int from pgpm.log
            where parent_table = 'public.cr129a'::regclass and action = 'archive_coverage_reset'),
  0, 'and no archive_coverage_reset was logged');
select is((select count(*)::int from pg_trigger where tgrelid = :'a_impostor'::oid and not tgisinternal),
  0, 'the substitute got no trigger: pgpm issued no DDL against a relation it had not identified');
select results_eq(
  $$ select id from public.cr129a_kept order by id $$,
  $$ select generate_series(1, 7)::bigint $$,
  'the real partition still holds exactly ids 1..7');
select ok(exists (select 1 from pg_trigger where tgrelid = :'a_real'::oid and tgname = 'pgpm_write_block'),
  'and still has its block, so the coverage was true throughout');
select results_eq(
  $$ select id from pgpm_test129.handed where parent = 'public.cr129a'::regclass order by id $$,
  $$ values (1::bigint) $$,
  'nothing was archived under the substituted name: the refusal was the whole of what the tick did for it');

-- THE NAME SORTED OUT: the substitute goes and the real partition gets its name back. This is what
-- keeping the row is FOR: the next tick resumes from the watermark instead of re-exporting [0, 2).
select format('drop table public.%I', :'a_doomed') \gexec
select format('alter table public.cr129a_kept rename to %I', :'a_doomed') \gexec
select is(format('public.%I', :'a_doomed')::regclass::oid, :'a_real'::oid,
  'LIVENESS: (A) the name resolves to the recorded relation again');

call pgpm.maintain('public.cr129a');

select results_eq(
  format($$ select lo, hi from pgpm.archive_ledger where parent_table = 'public.cr129a'::regclass and child_name = %L order by lo::numeric $$, :'a_doomed'),
  $$ values ('0'::text, '2'::text), ('2', '4') $$,
  'archiving resumed from the kept watermark: the second chunk is [2, 4), not [0, 2) again');
select results_eq(
  $$ select id from pgpm_test129.handed where parent = 'public.cr129a'::regclass order by id $$,
  $$ values (1::bigint), (2), (3) $$,
  'IDENTITY A: ids 1, 2 and 3 were each handed exactly once: nothing was re-exported');
select is((select count(*)::int from pgpm.log
            where parent_table = 'public.cr129a'::regclass and action = 'archive_coverage_reset'),
  0, 'and still no archive_coverage_reset: the coverage was never in question');

-- ============ PART B: identity intact and the trigger really gone, the reset still fires ============
-- The negative in part A would be satisfied by a tick that never resets anything, so this pins the
-- branch it guards: same setup, the trigger dropped by hand on the monolith ITSELF, name and oid
-- agreeing, and the tick discards the coverage exactly as #452 requires.
create table public.cr129b (id bigint generated by default as identity primary key, payload text);
insert into public.cr129b (payload) select 'x' from generate_series(1, 7);
call pgpm.transmute('public.cr129b', 'id', 1000, p_retain => 18000, p_paused => false);
select pgpm.set_archive_fn('public.cr129b', 'pgpm_test129.recorder(regclass,name,text,text)'::regprocedure);
insert into public.cr129b (id, payload) values (20000, 'frontier');
select child_name as b_doomed from pgpm.part where parent_table = 'public.cr129b'::regclass and lo = '0' \gset

call pgpm.maintain('public.cr129b');

select results_eq(
  $$ select child_name, lo, hi from pgpm.archive_ledger where parent_table = 'public.cr129b'::regclass $$,
  format($$ values (%L::name, '0'::text, '2'::text) $$, :'b_doomed'),
  'LIVENESS: (B) one chunk of coverage is recorded for the monolith');

select format('drop trigger pgpm_write_block on public.%I', :'b_doomed') \gexec

select is(
  (select child_oid from pgpm.part where parent_table = 'public.cr129b'::regclass and child_name = :'b_doomed'),
  format('public.%I', :'b_doomed')::regclass::oid,
  'LIVENESS: (B) the name resolves to the recorded relation: identity is intact');
select ok(not pgpm._is_write_blocked('public.cr129b', :'b_doomed'),
  'LIVENESS: (B) and its block is really gone while the coverage remains');

call pgpm.maintain('public.cr129b');

select results_eq(
  $$ select action, lo, hi, rows from pgpm.log
      where parent_table = 'public.cr129b'::regclass and action = 'archive_coverage_reset' $$,
  $$ values ('archive_coverage_reset'::text, '0'::text, '1000'::text, 1::bigint) $$,
  'coverage found without its block on the partition itself is discarded, and the log says one chunk went');
select is((select count(*)::int from pgpm.log
            where parent_table = 'public.cr129b'::regclass and action = 'fail_write_block_identity'),
  0, 'with nothing to refuse: the name never stopped meaning the partition');
select results_eq(
  $$ select id from pgpm_test129.handed where parent = 'public.cr129b'::regclass order by id $$,
  $$ values (1::bigint), (1) $$,
  'IDENTITY B: id 1 was handed twice, once per pass: the re-blocked partition really did start over from lo');

-- ================= PART C: an unanchored partition (child_oid null) is not a mismatch =================
-- An install upgrading into identity anchoring has pgpm.part rows with no recorded oid. Nothing to
-- compare means nothing to refuse on everywhere else in pgpm, and the reset must read it the same
-- way: a null anchor is not a substitution, so coverage found without its block on such a partition
-- is still discarded. (The tempting `is distinct from` would read null as "different" and keep, for
-- every pre-upgrade partition, coverage nothing vouches for.)
create table public.cr129c (id bigint generated by default as identity primary key, payload text);
insert into public.cr129c (payload) select 'x' from generate_series(1, 7);
call pgpm.transmute('public.cr129c', 'id', 1000, p_retain => 18000, p_paused => false);
select pgpm.set_archive_fn('public.cr129c', 'pgpm_test129.recorder(regclass,name,text,text)'::regprocedure);
insert into public.cr129c (id, payload) values (20000, 'frontier');
select child_name as c_doomed from pgpm.part where parent_table = 'public.cr129c'::regclass and lo = '0' \gset

call pgpm.maintain('public.cr129c');

select results_eq(
  $$ select child_name, lo, hi from pgpm.archive_ledger where parent_table = 'public.cr129c'::regclass $$,
  format($$ values (%L::name, '0'::text, '2'::text) $$, :'c_doomed'),
  'LIVENESS: (C) one chunk of coverage is recorded for the monolith');

update pgpm.part set child_oid = null where parent_table = 'public.cr129c'::regclass and child_name = :'c_doomed';
select format('drop trigger pgpm_write_block on public.%I', :'c_doomed') \gexec

select is(
  (select child_oid from pgpm.part where parent_table = 'public.cr129c'::regclass and child_name = :'c_doomed'),
  null::oid, 'LIVENESS: (C) the monolith has no recorded oid, as on an install upgrading into identity anchoring');
select ok(not pgpm._is_write_blocked('public.cr129c', :'c_doomed'),
  'LIVENESS: (C) and its block is really gone while the coverage remains');

call pgpm.maintain('public.cr129c');

select results_eq(
  $$ select action, lo, hi, rows from pgpm.log
      where parent_table = 'public.cr129c'::regclass and action = 'archive_coverage_reset' $$,
  $$ values ('archive_coverage_reset'::text, '0'::text, '1000'::text, 1::bigint) $$,
  'the unanchored partition''s coverage without its block is discarded exactly as an anchored one''s');
select is((select count(*)::int from pgpm.log
            where parent_table = 'public.cr129c'::regclass and action = 'fail_write_block_identity'),
  0, 'and no identity refusal was logged: a null anchor is not a mismatch');

select * from finish();
