-- pgpm.set_archive_fn checks what the strategy RETURNS, not only what it takes (issue #517).
--
-- The archive_fn contract is `(p_parent regclass, p_child name, p_lo text, p_hi text) returns
-- pgpm.archive_result`. set_archive_fn takes a regprocedure, and the cast to regprocedure resolves
-- the name and the ARGUMENT types: a reference with the wrong argument list fails right there, as
-- 42883 (tests/66). It says nothing about the return type, and before this fix nothing else did, so
-- a strategy declared `returns text` was installed without complaint, against the reference's
-- promise that assignment validates "exactly this signature".
--
-- What that cost. _run_archive_strategy calls the strategy as `select * from fn(...)` and reads the
-- result INTO a pgpm.archive_result variable, positionally. A one-column text result lands in the
-- first field, covered_hi, and the other three stay null. A strategy that echoes p_hi therefore
-- returns a covered_hi that is exactly the chunk's hi: it passes the contract check (#454) as a
-- perfect answer, a ledger row is written with rows_archived null, coverage is complete, and the
-- next retain() drops the partition with nothing archived. Not a Tier 1 on its own only because the
-- operator had to install a strategy of the wrong type first; the point of the check is that this
-- is the one moment pgpm can tell, and it said nothing.
--
-- The fix: set_archive_fn refuses a function whose prorettype is not pgpm.archive_result, or that
-- returns SETOF it, naming the function, what it does return and the contract, and leaves
-- config.archive_fn exactly as it was. The negative assertions below ("refused", "unchanged", "never
-- called") are each paired with a witness that the conditions for the defect were present: the cast
-- alone accepts the mis-typed function, a well-typed twin with the same argument list is accepted,
-- and the tick that follows really did do the archive work, through the well-typed strategy.
create extension if not exists pgtap;

select plan(20);

create schema pgpm_test129;

-- What each strategy was actually asked, so "the mis-typed strategy was never called" can be checked
-- against "the well-typed one was, for this exact chunk", rather than against nothing.
create table pgpm_test129.calls (strategy text, p_child name, p_lo text, p_hi text);

-- The issue's strategy: the contract's argument list, `returns text`, echoing p_hi. Pre-fix this was
-- accepted, and at tick time its one column became covered_hi = p_hi.
create function pgpm_test129.echo_hi(p_parent regclass, p_child name, p_lo text, p_hi text)
returns text language plpgsql as $$
begin
  insert into pgpm_test129.calls values ('echo_hi', p_child, p_lo, p_hi);
  return p_hi;
end $$;

-- The contract's argument list and its row type, but SETOF: not the signature either.
create function pgpm_test129.as_setof(p_parent regclass, p_child name, p_lo text, p_hi text)
returns setof pgpm.archive_result language plpgsql as $$
begin
  insert into pgpm_test129.calls values ('as_setof', p_child, p_lo, p_hi);
  return next row(p_hi, 0::bigint, null, null)::pgpm.archive_result;
end $$;

-- The well-typed twin: same argument list, returns pgpm.archive_result, and archives (counts) the
-- rows it is handed, so a drop that follows it is a drop after a real archive.
create function pgpm_test129.well_typed(p_parent regclass, p_child name, p_lo text, p_hi text)
returns pgpm.archive_result language plpgsql as $$
declare v pgpm.archive_result; v_rows bigint;
begin
  insert into pgpm_test129.calls values ('well_typed', p_child, p_lo, p_hi);
  execute format('select count(*) from public.%I where id >= %s and id < %s', p_child, p_lo, p_hi) into v_rows;
  v.covered_hi := p_hi;
  v.rows_archived := v_rows;
  return v;
end $$;

-- Monolith [0, 1000) holding 7 rows; retain 18000 so that the frontier row at 20000 inserted below
-- puts the horizon at exactly 2000 and the monolith is the only eligible partition.
create table public.af129 (id bigint generated by default as identity primary key, payload text);
insert into public.af129 (payload) select 'x' from generate_series(1, 7);                     -- ids 1..7
call pgpm.transmute('public.af129', 'id', 1000, p_retain => 18000, p_paused => false);        -- monolith [0,1000)

select child_name as af_child from pgpm.part
  where parent_table = 'public.af129'::regclass and lo = '0' \gset

select is((select archive_fn from pgpm.config where parent_table = 'public.af129'::regclass),
  null::regprocedure, 'fixture: archive_fn is null (strategy none) on the freshly transmuted table');

-- ============================ the witnesses ============================
-- Both mis-typed candidates get past the regprocedure cast on their own: the cast is not the check.
select is(('pgpm_test129.echo_hi(regclass,name,text,text)'::regprocedure)::text,
  'pgpm_test129.echo_hi(regclass,name,text,text)',
  'LIVENESS: the text-returning strategy has the contract''s argument list, so the regprocedure cast alone accepts it');
select is((select prorettype::regtype::text from pg_proc where oid = 'pgpm_test129.echo_hi(regclass,name,text,text)'::regprocedure),
  'text', 'LIVENESS: and it returns text, not pgpm.archive_result');
select is((select proretset from pg_proc where oid = 'pgpm_test129.as_setof(regclass,name,text,text)'::regprocedure),
  true, 'LIVENESS: the setof strategy returns SETOF pgpm.archive_result');

-- A well-typed function with the very same argument list is accepted, so a refusal below is about
-- the return type and nothing else.
select lives_ok(
  $$ select pgpm.set_archive_fn('public.af129', 'pgpm_test129.well_typed(regclass,name,text,text)'::regprocedure) $$,
  'LIVENESS: a strategy with the same arguments that returns pgpm.archive_result is accepted');
select is((select archive_fn from pgpm.config where parent_table = 'public.af129'::regclass),
  'pgpm_test129.well_typed(regclass,name,text,text)'::regprocedure,
  'LIVENESS: config.archive_fn now names the well-typed strategy');

-- ============================ the property ============================
-- Ordered so the issue's own strategy is the LAST assignment before the tick: pre-fix, every one of
-- these was accepted, and the tick below then ran echo_hi, which is the consequence the section
-- after this one asserts against.

-- A dangling reference never reaches the catalog: an oid that names no function is refused before
-- the update, not stored for a tick to trip over.
select throws_like(
  $$ select pgpm.set_archive_fn('public.af129', 4294967295::oid::regprocedure) $$,
  '%4294967295%does not name a function%',
  'set_archive_fn refuses an oid that names no function');
select is((select archive_fn from pgpm.config where parent_table = 'public.af129'::regclass),
  'pgpm_test129.well_typed(regclass,name,text,text)'::regprocedure,
  'config.archive_fn is unchanged by the dangling reference: still the well-typed strategy');

select throws_like(
  $$ select pgpm.set_archive_fn('public.af129', 'pgpm_test129.as_setof(regclass,name,text,text)'::regprocedure) $$,
  '%pgpm_test129.as_setof(regclass,name,text,text)%returns setof pgpm.archive_result%',
  'set_archive_fn refuses a strategy that returns SETOF pgpm.archive_result: the contract is one row');
select is((select archive_fn from pgpm.config where parent_table = 'public.af129'::regclass),
  'pgpm_test129.well_typed(regclass,name,text,text)'::regprocedure,
  'config.archive_fn is unchanged by that refusal too');

select throws_like(
  $$ select pgpm.set_archive_fn('public.af129', 'pgpm_test129.echo_hi(regclass,name,text,text)'::regprocedure) $$,
  '%pgpm_test129.echo_hi(regclass,name,text,text)%returns text%returns pgpm.archive_result%',
  'set_archive_fn refuses a strategy that returns text, naming the function, what it returns and the contract');
select is((select archive_fn from pgpm.config where parent_table = 'public.af129'::regclass),
  'pgpm_test129.well_typed(regclass,name,text,text)'::regprocedure,
  'config.archive_fn is unchanged by the refusal: still the well-typed strategy');

-- ============================ the consequence, on this tree ============================
-- Pre-fix the last set_archive_fn above installed echo_hi, this tick handed it [0, 1000), its
-- echoed p_hi went in as covered_hi with rows_archived null, and retain() dropped the monolith with
-- nothing archived. Post-fix the tick runs the well-typed strategy, which is the witness that the
-- archive step did its work at all, and the drop that follows is backed by a real archive of 7 rows.
insert into public.af129 (id, payload) values (20000, 'frontier');                             -- horizon 2000

call pgpm.maintain('public.af129');

select results_eq(
  $$ select strategy, p_child, p_lo, p_hi from pgpm_test129.calls $$,
  format($$ values ('well_typed'::text, %L::name, '0'::text, '1000'::text) $$, :'af_child'),
  'LIVENESS: the tick called exactly one strategy, the well-typed one, for the monolith''s chunk [0, 1000)');
select is((select count(*)::int from pgpm_test129.calls where strategy in ('echo_hi', 'as_setof')), 0,
  'neither mis-typed strategy was ever invoked');
select results_eq(
  $$ select lo, hi, child_name, rows_archived from pgpm.archive_ledger where parent_table = 'public.af129'::regclass $$,
  format($$ values ('0'::text, '1000'::text, %L::name, 7::bigint) $$, :'af_child'),
  'the one ledger row records the well-typed strategy''s 7 archived rows, not a positional echo with rows_archived null');
select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.af129'::regclass and action = 'retain_drop' and lo = '0'
      and exists (select 1 from pgpm.archive_ledger l
                   where l.parent_table = 'public.af129'::regclass and l.lo = '0' and l.rows_archived is null)),
  0, 'no partition was dropped on the strength of a ledger row a mis-typed strategy produced');
select results_eq(
  $$ select lo, hi from pgpm.log where parent_table = 'public.af129'::regclass and action = 'retain_drop' $$,
  $$ values ('0'::text, '1000'::text) $$,
  'LIVENESS: the monolith was dropped this tick, after the real archive, so the tick reached retention');
select results_eq(
  $$ select id from public.af129 order by id $$,
  $$ values (20000::bigint) $$,
  'the 7 archived rows went with the partition and the frontier row is untouched');

-- ============================ the switch still turns off ============================
select lives_ok($$ select pgpm.set_archive_fn('public.af129') $$,
  'set_archive_fn with no strategy still clears archive_fn: null is not a mis-typed function');
select is((select archive_fn from pgpm.config where parent_table = 'public.af129'::regclass),
  null::regprocedure, 'archive_fn is null again');

select * from finish();
