-- retire() trusted archive coverage recorded while a write block it did not see was absent (issue #564).
--
-- The #452 rule is that coverage found on a partition WITHOUT its write block is discarded: the ledger
-- watermark describes the partition's contents only because the trigger has been on it since the first
-- chunk was recorded, so ledger rows on an unblocked child can only mean the block left by a path pgpm
-- did not guard (an operator dropped the trigger by hand; a pgpm older than #452 lifted it before an
-- upgrade). _enforce_write_blocks applied that rule. retire() did not, and retire() is documented as
-- independently callable: "only maintain() is guaranteed to have run _enforce_write_blocks first". So a
-- direct caller reached a fully archived child whose block had gone, retire() re-installed the block
-- itself, read the stale watermark as full coverage, and DROPPED the child with a row written while it
-- was unblocked that no strategy was ever handed.
--
-- The rule now: retire() applies the same discard before it installs the block. Coverage found without
-- the block is deleted and logged as archive_coverage_reset (rows = how many chunks), the block goes
-- back on, and _archive_fully_covered then reads false, so retire() returns false with the partition
-- untouched. Archiving starts over from lo under the block, and a later retire() drops it only once
-- every row in it, the unguarded write included, has been handed to the strategy.
--
-- PART A is the defect, asserted by identity: WHICH ledger rows go (the monolith's two, not the
-- sibling's), WHICH row survives (500), and afterwards WHICH ids the strategy is handed (1, 2, 3 twice,
-- once per pass, and 500 once) before the drop is allowed.
-- PART B is the positive counterpart, so "retire() did not drop" in A cannot be satisfied by a retire()
-- that has stopped dropping anything: a covered child whose block never left is dropped, and no second
-- reset is logged for it.
-- PART C pins that the discard is about coverage, not merely an absent block: an unblocked child with no
-- ledger rows is blocked by retire() as before and logs no reset at all.
create extension if not exists pgtap;

select plan(29);

create schema pgpm_test130;

-- Every row the strategy is handed lands here, so a row handed twice (once per archiving pass) shows up
-- as two copies and a row never handed as absent. At most 600 ids of range per call, so the monolith
-- [0, 1000) takes two chunks, [0, 600) and [600, 1000), and the ledger count the reset reports is 2.
create table pgpm_test130.handed (parent regclass, id bigint);
create function pgpm_test130.recorder(p_parent regclass, p_child name, p_lo text, p_hi text)
returns pgpm.archive_result language plpgsql as $$
declare v_hi numeric := least(p_lo::numeric + 600, p_hi::numeric); v_rows bigint; v_result pgpm.archive_result;
begin
  execute format('insert into pgpm_test130.handed (parent, id) select %s::regclass, id from public.%I where id >= %L and id < %L',
                 p_parent::oid, p_child, p_lo, v_hi::text);
  get diagnostics v_rows = row_count;
  v_result.covered_hi := v_hi::text;
  v_result.rows_archived := v_rows;
  return v_result;
end;
$$;

-- ============ PART A: coverage recorded before an unguarded write does not license the drop ============
-- Monolith [0, 1000) with ids 1, 2, 3; sibling [1000, 2000) with id 1500; the frontier row 20000 with
-- retain 18000 puts the horizon at 2000, so both are eligible.
create table public.rs130a (id bigint generated by default as identity primary key, payload text);
insert into public.rs130a (payload) select 'x' from generate_series(1, 3);
call pgpm.transmute('public.rs130a', 'id', 1000, p_retain => 18000, p_paused => false);
select pgpm.set_archive_fn('public.rs130a', 'pgpm_test130.recorder(regclass,name,text,text)'::regprocedure);
insert into public.rs130a (id, payload) values (1500, 'sibling'), (20000, 'frontier');

select child_name as a_mono from pgpm.part where parent_table = 'public.rs130a'::regclass and lo = '0' \gset
select child_name as a_sib from pgpm.part where parent_table = 'public.rs130a'::regclass and lo = '1000' \gset

-- a normal tick's worth, repeated until both are covered: block, then archive
select pgpm._enforce_write_blocks('public.rs130a');
do $$ begin for i in 1..6 loop perform pgpm._archive_step('public.rs130a'); end loop; end $$;

select ok(pgpm._archive_fully_covered('public.rs130a', :'a_mono') and pgpm._archive_fully_covered('public.rs130a', :'a_sib'),
  'LIVENESS A: the monolith and the sibling are both fully archive-covered');
select results_eq(
  $$ select child_name, lo, hi from pgpm.archive_ledger where parent_table = 'public.rs130a'::regclass order by child_name, lo::numeric $$,
  format($$ values (%1$L::name, '0'::text, '600'::text), (%1$L::name, '600', '1000'), (%2$L::name, '1000', '1600'), (%2$L::name, '1600', '2000') $$,
         :'a_mono', :'a_sib'),
  'LIVENESS A: the monolith is covered by two chunks and the sibling by two, under their own names');
select results_eq(
  $$ select id from pgpm_test130.handed where parent = 'public.rs130a'::regclass order by id $$,
  $$ values (1::bigint), (2::bigint), (3::bigint), (1500::bigint) $$,
  'LIVENESS A: ids 1, 2, 3 and 1500 were each handed to the strategy exactly once');

-- the block leaves by a path pgpm did not guard (the hand edit #452 names), and a row lands
select format('drop trigger pgpm_write_block on public.%I', :'a_mono') as a_dropsql \gset
:a_dropsql;
insert into public.rs130a (id, payload) values (500, 'written while unblocked');

select ok(not pgpm._is_write_blocked('public.rs130a', :'a_mono'), 'LIVENESS A: the monolith''s write block is gone');
select ok(pgpm._is_write_blocked('public.rs130a', :'a_sib'), 'LIVENESS A: the sibling''s write block is still on');
select results_eq(format($$ select id from public.%I order by id $$, :'a_mono'),
  $$ values (1::bigint), (2::bigint), (3::bigint), (500::bigint) $$,
  'LIVENESS A: row 500 landed in the monolith, beside 1, 2, 3');
select ok(pgpm._archive_fully_covered('public.rs130a', :'a_mono'),
  'LIVENESS A: the stale watermark still reads as full coverage of the monolith, so the old retire() would drop it');

-- an external retirement actor calls the sanctioned single-partition drop directly
select is(pgpm.retire('public.rs130a', :'a_mono'), false,
  'retire() does not drop a partition whose coverage was recorded before its write block went missing');
select isnt(to_regclass(format('public.%I', :'a_mono')), null, 'the monolith relation still exists');
select ok(exists (select 1 from pgpm.part where parent_table = 'public.rs130a'::regclass and child_name = :'a_mono'),
  'the monolith is still catalogued in pgpm.part');
select results_eq($$ select id from public.rs130a where id = 500 $$, $$ values (500::bigint) $$,
  'row 500 is still live');
select results_eq(
  $$ select child_name, lo, hi from pgpm.archive_ledger where parent_table = 'public.rs130a'::regclass order by child_name, lo::numeric $$,
  format($$ values (%1$L::name, '1000'::text, '1600'::text), (%1$L::name, '1600', '2000') $$, :'a_sib'),
  'the monolith''s two stale chunks are discarded and the sibling''s two are untouched');
select results_eq(
  $$ select action, lo, hi, rows from pgpm.log where parent_table = 'public.rs130a'::regclass and action = 'archive_coverage_reset' $$,
  $$ values ('archive_coverage_reset'::text, '0'::text, '1000'::text, 2::bigint) $$,
  'the discard is logged once, as archive_coverage_reset for [0, 1000), counting its two chunks');
select ok(pgpm._is_write_blocked('public.rs130a', :'a_mono'), 'retire() put the monolith''s write block back on');
select ok(case when exists (select 1 from pgpm.part where parent_table = 'public.rs130a'::regclass and child_name = :'a_mono')
                then not pgpm._archive_fully_covered('public.rs130a', :'a_mono') else false end,
  'the monolith now reads as not covered');

-- ============ PART B: a covered child whose block never left is still dropped ============
select is(pgpm.retire('public.rs130a', :'a_sib'), true, 'retire() drops the sibling, whose coverage was guarded throughout');
select is(to_regclass(format('public.%I', :'a_sib')), null, 'the sibling relation is gone');
select is((select count(*)::int from pgpm.log where parent_table = 'public.rs130a'::regclass and action = 'archive_coverage_reset'), 1,
  'no reset is logged for the sibling: the one reset row is still the monolith''s');

-- ============ PART A, continued: archiving starts over from lo, and the drop waits for it ============
do $$ begin for i in 1..4 loop perform pgpm._archive_step('public.rs130a'); end loop; end $$;

select results_eq(
  $$ select child_name, lo, hi from pgpm.archive_ledger where parent_table = 'public.rs130a'::regclass and child_name = (select child_name from pgpm.part where parent_table = 'public.rs130a'::regclass and lo = '0') order by lo::numeric $$,
  format($$ values (%1$L::name, '0'::text, '600'::text), (%1$L::name, '600', '1000') $$, :'a_mono'),
  'archiving the monolith restarted from lo 0 under the restored block');
select results_eq(
  $$ select id, count(*)::int from pgpm_test130.handed where parent = 'public.rs130a'::regclass group by id order by id $$,
  $$ values (1::bigint, 2), (2::bigint, 2), (3::bigint, 2), (500::bigint, 1), (1500::bigint, 1) $$,
  'the second pass handed 1, 2, 3 again and 500 for the first time');
select is(pgpm.retire('public.rs130a', :'a_mono'), true, 'retire() drops the monolith once its coverage was recorded under the block');
select is(to_regclass(format('public.%I', :'a_mono')), null, 'the monolith relation is gone');
select results_eq($$ select id from public.rs130a order by id $$, $$ values (20000::bigint) $$,
  'only the frontier row is left live');
select results_eq(
  $$ select id from public.rs130a union select id from pgpm_test130.handed where parent = 'public.rs130a'::regclass order by id $$,
  $$ values (1::bigint), (2::bigint), (3::bigint), (500::bigint), (1500::bigint), (20000::bigint) $$,
  'every row ever written is still live or was handed to the strategy, 500 included');

-- ============ PART C: an unblocked child with no coverage logs no reset ============
create table public.rs130c (id bigint generated by default as identity primary key, payload text);
insert into public.rs130c (payload) select 'x' from generate_series(1, 2);
call pgpm.transmute('public.rs130c', 'id', 1000, p_retain => 19000, p_paused => false);
select pgpm.set_archive_fn('public.rs130c', 'pgpm_test130.recorder(regclass,name,text,text)'::regprocedure);
insert into public.rs130c (id, payload) values (20000, 'frontier');
select child_name as c_mono from pgpm.part where parent_table = 'public.rs130c'::regclass and lo = '0' \gset

select ok(not pgpm._is_write_blocked('public.rs130c', :'c_mono'), 'LIVENESS C: the child has never been write-blocked');
select ok(not exists (select 1 from pgpm.archive_ledger where parent_table = 'public.rs130c'::regclass),
  'LIVENESS C: and no coverage is recorded for it');
select is(pgpm.retire('public.rs130c', :'c_mono'), false, 'retire() does not drop the uncovered child');
select ok(pgpm._is_write_blocked('public.rs130c', :'c_mono'), 'retire() write-blocked it, as it always has');
select ok(not exists (select 1 from pgpm.log where parent_table = 'public.rs130c'::regclass and action = 'archive_coverage_reset'),
  'no archive_coverage_reset is logged when there was no coverage to discard');

select * from finish();
