-- Issue #590: a lock race while maintain() looks for its auto-regrain candidate defers the regrain step
-- alone; it does not raise out of maintain() and abandon the rest of maintain_all's sweep.
--
-- THE DEFECT. maintain() found the auto-regrain candidate BEFORE the regrain step's exception handler.
-- The search computes the grid floor from pgpm._frontier_native(parent), which reads the parent under
-- the tick's 200 ms lock_timeout, so while another session held a lock on a parent with regrain_to set
-- the 55P03 raised straight out of maintain(). maintain_all() has no handler around the call, by design
-- (one would disable every COMMIT inside maintain()), so the sweep stopped there: every parent ordered
-- after it got no write-block, archive or retain that tick, nor any tick for as long as the lock lasted.
-- docs/reference.md promises the opposite: "one step failing does not abandon the rest of the tick; a
-- step that loses a lock race is deferred and retried next tick".
--
-- THE FIX moves the candidate search inside the regrain step's handler, so a lock race there is the
-- regrain step's deferral (a skip_regrain row, regrain=deferred), exactly like one inside regrain_step.
--
-- Fixture. X is transmuted first (lower oid, so maintain_all visits it first), has auto-regrain on and a
-- frozen coarse monolith (its frontier moved far past it), so the candidate search is a real search with
-- a real answer. Y is transmuted second and has exactly one partition past its retention horizon,
-- [0,1000), holding five rows, and a live one holding the frontier row: asymmetric, so "Y was maintained"
-- is shown by WHICH partition went and which stayed, not by a count.
--
-- Every negative ("X did not stop the sweep") is paired with its liveness witness: another session
-- really held ACCESS EXCLUSIVE on X for the whole sweep, the sweep really visited X first, X's candidate
-- search really lost the lock race (the skip_regrain row carries 55P03's text), and once the lock is gone
-- the same tick on X really does regrain.
create extension if not exists pgtap;
create extension if not exists dblink;
set client_min_messages = warning;
select plan(11);

-- X: auto-regrain on; 299 rows on ids 10..2990, so at step 1000 the monolith is the coarse [0,3000),
-- frozen by one row at 20000
create table public.rcx (id bigint primary key, payload text);
insert into public.rcx select g * 10, 'x' from generate_series(1, 299) g;
call pgpm.transmute('public.rcx', 'id', 1000, p_paused => false);
insert into public.rcx (id, payload) values (20000, 'frontier');
select pgpm.set_regrain('public.rcx', '1000');

-- Y: [0,1000) holds rows 1..5 and is past retention once the frontier is at 20000
create table public.rcy (id bigint generated by default as identity primary key, payload text);
insert into public.rcy (payload) select 'y' from generate_series(1, 5);
call pgpm.transmute('public.rcy', 'id', 1000, p_retain => 19000, p_paused => false);
insert into public.rcy (id, payload) values (20000, 'frontier');
select child_name as ychild from pgpm.part where parent_table = 'public.rcy'::regclass and lo = '0' \gset
select child_name as ylive from pgpm.part
 where parent_table = 'public.rcy'::regclass and attached and lo::bigint <= 20000 and hi::bigint > 20000 \gset

select ok('public.rcx'::regclass::oid < 'public.rcy'::regclass::oid,
  'LIVENESS: maintain_all visits X before Y');
select is((select pgpm._retain_boundary(c) from pgpm.config c where parent_table = 'public.rcy'::regclass), '1000',
  'LIVENESS: Y''s partition [0,1000) is past its retention horizon, so a Y tick drops it');
select ok(exists (select 1 from pgpm.part where parent_table = 'public.rcx'::regclass and attached
                    and lo::bigint = 0 and hi::bigint = 3000),
  'LIVENESS: X has a frozen coarse child, so its candidate search has something to find');

delete from pgpm.log;

-- a second session holds ACCESS EXCLUSIVE on X (a long ALTER, a migration, an explicit LOCK)
select dblink_connect('rcl', 'dbname=' || current_database());
select dblink_exec('rcl', 'begin');
select dblink_exec('rcl', 'lock table public.rcx in access exclusive mode');
select ok(exists (select 1 from pg_locks where relation = 'public.rcx'::regclass and mode = 'AccessExclusiveLock'
                   and granted and pid <> pg_backend_pid()),
  'LIVENESS: another session holds ACCESS EXCLUSIVE on X');

\set ON_ERROR_STOP 0
call pgpm.maintain_all();
\set ON_ERROR_STOP 1

select ok(exists (select 1 from pg_locks where relation = 'public.rcx'::regclass and mode = 'AccessExclusiveLock'
                   and granted and pid <> pg_backend_pid()),
  'LIVENESS: and still held it when the sweep returned');
select dblink_exec('rcl', 'rollback');
select dblink_disconnect('rcl');

-- the lock race on X deferred X's regrain step, by name and with the lock timeout as its reason
select is((select string_agg(method, ' | ') from pgpm.log
            where parent_table = 'public.rcx'::regclass and action = 'skip_regrain'),
  'canceling statement due to lock timeout',
  'X''s candidate search lost the lock race and was logged as the regrain step''s deferral');

-- and the sweep went on to Y: its aged partition, and only that one, was retired
select is((select string_agg(lo, ',' order by id) from pgpm.log
            where parent_table = 'public.rcy'::regclass and action = 'retain_drop'),
  '0',
  'the sweep reached Y and retired [0,1000) (a lock race on X defers X''s step only)');
select ok(to_regclass('public.' || quote_ident(:'ychild')) is null, 'Y''s aged partition is gone');
select is((select string_agg(t.id || '->' || c.relname, ' ' order by t.id)
             from public.rcy t join pg_class c on c.oid = t.tableoid),
  '20000->' || :'ylive',
  'and Y''s live partition, with its frontier row, is untouched');

-- with the lock gone the same step does its work: the deferral was a deferral, not a no-op
delete from pgpm.log;
call pgpm.maintain('public.rcx', null) \gset
select is(:'p_status'::text, 'archived=0 dropped=0 restored_fk=0 regrain=prepared',
  'LIVENESS: once the lock is released, X''s tick finds the candidate and starts its regrain');
select is((select string_agg(action || ':' || method, ' | ' order by id) from pgpm.log
            where parent_table = 'public.rcx'::regclass),
  'regrain_prepare:' || (select child_name from pgpm.part where parent_table = 'public.rcx'::regclass and lo = '0'),
  'on the monolith, and logs no deferral');

select * from finish();
