-- Issue #591: extend_to builds every partition it needs in ONE transaction (it is a function), and each
-- CREATE TABLE ... PARTITION OF holds its locks to that transaction's end. Its p_max (default 10000) was
-- the only bound, so on a stock server (max_locks_per_transaction = 64) a call a few thousand cells out
-- passed its own dry count and then died with 53200 `out of shared memory` after ~2100 partitions, having
-- filled the SHARED lock table every other backend needs on the way. The contract: a call whose partitions
-- would hold more than half the nominal lock table, max_locks_per_transaction x (max_connections +
-- max_prepared_transactions), refuses in pgpm's own words and creates nothing; a call inside that budget
-- still extends exactly as before.
create extension if not exists pgtap;
set client_min_messages = warning;

select plan(9);

-- the budget, computed from THIS server's settings rather than assumed stock
create temporary table lb_budget as
  select (current_setting('max_locks_per_transaction')::int
          * (current_setting('max_connections')::int + current_setting('max_prepared_transactions')::int)) / 2
         as slots;

create table public.lb (id bigint generated by default as identity primary key, payload text);
insert into public.lb (payload) select 'x' from generate_series(1, 10);
call pgpm.transmute('public.lb', 'id', 10, p_paused => false);

create temporary table lb_edge as
  select max(hi::numeric) as hi from pgpm.part where parent_table = 'public.lb'::regclass;

-- ==================== (A) within the budget, extend_to extends, and each partition costs a slot ====
-- One transaction (a DO block is one), so the locks this call takes are still held when they are counted.
-- Fast-path locks are excluded: they live in the backend's own PGPROC, not in the shared table.
create temporary table lb_small (made int, slots_taken int);
do $$
declare v_before int; v_made int;
begin
  select count(*) into v_before from pg_locks where pid = pg_backend_pid() and not fastpath;
  v_made := pgpm.extend_to('public.lb', ((select hi from lb_edge) + 25)::text);
  insert into lb_small
    select v_made, count(*)::int - v_before from pg_locks where pid = pg_backend_pid() and not fastpath;
end $$;

select is((select made from lb_small), 3,
  'an in-budget call still extends: exactly the three cells from the forward edge through edge + 25');
select is(
  (select array_agg(lo::numeric order by lo::numeric) from pgpm.part
    where parent_table = 'public.lb'::regclass and lo::numeric >= (select hi from lb_edge)),
  (select array_agg(g order by g) from generate_series((select hi from lb_edge), (select hi from lb_edge) + 20, 10) g),
  'and they are the right cells, by their lower bounds');
select cmp_ok((select slots_taken from lb_small), '>=', 3,
  'LIVENESS: every partition extend_to creates takes at least one shared lock-table slot, held to transaction end');

-- ==================== (B) past the budget, under the default p_max, it refuses in its own words ====
-- budget + 1 cells: at one slot apiece (witnessed above) they cannot fit, whatever each really costs.
create temporary table lb_far as
  select (select hi from lb_edge) + 30 + ((select slots from lb_budget) + 1) * 10 as v;
create temporary table lb_before as
  select child_name, lo, hi, child_oid from pgpm.part where parent_table = 'public.lb'::regclass;
create temporary table lb_log_before as
  select count(*)::int as n from pgpm.log where parent_table = 'public.lb'::regclass and action = 'obtain';

select cmp_ok(((select v from lb_far) - (select hi from lb_edge) - 30) / 10, '<', 10000::numeric,
  'LIVENESS: reaching the far value needs fewer new partitions than extend_to''s default p_max of 10000');

select throws_like(
  format($$ select pgpm.extend_to('public.lb', %L) $$, (select v from lb_far)::text),
  'pg_partition_magician: extend_to(%lb, %) would hold about % lock-table slots%more than half%',
  'a call whose partitions cannot fit in half the lock table is refused by pgpm, not by 53200');

select is(
  (select array_agg(row(child_name, lo, hi, child_oid)::text order by child_name) from pgpm.part
    where parent_table = 'public.lb'::regclass),
  (select array_agg(row(child_name, lo, hi, child_oid)::text order by child_name) from lb_before),
  'the refused call left pgpm.part exactly as it was: the same partitions, by name, bounds and oid');
select is(
  (select array_agg(c.relname::text order by c.relname) from pg_inherits i join pg_class c on c.oid = i.inhrelid
    where i.inhparent = 'public.lb'::regclass),
  (select array_agg(child_name::text order by child_name) from lb_before),
  'and the catalog agrees: the parent''s children are exactly the recorded ones');
select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.lb'::regclass and action = 'obtain'),
  (select n from lb_log_before),
  'and it logged no partition creation');

-- ==================== (C) the explicit p_max refusal still comes first ============================
select throws_like(
  format($$ select pgpm.extend_to('public.lb', %L, 5) $$, (select v from lb_far)::text),
  'pg_partition_magician: extend_to(%lb, %) would need more than 5 new partitions%',
  'p_max still refuses up front when it is the tighter bound');

select * from finish();
