-- Issue #656: transmute and untransmute reseed an identity sequence from values read under the lock that
-- stops writers, not from values read before it.
--
-- Both used to read max(identity) and the sequence's position with nothing on the table that excludes a
-- writer: transmute in its preflight, before phase 1 (phase 2's VALIDATE blocks nobody), untransmute before
-- its explicit ACCESS EXCLUSIVE (#443's second gate). Ids handed out after that read were handed out AGAIN
-- by the reseeded sequence, so the first inserts after the conversion or the reversal failed with a
-- duplicate key, one failed insert per re-issued id. Both now take those values under the ACCESS EXCLUSIVE
-- their cutover already holds, after which no writer can hand out another.
--
-- The concurrent writer is a dblink connection, the way tests/109 drives #443's race. It takes ROW SHARE
-- first, so the conversion (or the reversal) queues for ACCESS EXCLUSIVE behind it; this session sees that
-- wait in pg_locks, and only THEN does the writer insert, so its ids are by construction issued after the
-- old read point. It commits, and the call under test completes.
--
-- WHILE THE CALL UNDER TEST WAITS, THIS SESSION MUST NOT TOUCH ITS TABLE: a new ACCESS SHARE queues behind
-- the pending ACCESS EXCLUSIVE, and the writer that would release it is this session's to commit.
--
-- Asymmetric: the writer adds sequence-issued ids AND one explicit id well past them (the identity is BY
-- DEFAULT), so the right reseed (the greater of the max + 1 and the sequence's own next value, both read
-- under the lock) is neither the sequence's next value alone nor the pre-lock one. Transmute's writer adds
-- three ids and 40, untransmute's two ids and 60, so neither half's expected value can stand in for the
-- other's.
create extension if not exists pgtap;
create extension if not exists dblink;

select plan(17);

-- An insert that reports the id it got, or the error it met, instead of aborting the file.
create function public.id157_next(p_rel regclass) returns text language plpgsql as $$
declare v bigint;
begin
  execute format('insert into %s (body) values (''after'') returning id', p_rel) into v;
  return v::text;
exception when unique_violation then
  return sqlerrm;
end $$;

-- ============================ (A) transmute ============================
create table public.id157 (id bigint generated by default as identity primary key, body text);
insert into public.id157 (body) select 'pre ' || g from generate_series(1, 5) g;   -- ids 1..5

select dblink_connect('b157', 'dbname=' || current_database());
select dblink_exec('b157', $$set application_name = 'id157_writer'$$);
select dblink_exec('b157', 'begin');
select dblink_exec('b157', 'lock table public.id157 in row share mode');

select dblink_connect('t157', 'dbname=' || current_database());
select dblink_exec('t157', $$set application_name = 'id157_transmute'$$);
select dblink_send_query('t157',
  $$call pgpm.transmute('public.id157', 'id', 100::bigint, p_obtain => 2, p_lock_timeout => '60s')$$);

-- Poll for the WAIT (phase 1's ADD CONSTRAINT), bounded at 30 s so a broken fixture fails, not hangs.
-- pg_stat_activity is read once per transaction and then frozen (the documented snapshot; a DO block is
-- one transaction), so the loop clears it each turn (#713). It happened to work without that: pg_locks is
-- live, and the backend it joins was in the first snapshot with its application_name already set.
do $$
begin
  for i in 1 .. 600 loop
    perform pg_stat_clear_snapshot();
    exit when exists (select 1 from pg_locks l join pg_stat_activity a on a.pid = l.pid
                       where a.application_name = 'id157_transmute' and l.locktype = 'relation'
                         and l.relation = 'public.id157'::regclass
                         and l.mode = 'AccessExclusiveLock' and not l.granted);
    perform pg_sleep(0.05);
  end loop;
end $$;
select is(
  (select count(*)::int from pg_locks l join pg_stat_activity a on a.pid = l.pid
    where a.application_name = 'id157_transmute' and l.locktype = 'relation'
      and l.relation = 'public.id157'::regclass and l.mode = 'AccessExclusiveLock' and not l.granted),
  1, 'LIVENESS: transmute is past its preflight, queued for ACCESS EXCLUSIVE behind the writer');

-- The writer already holds a lock the queued request conflicts with, so its inserts go ahead of it.
select dblink_exec('b157', $$insert into public.id157 (body) values ('during 1'), ('during 2'), ('during 3')$$);
select dblink_exec('b157', $$insert into public.id157 (id, body) values (40, 'during explicit')$$);
select is(
  (select count(*)::int from pg_locks l join pg_stat_activity a on a.pid = l.pid
    where a.application_name = 'id157_transmute' and l.locktype = 'relation'
      and l.relation = 'public.id157'::regclass and l.mode = 'AccessExclusiveLock' and not l.granted),
  1, 'LIVENESS: and still queued after the writer''s inserts, so they came after the preflight');
select dblink_exec('b157', 'commit');
select is((select r from dblink_get_result('t157') as t(r text)), 'CALL',
  'transmute completed once the writer committed');
select dblink_disconnect('t157');
select dblink_disconnect('b157');

select is((select relkind::text from pg_class where oid = 'public.id157'::regclass), 'p',
  'LIVENESS: id157 was converted');
select is((select string_agg(id::text, ',' order by id) from public.id157), '1,2,3,4,5,6,7,8,40',
  'LIVENESS: the writer''s ids 6, 7, 8 and 40 are in the table beside 1..5');
select is(
  (select string_agg(distinct c.relname::text, ',') from public.id157 t join pg_class c on c.oid = t.tableoid
    where t.id in (6, 7, 8, 40)),
  (select child_name::text from pgpm.part where parent_table = 'public.id157'::regclass order by lo::bigint limit 1),
  'LIVENESS: in the monolith, the partition the reseed has to steer clear of');
select is(public.id157_next('public.id157'), '41',
  'the first insert after the conversion gets 41: past the explicit 40 AND past the sequence-issued 8');
select is(public.id157_next('public.id157'), '42', 'and the next one 42');
select is((select attidentity::text from pg_attribute where attrelid = 'public.id157'::regclass and attname = 'id'),
  'd', 'the identity is still BY DEFAULT on the parent');

-- ============================ (B) untransmute ============================
create table public.iu157 (id bigint generated by default as identity primary key, body text);
insert into public.iu157 (body) select 'pre ' || g from generate_series(1, 5) g;   -- ids 1..5
call pgpm.transmute('public.iu157', 'id', 100::bigint, p_obtain => 2);          -- monolith [0, 100)

select dblink_connect('w157', 'dbname=' || current_database());
select dblink_exec('w157', $$set application_name = 'iu157_writer'$$);
select dblink_exec('w157', 'begin');
select dblink_exec('w157', 'lock table public.iu157 in row share mode');

select dblink_connect('u157', 'dbname=' || current_database());
select dblink_exec('u157', $$set application_name = 'iu157_untransmute'$$);
select dblink_exec('u157', $$set lock_timeout = '60s'$$);
select dblink_send_query('u157', $$select pgpm.untransmute('public.iu157')::text$$);

-- The same poll as (A)'s, snapshot cleared each turn for the same reason.
do $$
begin
  for i in 1 .. 600 loop
    perform pg_stat_clear_snapshot();
    exit when exists (select 1 from pg_locks l join pg_stat_activity a on a.pid = l.pid
                       where a.application_name = 'iu157_untransmute' and l.locktype = 'relation'
                         and l.relation = 'public.iu157'::regclass
                         and l.mode = 'AccessExclusiveLock' and not l.granted);
    perform pg_sleep(0.05);
  end loop;
end $$;
select is(
  (select count(*)::int from pg_locks l join pg_stat_activity a on a.pid = l.pid
    where a.application_name = 'iu157_untransmute' and l.locktype = 'relation'
      and l.relation = 'public.iu157'::regclass and l.mode = 'AccessExclusiveLock' and not l.granted),
  1, 'LIVENESS: untransmute passed its first gate and is queued for ACCESS EXCLUSIVE behind the writer');

select dblink_exec('w157', $$insert into public.iu157 (body) values ('during 1'), ('during 2')$$);
select dblink_exec('w157', $$insert into public.iu157 (id, body) values (60, 'during explicit')$$);
select is(
  (select count(*)::int from pg_locks l join pg_stat_activity a on a.pid = l.pid
    where a.application_name = 'iu157_untransmute' and l.locktype = 'relation'
      and l.relation = 'public.iu157'::regclass and l.mode = 'AccessExclusiveLock' and not l.granted),
  1, 'LIVENESS: and still queued after the writer''s inserts');
select dblink_exec('w157', 'commit');
select is((select r from dblink_get_result('u157') as t(r text)), 'iu157',
  'untransmute completed once the writer committed');
select dblink_disconnect('u157');
select dblink_disconnect('w157');

select is((select relkind::text from pg_class where oid = 'public.iu157'::regclass), 'r',
  'LIVENESS: iu157 is a plain table again');
select is((select string_agg(id::text, ',' order by id) from public.iu157), '1,2,3,4,5,6,7,60',
  'LIVENESS: the writer''s ids 6, 7 and 60 are in the restored table beside 1..5');
select is(public.id157_next('public.iu157'), '61',
  'the first insert after the reversal gets 61: past the explicit 60 AND past the sequence-issued 7');
select is(public.id157_next('public.iu157'), '62', 'and the next one 62');
select is((select attidentity::text from pg_attribute where attrelid = 'public.iu157'::regclass and attname = 'id'),
  'd', 'the identity comes back BY DEFAULT');

select * from finish();
