-- Covered-case PK reuse: partitioning a table on its own bigint id primary key must NOT
-- drop and rebuild that primary key. The existing index already includes the partition key,
-- so transmute reuses it in place (the one-time "setup" cost center collapses to zero). See
-- REDESIGN.md ("reuse the existing PK when the partition key already covers it").
create extension if not exists pgtap;

select plan(6);

create table public.reuse_pk (id bigint generated by default as identity primary key, payload text);
insert into public.reuse_pk (payload) select 'p' || g from generate_series(1, 500) g;
-- Identity, not cardinality (#997): distinct payloads, snapshotted before the transmute.
create temporary table _reuse_pk_before as select id, payload from public.reuse_pk;

-- the identity of the PK index BEFORE transmute; reuse means this same index object survives
create temporary table _pk_before as
  select i.indexrelid::oid as idx_oid
    from pg_index i where i.indrelid = 'public.reuse_pk'::regclass and i.indisprimary;

call pgpm.transmute('public.reuse_pk', 'id', 100000);

select is(
  (select relkind::text from pg_class where oid = 'public.reuse_pk'::regclass),
  'p', 'reuse_pk became a partitioned table');

select is(
  (select count(*)::int from pg_constraint where conrelid = 'public.reuse_pk'::regclass and contype = 'p'),
  1, 'parent has a primary key');

select is(
  (select count(*)::int from pg_index where indexrelid = (select idx_oid from _pk_before)),
  1, 'the original PK index object survives (reused in place on the monolith, never rebuilt)');


select throws_ok(
  $$ insert into public.reuse_pk (id, payload) values (1, 'dup') $$,
  '23505', NULL, 'duplicate id rejected (PK enforced through the cutover)');

select is(
  (select count(*)::int from public.reuse_pk), 500, 'all rows conserved');

select bag_eq(
  'select id, payload from public.reuse_pk',
  'select id, payload from _reuse_pk_before',
  'every row survives the transmute by identity: the same (id, payload) rows, none lost, none added, none altered');

select * from finish();
