-- Issue #662: the sweeps' bookkeeping writes to pgpm.config must not be able to abort or hang a sweep.
--
-- THE DEFECT. maintain_all stamps config.sweep_turn_at (#579) for each parent, once before the sweep's
-- first parent starts and once after every parent's maintain() returns; maintain_obtain writes
-- config.obtain_retry_after, clearing an expired back-off after a successful obtain and arming one in its
-- deferral handler. All four were plain UPDATEs of the parent's pgpm.config row, outside any handler, so
-- while another transaction held that row (an operator's open `begin; select pgpm.set_obtain(...)`, a
-- synchronous regrain() advancing regrain_cursor) the stamp either raised 55P03 out of the sweep (under the
-- 3 s lock_timeout maintain leaves behind, or obtain's 200 ms) or, for the first parent's pre-stamp, which
-- runs with no lock_timeout at all, waited for as long as the holder stayed open. Neither sweep has a
-- handler around its loop, by design, so every parent behind the held one went unmaintained, or was
-- denied obtain, for as long as the row was held.
--
-- THE CONTRACT. A held config row costs that parent's bookkeeping write and nothing else: the write is
-- skipped (pgpm._config_try_lock takes the row with SKIP LOCKED), the parent's own work still runs, and
-- every parent behind it in the sweep is reached. Skipping is safe for each of the four: a turn that is
-- not stamped leads the next sweep, a back-off that is not cleared has expired or been bypassed already,
-- and a back-off that is not armed means obtain retries on the next tick, which is the direction that
-- protects the grid.
--
-- The holder and the sweeper are both real second backends (dblink): the holder so the row is held by
-- someone other than the sweep, the sweeper so the sweep runs as a top-level CALL (it commits) and a
-- failure is returned as a value here rather than ending this file. The sweeper runs under a 6 s
-- statement_timeout, so the unguarded first-parent stamp, which would wait on the holder forever, ends as
-- an error instead of hanging the suite.
create extension if not exists pgtap;
create extension if not exists dblink;
set client_min_messages = warning;
select plan(31);

create schema s167;
-- Is p's config row held by another transaction? Asked with NOWAIT in a statement of its own, so this
-- probe never holds the row past its own call and cannot starve the sweep it is observing.
create function s167.held(p regclass) returns boolean language plpgsql as $$
begin
  perform 1 from pgpm.config where parent_table = p for no key update nowait;
  return false;
exception when lock_not_available then
  return true;
end $$;

select dblink_connect('h167', 'dbname=' || current_database());
select dblink_connect('sw167', 'dbname=' || current_database());
select dblink_exec('sw167', 'set statement_timeout = ''6s''');

-- ---------------------------------------------------------------------------------------------------
-- Part A: maintain_all's sweep_turn_at stamps (F4-04)
-- ---------------------------------------------------------------------------------------------------
-- X, A and B in that (oid) order, each with an aged [0,1000) under retain 19000 and a frontier at 20000.
-- Asymmetric row counts, so a partition's rows cannot be mistaken for another's.
create table public.st_x (id bigint generated by default as identity primary key, payload text);
create table public.st_a (id bigint generated by default as identity primary key, payload text);
create table public.st_b (id bigint generated by default as identity primary key, payload text);
insert into public.st_x (payload) select 'x' from generate_series(1, 4);
insert into public.st_a (payload) select 'a' from generate_series(1, 3);
insert into public.st_b (payload) select 'b' from generate_series(1, 2);
call pgpm.transmute('public.st_x', 'id', 1000, p_retain => 19000, p_paused => false);
call pgpm.transmute('public.st_a', 'id', 1000, p_retain => 19000, p_paused => false);
call pgpm.transmute('public.st_b', 'id', 1000, p_retain => 19000, p_paused => false);
insert into public.st_x (id, payload) values (20000, 'frontier');
insert into public.st_a (id, payload) values (20000, 'frontier');
insert into public.st_b (id, payload) values (20000, 'frontier');
select child_name as xold from pgpm.part where parent_table = 'public.st_x'::regclass and lo = '0' \gset
select child_name as aold from pgpm.part where parent_table = 'public.st_a'::regclass and lo = '0' \gset
select child_name as bold from pgpm.part where parent_table = 'public.st_b'::regclass and lo = '0' \gset
select child_name as bnext from pgpm.part where parent_table = 'public.st_b'::regclass and lo = '1000' \gset

select ok('public.st_x'::regclass::oid < 'public.st_a'::regclass::oid
          and 'public.st_a'::regclass::oid < 'public.st_b'::regclass::oid,
  'LIVENESS: the sweep visits X, then A, then B (all new to it, so oid order)');
select ok(to_regclass('public.' || quote_ident(:'bold')) is not null
          and to_regclass('public.' || quote_ident(:'aold')) is not null,
  'LIVENESS: A''s and B''s aged partitions [0,1000) exist before the sweep');

-- A second session holds A's config row: an operator's transaction around a setter, left open.
select dblink_exec('h167', 'begin');
select r from dblink('h167', 'select pgpm.set_obtain(''public.st_a'', 30)::text') as t(r text);
select ok(s167.held('public.st_a'), 'LIVENESS: another session holds A''s config row when the sweep starts');
select ok(not s167.held('public.st_b'), 'LIVENESS: and only A''s: B''s row is free');

-- Sweep 1: A's stamp comes after its maintain(), under the lock_timeout maintain leaves behind.
select is(dblink_exec('sw167', 'call pgpm.maintain_all()', false), 'CALL',
  'sweep 1 completes although A''s config row is held');
select ok(to_regclass('public.' || quote_ident(:'bold')) is null,
  'B, behind the held A, retired its aged partition [0,1000)');
select ok(to_regclass('public.' || quote_ident(:'xold')) is null
          and to_regclass('public.' || quote_ident(:'aold')) is null,
  'and X and A retired theirs: A''s own maintain() ran, only its stamp was at stake');
select is((select array_agg(parent_table::text order by parent_table) from pgpm.config
            where parent_table in ('public.st_x'::regclass, 'public.st_a'::regclass, 'public.st_b'::regclass)
              and sweep_turn_at is null),
  array['st_a'],
  'A''s turn, and only A''s, went unstamped: the held row cost its bookkeeping and nothing else');
select ok(s167.held('public.st_a'), 'LIVENESS: the holder was still open when sweep 1 returned');

-- Sweep 2: A leads, so its turn is the one stamped BEFORE maintain(), in a transaction with no
-- lock_timeout at all. Every other parent has had its turn, which makes the lead deterministic.
update pgpm.config set sweep_turn_at = clock_timestamp() where parent_table <> 'public.st_a'::regclass;
select now() as before2 \gset
insert into public.st_b (id, payload) values (21000, 'frontier 2');   -- B's [1000,2000) ages
select is((select array_agg(parent_table::text) from pgpm.config where sweep_turn_at is null),
  array['st_a'], 'LIVENESS: A is the only parent without a turn, so it leads sweep 2');
select ok(to_regclass('public.' || quote_ident(:'bnext')) is not null,
  'LIVENESS: B''s [1000,2000) exists before sweep 2');

select is(dblink_exec('sw167', 'call pgpm.maintain_all()', false), 'CALL',
  'sweep 2 completes although the parent it leads with has its config row held');
select ok(to_regclass('public.' || quote_ident(:'bnext')) is null,
  'B, behind the held A again, retired [1000,2000) in sweep 2');
select ok((select sweep_turn_at > :'before2'::timestamptz from pgpm.config
            where parent_table = 'public.st_b'::regclass)
          and (select sweep_turn_at > :'before2'::timestamptz from pgpm.config
            where parent_table = 'public.st_x'::regclass),
  'and B and X had their turns stamped by sweep 2');
select ok((select sweep_turn_at is null from pgpm.config where parent_table = 'public.st_a'::regclass),
  'A''s turn is still unstamped: both of its stamps were skipped');
select ok(s167.held('public.st_a'), 'LIVENESS: the holder was still open when sweep 2 returned');

-- The holder lets go. The stamp is skipped only while the row is held: this is the witness that
-- nothing above passed because the stamp simply never runs.
select dblink_exec('h167', 'rollback');
select ok(not s167.held('public.st_a'), 'LIVENESS: A''s config row is free again');
select is(dblink_exec('sw167', 'call pgpm.maintain_all()', false), 'CALL', 'sweep 3 completes');
select ok((select sweep_turn_at is not null from pgpm.config where parent_table = 'public.st_a'::regclass),
  'with A''s row free, sweep 3 stamps A''s turn');

-- ---------------------------------------------------------------------------------------------------
-- Part B: maintain_obtain's obtain_retry_after writes (F4-05)
-- ---------------------------------------------------------------------------------------------------
-- OA: a back-off that has expired, so obtain runs and then CLEARS it (the clearing UPDATE).
-- OD: a longer lookahead to build, with its parent locked by the holder too, so obtain loses the lock
--     race and the deferral handler ARMS a back-off (the handler's UPDATE).
-- OB: a longer lookahead to build and nothing held: the parent behind both.
create table public.ob_a (id bigint generated by default as identity primary key, payload text);
create table public.ob_d (id bigint generated by default as identity primary key, payload text);
create table public.ob_b (id bigint generated by default as identity primary key, payload text);
insert into public.ob_a (payload) select 'a' from generate_series(1, 3);
insert into public.ob_d (payload) select 'd' from generate_series(1, 4);
insert into public.ob_b (payload) select 'b' from generate_series(1, 2);
call pgpm.transmute('public.ob_a', 'id', 1000, p_paused => false);
call pgpm.transmute('public.ob_d', 'id', 1000, p_paused => false);
call pgpm.transmute('public.ob_b', 'id', 1000, p_paused => false);
update pgpm.config set obtain_retry_after = now() - interval '30 seconds'
 where parent_table = 'public.ob_a'::regclass;
select obtain_retry_after as oa_retry from pgpm.config where parent_table = 'public.ob_a'::regclass \gset
select pgpm.set_obtain('public.ob_d', 40);
select pgpm.set_obtain('public.ob_b', 40);
select coalesce(max(id), 0) as log0 from pgpm.log \gset

select ok('public.ob_a'::regclass::oid < 'public.ob_d'::regclass::oid
          and 'public.ob_d'::regclass::oid < 'public.ob_b'::regclass::oid,
  'LIVENESS: the obtain sweep visits OA, then OD, then OB');
select ok((select max(hi::numeric) < 41000 from pgpm.part where parent_table = 'public.ob_b'::regclass and attached)
          and (select max(hi::numeric) < 41000 from pgpm.part where parent_table = 'public.ob_d'::regclass and attached),
  'LIVENESS: OB''s and OD''s grids are short of the 40-step lookahead obtain would build (top 41000)');

select dblink_exec('h167', 'begin');
select r from dblink('h167', 'select pgpm.set_obtain(''public.ob_a'', 30)::text') as t(r text);
select r from dblink('h167', 'select pgpm.set_obtain(''public.ob_d'', 30)::text') as t(r text);
select n from dblink('h167', 'select count(*) from public.ob_d') as t(n bigint);   -- ACCESS SHARE: obtain(OD) must wait
select ok(s167.held('public.ob_a') and s167.held('public.ob_d') and not s167.held('public.ob_b'),
  'LIVENESS: another session holds OA''s and OD''s config rows, and not OB''s');

select is(dblink_exec('sw167', 'call pgpm.maintain_obtain_all()', false), 'CALL',
  'the obtain sweep completes although OA''s and OD''s config rows are held');
select ok(exists (select 1 from pgpm.part where parent_table = 'public.ob_b'::regclass
                   and attached and lo = '40000' and hi = '41000'),
  'OB, behind both, got its lookahead built out to [40000, 41000)');
select is((select array_agg(parent_table::text order by id) from pgpm.log
            where id > :log0 and action = 'skip_obtain'),
  array['ob_d'],
  'LIVENESS: OD lost its lock race and went through the deferral handler, and only OD did');
select ok((select obtain_retry_after is null from pgpm.config where parent_table = 'public.ob_d'::regclass),
  'OD''s back-off was not armed while its row was held: obtain retries it on the next tick');
select is((select obtain_retry_after from pgpm.config where parent_table = 'public.ob_a'::regclass),
  :'oa_retry'::timestamptz,
  'OA''s expired back-off was left as it was while its row was held');
select ok(s167.held('public.ob_a'), 'LIVENESS: the holder was still open when the obtain sweep returned');

select dblink_exec('h167', 'rollback');
select is(dblink_exec('sw167', 'call pgpm.maintain_obtain_all()', false), 'CALL',
  'with the rows free, the next obtain sweep completes');
select ok((select obtain_retry_after is null from pgpm.config where parent_table = 'public.ob_a'::regclass),
  'and clears OA''s expired back-off: the write is skipped only while the row is held');
select ok(exists (select 1 from pgpm.part where parent_table = 'public.ob_d'::regclass
                   and attached and lo = '40000' and hi = '41000'),
  'and builds OD''s lookahead out to [40000, 41000), the retry the unarmed back-off allowed');

select dblink_disconnect('sw167');
select dblink_disconnect('h167');
select * from finish();
