-- An id retain of NaN is refused like a negative one (issue #649).
--
-- #451 refused a retain that puts the horizon past the partition taking writes, and for control_kind id the
-- rule was `p_retain::numeric >= 0`. numeric has a NaN, and PostgreSQL orders it ABOVE every number, so
-- 'NaN' >= 0 is true and the value was accepted as non-negative. The horizon computed from it is
-- frontier - NaN = NaN, which _grid_floor keeps as NaN, and every partition's hi sorts below NaN: every
-- partition is drop-eligible at once, the one taking writes included. One maintenance tick against a
-- config.retain written by hand to 'NaN' write-blocked and dropped the whole table with every row. The API
-- routes happened to refuse it (transmute's id p_retain is bigint; set_retain's would-drop guard fires), so
-- the route is the hand edit #451's defence in _retain_boundary exists for, and that defence let it through.
--
-- One function (_retain_nonnegative) is the rule for every site, so each inherits the fix; pinned here:
--   (A) the rule itself, with a witness that NaN passes the old comparison and would not be refused by it;
--   (B) set_retain refuses NaN with the sign-rule message (pre-fix a different guard refused it, by accident);
--   (C) a config.retain written by hand to NaN: the tick logs skip_write_block / skip_retain (exact actions)
--       and keeps every partition by name and every row by identity; status() stays alive and reports
--       retain_backlog null; set_retain can repair it; and a positive control on the same table with a sane
--       retain drops exactly the two aged partitions (2 dropped, 2 kept: the effects cannot cancel);
--   (D) regrain_step, which computes its own copy of the horizon, refuses NaN rather than discarding every
--       sub-range as aged.
-- (C) and (D) are where pre-fix code shows the data loss.
create extension if not exists pgtap;
select plan(35);

-- ======================= (A) the rule =======================
-- LIVENESS: NaN is "non-negative" under the pre-fix comparison, and it sorts above any frontier there is,
-- so a green refusal below is the new rule doing it, not the old one.
select ok('NaN'::numeric >= 0 and 'NaN'::numeric > 1e300, 'LIVENESS: numeric NaN passes >= 0 and sorts above every number');
select ok(not pgpm._retain_nonnegative('id', v), format('id retain %L is refused', v))
  from unnest(array['NaN', 'nan', '  NaN  ']) v;
-- still refused, still accepted: the rule is otherwise unchanged
select ok(not pgpm._retain_nonnegative('id', '-1'), 'id retain -1 is still refused');
select ok(pgpm._retain_nonnegative('id', v), format('id retain %s is still accepted', v))
  from unnest(array['0', '1500', '1e9']) v;

-- ======================= fixture: an id table with work for retention to do =======================
-- step 1000, obtain 3: [0, 1000) with ids 1..7, [1000, 2000) with 3 rows, [2000, 3000) empty, [3000, 4000)
-- holding the frontier row 3500. Under the legitimate retain of 1500 the horizon is floor(2000) = 2000 and
-- exactly the first two are aged.
create table public.rn168 (id bigint generated by default as identity primary key, payload text);
insert into public.rn168 (payload) select 'x' || g from generate_series(1, 7) g;
call pgpm.transmute('public.rn168', 'id', 1000, p_retain => 1500, p_paused => false, p_obtain => 3);
insert into public.rn168 (id, payload) select g, 'y' || g from generate_series(1001, 1003) g;
insert into public.rn168 (id, payload) values (3500, 'frontier');

create table pg_temp.before168 as
  select lo, child_name from pgpm.part where parent_table = 'public.rn168'::regclass and attached;
select is((select array_agg(lo order by lo::numeric) from pg_temp.before168), array['0', '1000', '2000', '3000'],
  'setup: four attached partitions, two of them below the legitimate horizon');
select child_name as w_live from pgpm.part
  where parent_table = 'public.rn168'::regclass and attached and lo = '3000' \gset

-- ======================= (B) set_retain refuses NaN =======================
select throws_like(
  $$ select pgpm.set_retain('public.rn168', 'NaN') $$,
  '%p_retain cannot be negative (got NaN)%', 'set_retain refuses NaN with the sign-rule message');
select is((select retain from pgpm.config where parent_table = 'public.rn168'::regclass), '1500',
  'the refused call left config.retain untouched');

-- ======================= (C) defence in depth: a config.retain written by hand =======================
update pgpm.config set retain = 'NaN' where parent_table = 'public.rn168'::regclass;   -- THE HAND EDIT
select is((select retain from pgpm.config where parent_table = 'public.rn168'::regclass), 'NaN',
  'LIVENESS: config.retain holds NaN');

select throws_like(
  $$ select pgpm._retain_boundary(c) from pgpm.config c where c.parent_table = 'public.rn168'::regclass $$,
  '%config.retain NaN on %rn168 is negative%', '_retain_boundary refuses to compute a horizon from it');

call pgpm.maintain('public.rn168') \gset
select ok(:'p_status' like 'archived=0 dropped=0%write_block_deferred%retain_deferred%',
  'the tick deferred both the write-block and the retain step: ' || :'p_status');
select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.rn168'::regclass and action = 'skip_write_block' and method like '%NaN%is negative%'),
  1, 'skip_write_block was logged once, carrying the refusal');
select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.rn168'::regclass and action = 'skip_retain' and method like '%NaN%is negative%'),
  1, 'skip_retain was logged once, carrying the refusal');
select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.rn168'::regclass and action = 'retain_drop'),
  0, 'nothing was dropped');
select is(
  (select array_agg(child_name order by lo::numeric) from pgpm.part
    where parent_table = 'public.rn168'::regclass and attached),
  (select array_agg(child_name order by lo::numeric) from pg_temp.before168),
  'every partition attached before the tick is attached after it, by name');
select ok(to_regclass(format('public.%I', :'w_live')) is not null, 'the partition taking writes still exists');
select is((select array_agg(id order by id) from public.rn168),
  array[1, 2, 3, 4, 5, 6, 7, 1001, 1002, 1003, 3500]::bigint[],
  'every row is still there, the aged ones and the frontier row included');
select lives_ok($$ insert into public.rn168 (id, payload) values (3501, 'still live') $$,
  'the table is live: a write at the frontier is accepted');

-- status() is the diagnostic, so it must not be the thing that dies
select is((select retain from pgpm.status() where parent = 'public.rn168'::regclass), 'NaN',
  'status() shows the offending value');
select is((select retain_backlog from pgpm.status() where parent = 'public.rn168'::regclass), null::bigint,
  'status().retain_backlog is null for it');

-- the repair path is open: set_retain compares the NaN as null rather than being blocked by it
select lives_ok($$ select pgpm.set_retain('public.rn168', '500000') $$,
  'set_retain repairs a hand-edited NaN retain');
select is((select retain from pgpm.config where parent_table = 'public.rn168'::regclass), '500000',
  'config.retain was repaired');

-- POSITIVE CONTROL: the same table and tick with a sane value drops exactly the two aged partitions.
update pgpm.config set retain = '1500' where parent_table = 'public.rn168'::regclass;
call pgpm.maintain('public.rn168') \gset
select ok(:'p_status' like 'archived=0 dropped=2%' and :'p_status' not like '%deferred%',
  'with retain 1500 the tick drops the two aged partitions and defers nothing: ' || :'p_status');
select is(
  (select array_agg(lo order by lo::numeric) from pgpm.log
    where parent_table = 'public.rn168'::regclass and action = 'retain_drop'),
  array['0', '1000'], 'retain_drop was logged for exactly [0, 1000) and [1000, 2000)');
select is(
  (select array_agg(child_name order by lo::numeric) from pgpm.part
    where parent_table = 'public.rn168'::regclass and attached),
  (select array_agg(child_name order by lo::numeric) from pg_temp.before168 where lo::numeric >= 2000),
  'exactly the partitions at or above the horizon remain attached, by name');
select is((select array_agg(id order by id) from public.rn168), array[3500, 3501]::bigint[],
  'exactly the frontier rows survive');

-- ======================= (D) regrain_step has its own copy of the horizon =======================
create table public.rn168r (id bigint generated by default as identity primary key, payload text);
insert into public.rn168r (payload) select 'x' from generate_series(1, 50000);   -- ids 1..50000
call pgpm.transmute('public.rn168r', 'id', 10000, p_retain => 30000);   -- monolith [0, 60000)
select pgpm.obtain('public.rn168r');
insert into public.rn168r (id, payload) values (65000, 'frontier');     -- the monolith is frozen
select child_name as r_mono from pgpm.part where parent_table = 'public.rn168r'::regclass and lo = '0' \gset

update pgpm.config set retain = 'NaN' where parent_table = 'public.rn168r'::regclass;   -- THE HAND EDIT

select is(pgpm.regrain_step('public.rn168r', :'r_mono'), 'prepared',
  'setup: the first regrain_step call installs change capture, before the horizon is computed');
select throws_like(
  format($$ select pgpm.regrain_step('public.rn168r', %L) $$, :'r_mono'),
  '%config.retain NaN on %rn168r is negative%', 'regrain_step refuses to compute a horizon from NaN');
select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.rn168r'::regclass and action in ('regrain_aged', 'regrain_copy')),
  0, 'no sub-range was marked aged and none was copied');
select ok(
  (select attached from pgpm.part where parent_table = 'public.rn168r'::regclass and child_name = :'r_mono'),
  'the monolith is still attached');

-- POSITIVE CONTROL: the same regrain with a sane retain copies the 3 within-horizon sub-ranges and skips
-- the 3 below it as aged (so the refusal above was the rule, not a regrain that could not run).
update pgpm.config set retain = '30000' where parent_table = 'public.rn168r'::regclass;
select is(pgpm.regrain_history('public.rn168r'), 3,
  'with retain 30000, regrain copies exactly the 3 within-horizon sub-ranges');
select is(
  (select array_agg(distinct lo order by lo) from pgpm.log
    where parent_table = 'public.rn168r'::regclass and action = 'regrain_aged'),
  array['0', '10000', '20000'], 'the 3 below-horizon sub-ranges were skipped as aged, by lo');

select * from finish();
