-- Archive coverage recorded while a write block was present but NOT IN FORCE outlived the repair of that
-- block, and a row written past it was dropped unarchived (issue #651).
--
-- The #452/#564 rule is that the ledger watermark describes a partition's contents only while its write
-- block has been in force since the first chunk was recorded, so coverage found on a partition without
-- its block is discarded, by maintain's _enforce_write_blocks and by a direct retire() alike. Both asked
-- pgpm._is_write_blocked, and that tested only whether the trigger EXISTED. A trigger that exists and
-- does not fire is no block: a pre-#450 pgpm installed it origin-only, which a session running as
-- session_replication_role = replica (a logical-replication apply worker, a loader silencing triggers)
-- writes straight through, and an operator can disable it by hand. _install_write_block repairs either
-- state to ENABLE ALWAYS on the next tick, but the coverage recorded before the repair was kept, the
-- stale watermark read as full coverage, and retire() dropped the partition with the row in it.
--
-- The rule now: _is_write_blocked is true only for a trigger enabled ALWAYS (pg_trigger.tgenabled = 'A').
-- One predicate, three sites: coverage found under a block in any other state is discarded (logged as
-- archive_coverage_reset) before the block is repaired, and _archive_step never records coverage under
-- such a block in the first place.
--
-- PART A is the issue's upgrade path through maintain's write-block step: an origin-only block and a
-- replica-role write. Asserted by identity: WHICH ledger rows go (the monolith's two, not the sibling's,
-- which stayed ALWAYS throughout and is the positive counterpart), WHICH row survives (500), and which
-- ids the strategy is handed before the drop is allowed (1, 2, 3 twice, 500 once).
-- PART B is the direct retire() path and the other state: a block disabled by hand, an ordinary write.
-- PART C pins the archive step itself: it does not archive under an origin-only block, and does once the
-- block is ALWAYS, so "nothing archived" cannot be met by a step that archives nothing at all.
create extension if not exists pgtap;

select plan(32);

create schema pgpm_test170;

-- Every row the strategy is handed lands here, so a row handed twice shows up as two copies and a row
-- never handed as absent. At most 600 ids of range per call, so [0, 1000) takes two chunks.
create table pgpm_test170.handed (parent regclass, id bigint);
create function pgpm_test170.recorder(p_parent regclass, p_child name, p_lo text, p_hi text)
returns pgpm.archive_result language plpgsql as $$
declare v_hi numeric := least(p_lo::numeric + 600, p_hi::numeric); v_rows bigint; v_result pgpm.archive_result;
begin
  execute format('insert into pgpm_test170.handed (parent, id) select %s::regclass, id from public.%I where id >= %L and id < %L',
                 p_parent::oid, p_child, p_lo, v_hi::text);
  get diagnostics v_rows = row_count;
  v_result.covered_hi := v_hi::text;
  v_result.rows_archived := v_rows;
  return v_result;
end;
$$;

create function pgpm_test170.state(p_child name) returns text language sql as $$
  select t.tgenabled::text from pg_trigger t
   where t.tgname = 'pgpm_write_block' and t.tgrelid = to_regclass(format('public.%I', p_child))
$$;

-- ============ PART A: an origin-only block, a replica-role write, maintain's write-block step ============
-- Monolith [0, 1000) with ids 1, 2, 3; sibling [1000, 2000) with id 1500; frontier 20000 and retain 18000
-- put the horizon at 2000, so both are eligible.
create table public.ew170a (id bigint generated by default as identity primary key, payload text);
insert into public.ew170a (payload) select 'x' from generate_series(1, 3);
call pgpm.transmute('public.ew170a', 'id', 1000, p_retain => 18000, p_paused => false);
select pgpm.set_archive_fn('public.ew170a', 'pgpm_test170.recorder(regclass,name,text,text)'::regprocedure);
insert into public.ew170a (id, payload) values (1500, 'sibling'), (20000, 'frontier');

select child_name as a_mono from pgpm.part where parent_table = 'public.ew170a'::regclass and lo = '0' \gset
select child_name as a_sib from pgpm.part where parent_table = 'public.ew170a'::regclass and lo = '1000' \gset

select pgpm._enforce_write_blocks('public.ew170a');
do $$ begin for i in 1..6 loop perform pgpm._archive_step('public.ew170a'); end loop; end $$;

select results_eq(
  $$ select child_name, lo, hi from pgpm.archive_ledger where parent_table = 'public.ew170a'::regclass order by child_name, lo::numeric $$,
  format($$ values (%1$L::name, '0'::text, '600'::text), (%1$L::name, '600', '1000'), (%2$L::name, '1000', '1600'), (%2$L::name, '1600', '2000') $$,
         :'a_mono', :'a_sib'),
  'LIVENESS: (A) the monolith and the sibling are each covered by two chunks');

-- the monolith's block goes back to the origin-only state a pre-#450 pgpm installed it in
select format('alter table public.%I enable trigger pgpm_write_block', :'a_mono') as a_origin_sql \gset
:a_origin_sql;
select is(pgpm_test170.state(:'a_mono'), 'O', 'LIVENESS: (A) the monolith''s block is origin-only');
select is(pgpm_test170.state(:'a_sib'), 'A', 'LIVENESS: (A) the sibling''s block is still ALWAYS');

set session_replication_role = replica;
insert into public.ew170a (id, payload) values (500, 'replicated');
reset session_replication_role;
select results_eq(format($$ select id from public.%I order by id $$, :'a_mono'),
  $$ values (1::bigint), (2::bigint), (3::bigint), (500::bigint) $$,
  'LIVENESS: (A) a replica-role row 500 landed in the monolith past its origin-only block');
select ok(pgpm._archive_fully_covered('public.ew170a', :'a_mono'),
  'LIVENESS: (A) the stale watermark still reads as full coverage of the monolith');

select ok(not pgpm._is_write_blocked('public.ew170a', :'a_mono'), 'an origin-only block does not count as write-blocked');
select ok(pgpm._is_write_blocked('public.ew170a', :'a_sib'), 'an ALWAYS block does');

-- the first tick after the upgrade
select pgpm._enforce_write_blocks('public.ew170a');

select results_eq(
  $$ select child_name, lo, hi from pgpm.archive_ledger where parent_table = 'public.ew170a'::regclass order by child_name, lo::numeric $$,
  format($$ values (%1$L::name, '1000'::text, '1600'::text), (%1$L::name, '1600', '2000') $$, :'a_sib'),
  'the monolith''s two chunks are discarded and the sibling''s two are untouched');
select results_eq(
  $$ select action, lo, hi, rows from pgpm.log where parent_table = 'public.ew170a'::regclass and action = 'archive_coverage_reset' $$,
  $$ values ('archive_coverage_reset'::text, '0'::text, '1000'::text, 2::bigint) $$,
  'the discard is logged once, as archive_coverage_reset for [0, 1000), counting its two chunks');
select is(pgpm_test170.state(:'a_mono'), 'A', 'the same tick repaired the monolith''s block to ALWAYS');
select ok(not pgpm._archive_fully_covered('public.ew170a', :'a_mono'), 'the monolith now reads as not covered');
select is(pgpm.retire('public.ew170a', :'a_mono'), false, 'so retire() does not drop it');
select results_eq($$ select id from public.ew170a where id = 500 $$, $$ values (500::bigint) $$, 'row 500 is still live');

do $$ begin for i in 1..4 loop perform pgpm._archive_step('public.ew170a'); end loop; end $$;
select results_eq(
  $$ select id, count(*)::int from pgpm_test170.handed where parent = 'public.ew170a'::regclass group by id order by id $$,
  $$ values (1::bigint, 2), (2::bigint, 2), (3::bigint, 2), (500::bigint, 1), (1500::bigint, 1) $$,
  'archiving restarted from lo under the repaired block: 1, 2, 3 again and 500 for the first time');
select is(pgpm.retire('public.ew170a', :'a_mono'), true, 'retire() drops the monolith once its coverage was recorded under an ALWAYS block');
select is(pgpm.retire('public.ew170a', :'a_sib'), true, 'and the sibling, whose coverage was guarded throughout');
select results_eq(
  $$ select id from public.ew170a union select id from pgpm_test170.handed where parent = 'public.ew170a'::regclass order by id $$,
  $$ values (1::bigint), (2::bigint), (3::bigint), (500::bigint), (1500::bigint), (20000::bigint) $$,
  'every row ever written is still live or was handed to the strategy, 500 included');
select is((select count(*)::int from pgpm.log where parent_table = 'public.ew170a'::regclass and action = 'archive_coverage_reset'), 1,
  'no reset is logged for the sibling: the one reset row is still the monolith''s');

-- ============ PART B: a block disabled by hand, an ordinary write, a direct retire() ============
-- Monolith [0, 1000) with ids 1, 2, 3; frontier 20000 and retain 19000 put the horizon at 1000.
create table public.ew170b (id bigint generated by default as identity primary key, payload text);
insert into public.ew170b (payload) select 'x' from generate_series(1, 3);
call pgpm.transmute('public.ew170b', 'id', 1000, p_retain => 19000, p_paused => false);
select pgpm.set_archive_fn('public.ew170b', 'pgpm_test170.recorder(regclass,name,text,text)'::regprocedure);
insert into public.ew170b (id, payload) values (20000, 'frontier');
select child_name as b_mono from pgpm.part where parent_table = 'public.ew170b'::regclass and lo = '0' \gset

select pgpm._enforce_write_blocks('public.ew170b');
do $$ begin for i in 1..4 loop perform pgpm._archive_step('public.ew170b'); end loop; end $$;
select ok(pgpm._archive_fully_covered('public.ew170b', :'b_mono'), 'LIVENESS: (B) the monolith is fully archive-covered');

select format('alter table public.%I disable trigger pgpm_write_block', :'b_mono') as b_disable_sql \gset
:b_disable_sql;
insert into public.ew170b (id, payload) values (700, 'written while disabled');
select is(pgpm_test170.state(:'b_mono'), 'D', 'LIVENESS: (B) the block is present and disabled');
select results_eq(format($$ select id from public.%I order by id $$, :'b_mono'),
  $$ values (1::bigint), (2::bigint), (3::bigint), (700::bigint) $$,
  'LIVENESS: (B) an ordinary row 700 landed in the monolith past the disabled block');

select is(pgpm.retire('public.ew170b', :'b_mono'), false,
  'retire() does not drop a partition whose coverage was recorded before its block was disabled');
select results_eq(
  $$ select action, lo, hi, rows from pgpm.log where parent_table = 'public.ew170b'::regclass and action = 'archive_coverage_reset' $$,
  $$ values ('archive_coverage_reset'::text, '0'::text, '1000'::text, 2::bigint) $$,
  'retire() discarded the two chunks, logged as archive_coverage_reset for [0, 1000)');
select ok(not exists (select 1 from pgpm.archive_ledger where parent_table = 'public.ew170b'::regclass),
  'no coverage is left recorded for the monolith');
select is(pgpm_test170.state(:'b_mono'), 'A', 'retire() repaired the block to ALWAYS');
select results_eq($$ select id from public.ew170b where id = 700 $$, $$ values (700::bigint) $$, 'row 700 is still live');

do $$ begin for i in 1..4 loop perform pgpm._archive_step('public.ew170b'); end loop; end $$;
select is(pgpm.retire('public.ew170b', :'b_mono'), true, 'retire() drops it once archiving has started over under the repaired block');
select results_eq(
  $$ select id, count(*)::int from pgpm_test170.handed where parent = 'public.ew170b'::regclass group by id order by id $$,
  $$ values (1::bigint, 2), (2::bigint, 2), (3::bigint, 2), (700::bigint, 1) $$,
  'the strategy was handed 1, 2, 3 on both passes and 700 on the second');

-- ============ PART C: the archive step records nothing under a block that is not in force ============
create table public.ew170c (id bigint generated by default as identity primary key, payload text);
insert into public.ew170c (payload) select 'x' from generate_series(1, 2);
call pgpm.transmute('public.ew170c', 'id', 1000, p_retain => 19000, p_paused => false);
select pgpm.set_archive_fn('public.ew170c', 'pgpm_test170.recorder(regclass,name,text,text)'::regprocedure);
insert into public.ew170c (id, payload) values (20000, 'frontier');
select child_name as c_mono from pgpm.part where parent_table = 'public.ew170c'::regclass and lo = '0' \gset

select pgpm._enforce_write_blocks('public.ew170c');
select format('alter table public.%I enable trigger pgpm_write_block', :'c_mono') as c_origin_sql \gset
:c_origin_sql;
select is(pgpm_test170.state(:'c_mono'), 'O', 'LIVENESS: (C) the uncovered child''s block is origin-only');

do $$ begin for i in 1..3 loop perform pgpm._archive_step('public.ew170c'); end loop; end $$;
select ok(not exists (select 1 from pgpm.archive_ledger where parent_table = 'public.ew170c'::regclass)
          and not exists (select 1 from pgpm_test170.handed where parent = 'public.ew170c'::regclass),
  'the archive step neither hands rows over nor records coverage under an origin-only block');

select pgpm._enforce_write_blocks('public.ew170c');
do $$ begin for i in 1..3 loop perform pgpm._archive_step('public.ew170c'); end loop; end $$;
select results_eq(
  $$ select child_name, lo, hi from pgpm.archive_ledger where parent_table = 'public.ew170c'::regclass order by lo::numeric $$,
  format($$ values (%1$L::name, '0'::text, '600'::text), (%1$L::name, '600', '1000') $$, :'c_mono'),
  'once the tick has made the block ALWAYS, the same step archives the child');
select ok(not exists (select 1 from pgpm.log where parent_table = 'public.ew170c'::regclass and action = 'archive_coverage_reset'),
  'no archive_coverage_reset is logged when there was no coverage to discard');

select * from finish();
