-- retire() refuses a partition something other than retirement detached, on BOTH paths (issue #652).
--
-- THE BUG. retire() asked pg_inherits whether the child was still a partition of the parent only inside
-- its referenced (incoming-FK) branch. The ordinary one-step path, taken by every table nothing points
-- a foreign key at, trusted pgpm.part.attached, which an operator's own `ALTER TABLE ... DETACH
-- PARTITION` never touches. So a table the operator detached to keep it (or to archive it by hand) was
-- write-blocked and then DROPPED, rows and all, by the next retain(), contradicting docs/reference.md
-- ("A partition that is detached but carries no retiring_at was detached by something other than pgpm,
-- and retire refuses to drop it") and retire()'s own comment on the referenced path.
--
-- THE CONTRACT, one rule for both paths: a child that is no longer a partition of the parent and carries
-- no retiring_at is left alone. retire() returns false, logs exactly fail_retain_drop for its range,
-- drops nothing, and does not write-block it either, on the unreferenced path (PART A, the issue proper)
-- and on the referenced path (PART B). The rule is one-directional: a child pgpm's OWN retirement
-- detached (retiring_at set) is still dropped, which PART B shows in the same run.
--
-- ASYMMETRIC FIXTURES. Each parent has an aged monolith [0, 1000) of 3 rows, the operator's table
-- [1000, 2000) of 2 rows (ids 1500 and 1600) and an aged partition [2000, 3000) of 1 row (id 2500), with
-- the horizon at 3000, so a wrong drop, a wrong refusal and a wrong count cannot stand in for each other.
create extension if not exists pgtap;

select plan(34);

-- The ids a table holds, by name, or null when no such table exists. A results_eq over a dropped table
-- raises and takes the rest of the file with it; a null is a clean failed assertion instead, which
-- keeps the assertion count (the guard's own liveness check) honest on a run where the defect is back.
create schema pgpm_test171;
create function pgpm_test171.ids(p_child name) returns bigint[] language plpgsql as $$
declare v_ids bigint[];
begin
  if to_regclass(format('public.%I', p_child)) is null then return null; end if;
  execute format('select array_agg(id order by id) from public.%I', p_child) into v_ids;
  return v_ids;
end;
$$;

-- ============================ PART A: the unreferenced one-step path ============================
create table public.rd171a (id bigint generated by default as identity primary key, payload text);
insert into public.rd171a (payload) select 'monolith' from generate_series(1, 3);        -- ids 1..3
call pgpm.transmute('public.rd171a', 'id', 1000, p_retain => 27000);
insert into public.rd171a (id, payload)
  values (1500, 'kept one'), (1600, 'kept two'), (2500, 'aged'), (30500, 'frontier');
-- horizon 3000 (30500 - 27000, on the grid): [0, 1000), [1000, 2000) and [2000, 3000) are wholly past it

select child_name as a_mono from pgpm.part where parent_table = 'public.rd171a'::regclass and lo = '0' \gset
select child_name as a_kept from pgpm.part where parent_table = 'public.rd171a'::regclass and lo = '1000' \gset
select child_name as a_aged from pgpm.part where parent_table = 'public.rd171a'::regclass and lo = '2000' \gset
select format('public.%I', :'a_kept')::regclass::oid as a_kept_oid \gset

-- the operator takes [1000, 2000) out of the table to keep it
select format('alter table public.rd171a detach partition public.%I', :'a_kept') \gexec

-- SETUP WITNESSES. Every refusal below is "retire() did not drop it", which a table retire() could not
-- drop anything on satisfies just as well. So pin every other way retire() has of saying no as open.
select is((select pgpm._retain_boundary(c) from pgpm.config c where parent_table = 'public.rd171a'::regclass),
  '3000', 'LIVENESS: the retention horizon is 3000, so [1000, 2000) is wholly past it');
select is((select archive_fn from pgpm.config where parent_table = 'public.rd171a'::regclass),
  null::regprocedure, 'LIVENESS: no archive strategy, so the coverage gate cannot be what refuses');
select is((select count(*)::int from pg_constraint
            where confrelid = 'public.rd171a'::regclass and contype = 'f' and conparentid = 0),
  0, 'LIVENESS: nothing references this parent, so retirement takes the one-step path');
select ok(not exists (select 1 from pg_inherits
                       where inhparent = 'public.rd171a'::regclass and inhrelid = :'a_kept_oid'::oid),
  'LIVENESS: the operator''s table is no longer a partition of the parent');
select results_eq(
  $$ select attached, retiring_at, child_oid from pgpm.part
      where parent_table = 'public.rd171a'::regclass and child_name = $$ || quote_literal(:'a_kept'),
  $$ values (true, null::timestamptz, $$ || :'a_kept_oid' || $$::oid) $$,
  'LIVENESS: pgpm.part still says attached, with no retiring_at, and child_oid is its own oid (not #428''s path)');
select is(pgpm_test171.ids(:'a_kept'), array[1500, 1600]::bigint[],
  'LIVENESS: the operator''s table holds exactly ids 1500 and 1600');

-- THE REFUSAL, called directly.
select is(pgpm.retire('public.rd171a', :'a_kept'), false,
  'retire() refuses the table the operator detached');
select is((select to_regclass(format('public.%I', :'a_kept'))::oid), :'a_kept_oid'::oid,
  'the operator''s table is still there, the same relation');
select ok(to_regclass(format('public.%I', :'a_kept')) is not null
          and not exists (select 1 from pg_trigger
                           where tgrelid = :'a_kept_oid'::oid and tgname = 'pgpm_write_block'),
  'and it is left alone: not write-blocked either');
select results_eq(
  $$ select action, lo, hi, method from pgpm.log
      where parent_table = 'public.rd171a'::regclass and lo = '1000'
        and action in ('retain_drop', 'fail_retain_drop', 'retain_detach', 'fail_retain_detach', 'fail_retain_identity') order by id $$,
  $$ values ('fail_retain_drop'::text, '1000'::text, '2000'::text,
             'detached from the parent by something other than retirement; not dropping it'::text) $$,
  'logged as exactly one fail_retain_drop for [1000, 2000), naming why');

-- THROUGH retain(), the path the issue reproduces. The two aged partitions around it ARE dropped, which
-- is the witness that this run reached the DROP at all.
select is(pgpm.retain('public.rd171a'), 2,
  'retain() drops exactly the two aged partitions, not three');
select ok(to_regclass(format('public.%I', :'a_mono')) is null
          and to_regclass(format('public.%I', :'a_aged')) is null,
  'LIVENESS: the monolith [0, 1000) and the aged [2000, 3000) are gone');
select results_eq(
  $$ select lo from pgpm.log where parent_table = 'public.rd171a'::regclass and action = 'retain_drop' order by lo $$,
  $$ values ('0'::text), ('2000'::text) $$,
  'logged retain_drop for exactly those two ranges, and none for [1000, 2000)');
select is(pgpm_test171.ids(:'a_kept'), array[1500, 1600]::bigint[],
  'the operator''s table survives retain() with exactly its rows, 1500 and 1600');
select ok(not exists (select 1 from pg_trigger where tgrelid = :'a_kept_oid'::oid and tgname = 'pgpm_write_block'),
  'still not write-blocked');
select is((select count(*)::int from pgpm.part
            where parent_table = 'public.rd171a'::regclass and child_name = :'a_kept'),
  1, 'its pgpm.part row stays for the operator to deal with');
select is((select count(*)::int from pgpm.log
            where parent_table = 'public.rd171a'::regclass and action = 'fail_retain_drop' and lo = '1000'),
  2, 'and each refusal is logged: one for the direct call, one for retain()');

-- ============================ PART B: the referenced path ============================
-- Same shapes, plus an incoming FK. Its one referencing row points at the frontier, a live row, so
-- nothing references the aged ranges and a plain DETACH of [1000, 2000) is allowed.
create table public.rd171b (id bigint generated by default as identity primary key, payload text);
insert into public.rd171b (payload) select 'monolith' from generate_series(1, 3);        -- ids 1..3
call pgpm.transmute('public.rd171b', 'id', 1000, p_retain => 27000);
insert into public.rd171b (id, payload)
  values (1500, 'kept one'), (1600, 'kept two'), (2500, 'aged'), (30500, 'frontier');
create table public.rd171b_ref (id bigint primary key, p_id bigint not null references public.rd171b (id));
insert into public.rd171b_ref values (1, 30500);

select child_name as b_kept from pgpm.part where parent_table = 'public.rd171b'::regclass and lo = '1000' \gset
select child_name as b_aged from pgpm.part where parent_table = 'public.rd171b'::regclass and lo = '2000' \gset
select format('public.%I', :'b_kept')::regclass::oid as b_kept_oid \gset
select format('public.%I', :'b_aged')::regclass::oid as b_aged_oid \gset

select format('alter table public.rd171b detach partition public.%I', :'b_kept') \gexec

select is((select count(*)::int from pg_constraint
            where confrelid = 'public.rd171b'::regclass and contype = 'f' and conparentid = 0),
  1, 'LIVENESS: a foreign key references this parent, so retirement takes the referenced path');
select ok(not exists (select 1 from pg_inherits
                       where inhparent = 'public.rd171b'::regclass and inhrelid = :'b_kept_oid'::oid)
          and exists (select 1 from pgpm.part where parent_table = 'public.rd171b'::regclass
                        and child_name = :'b_kept' and attached and retiring_at is null),
  'LIVENESS: the operator''s table is detached, pgpm.part says attached, and no retirement began');

select is(pgpm.retire('public.rd171b', :'b_kept'), false,
  'retire() refuses the operator''s table on the referenced path too');
select is(pgpm_test171.ids(:'b_kept'), array[1500, 1600]::bigint[],
  'it is still there with exactly its rows');
select ok(to_regclass(format('public.%I', :'b_kept')) is not null
          and not exists (select 1 from pg_trigger
                           where tgrelid = :'b_kept_oid'::oid and tgname = 'pgpm_write_block'),
  'and left alone on this path as well: not write-blocked');
select results_eq(
  $$ select action, method from pgpm.log
      where parent_table = 'public.rd171b'::regclass and lo = '1000'
        and action in ('retain_drop', 'fail_retain_drop', 'retain_detach', 'fail_retain_detach', 'fail_retain_identity') order by id $$,
  $$ values ('fail_retain_drop'::text,
             'detached from the parent by something other than retirement; not dropping it'::text) $$,
  'logged as exactly the same fail_retain_drop, and no detach was dispatched for it');
select is((select retiring_at from pgpm.part
            where parent_table = 'public.rd171b'::regclass and child_name = :'b_kept'),
  null::timestamptz, 'and it was not marked as a retirement pgpm started');

-- ONE-DIRECTIONAL. The aged [2000, 3000) goes through pgpm's own retirement: retire() write-blocks it,
-- marks it retiring_at and dispatches the detach (no pg_cron in this database, so the dispatch itself
-- is logged fail_retain_detach; the marker is what matters here), then the detach is run by hand at top
-- level exactly as the cron job would, and retire() completes the DROP of a table that is detached but
-- carries retiring_at.
select is(pgpm.retire('public.rd171b', :'b_aged'), false,
  'LIVENESS: retire() starts pgpm''s own retirement of [2000, 3000) and returns false');
select ok((select retiring_at is not null and retiring_oid = :'b_aged_oid'::oid from pgpm.part
            where parent_table = 'public.rd171b'::regclass and child_name = :'b_aged'),
  'LIVENESS: marked retiring_at, with retiring_oid its own oid');
select ok(exists (select 1 from pg_trigger where tgrelid = :'b_aged_oid'::oid and tgname = 'pgpm_write_block'),
  'LIVENESS: and write-blocked, so the trigger probe above can see a block when there is one');
select is(pgpm_test171.ids(:'b_aged'), array[2500]::bigint[],
  'LIVENESS: it holds exactly id 2500 before the detach');

select format('alter table public.rd171b detach partition public.%I concurrently', :'b_aged') \gexec

select ok(not exists (select 1 from pg_inherits
                       where inhparent = 'public.rd171b'::regclass and inhrelid = :'b_aged_oid'::oid),
  'LIVENESS: pgpm''s retirement detached it, so both tables are now detached');
select is(pgpm.retire('public.rd171b', :'b_aged'), true,
  'retire() completes the drop of the table its own retirement detached');
select ok(to_regclass(format('public.%I', :'b_aged')) is null,
  'that table is gone');
select results_eq(
  $$ select action, lo from pgpm.log
      where parent_table = 'public.rd171b'::regclass and action in ('retain_drop', 'fail_retain_drop')
      order by id $$,
  $$ values ('fail_retain_drop'::text, '1000'::text), ('retain_drop'::text, '2000'::text) $$,
  'the operator''s range was refused and pgpm''s own was dropped, and nothing else either way');
select is(pgpm.retire('public.rd171b', :'b_kept'), false,
  'and the operator''s table is still refused after it');
select is(pgpm_test171.ids(:'b_kept'), array[1500, 1600]::bigint[],
  'still holding exactly its rows');

select * from finish();
