-- transmute and untransmute re-create identity with the original sequence's options, and reseed on its
-- lattice (issue #670).
--
-- Step 6 re-added identity on the new parent with a bare ADD GENERATED ... AS IDENTITY, kind only (#308),
-- which takes the sequence DEFAULTS: an INCREMENT BY, MINVALUE/MAXVALUE, CYCLE and CACHE the operator
-- declared were silently dropped, and step 8b reseeded at greatest(max + 1, last_value + 1), off the
-- lattice for any increment but 1 and in the wrong direction for a negative one. An odd-ids-only identity
-- (increment 2, the usual two-writer interleave) handed out even ids after the conversion. untransmute
-- re-created it the same way. Both now carry the options and reseed through _identity_reseed.
--
-- Fixtures, asymmetric on purpose, one table per shape:
--   (A) ascending, INCREMENT BY 2, ALWAYS, with one row supplied above the sequence (id 9, by OVERRIDING
--       SYSTEM VALUE): the next id must be 11 (on the odd lattice, clear of 9). max + 1 would be 10, the
--       sequence's own next 7, so neither old formula gives it;
--   (B) descending, INCREMENT BY -3, BY DEFAULT, bounded, CYCLE, with one row supplied below the
--       sequence (id -12): the next id must be -13;
--   (C) exhausted, MAXVALUE 5 INCREMENT BY 2 with 1, 3 and 5 handed out: the next insert must fail
--       exactly as the original's did ("reached maximum value"), not hand out 7 past the maximum;
--   (D) A's shape through transmute AND untransmute: the restored table keeps the options and the lattice;
--   (E) CACHE 20 through both: carried, and the reseed honours what the original's cache reserved.
-- bench/transmute_identity_options.sh runs this file against a mutant whose _identity_options yields
-- nothing (transmute_identity_kind_only), so it is also required to FAIL there.
create extension if not exists pgtap;
select plan(29);

set timezone = 'UTC';

-- (A)
create table public.ia (id bigint generated always as identity (start with 1 increment by 2) primary key, body text);
insert into public.ia (body) values ('a'), ('b'), ('c');                       -- 1, 3, 5
insert into public.ia (id, body) overriding system value values (9, 'supplied');
select is((select array_agg(id order by id) from public.ia), array[1, 3, 5, 9]::bigint[],
  'A LIVENESS: before the conversion ia holds 1, 3, 5 from the sequence and 9 supplied');
select is((select seqincrement from pg_sequence where seqrelid = pg_get_serial_sequence('public.ia', 'id')::regclass), 2::bigint,
  'A LIVENESS: its identity sequence increments by 2');
call pgpm.transmute('public.ia', 'id', 1000::bigint, p_obtain => 2);
select is((select relkind::text from pg_class where oid = 'public.ia'::regclass), 'p', 'A: ia converted');
select is((select attidentity::text from pg_attribute where attrelid = 'public.ia'::regclass and attname = 'id'), 'a',
  'A: the parent''s identity is still ALWAYS');
select is((select seqincrement from pg_sequence where seqrelid = pg_get_serial_sequence('public.ia', 'id')::regclass), 2::bigint,
  'A: the parent''s identity sequence increments by 2');
insert into public.ia (body) values ('d'), ('e');
select is((select array_agg(id order by id) from public.ia), array[1, 3, 5, 9, 11, 13]::bigint[],
  'A: the next ids are 11 and 13: on the odd lattice, clear of the supplied 9');

-- (B)
create table public.ib (id bigint generated by default as identity
                          (start with -1 increment by -3 minvalue -1000 maxvalue -1 cycle) primary key, body text);
insert into public.ib (body) values ('a'), ('b'), ('c');                       -- -1, -4, -7
insert into public.ib (id, body) values (-12, 'supplied');
select is((select array_agg(id order by id desc) from public.ib), array[-1, -4, -7, -12]::bigint[],
  'B LIVENESS: before the conversion ib holds -1, -4, -7 from the sequence and -12 supplied');
select is((select array[seqincrement, seqmin, seqmax, seqstart] from pg_sequence
            where seqrelid = pg_get_serial_sequence('public.ib', 'id')::regclass),
  array[-3, -1000, -1, -1]::bigint[], 'B LIVENESS: its sequence is -3, [-1000, -1], start -1');
call pgpm.transmute('public.ib', 'id', 1000::bigint, p_obtain => 2);
select is((select relkind::text from pg_class where oid = 'public.ib'::regclass), 'p', 'B: ib converted');
select is((select attidentity::text from pg_attribute where attrelid = 'public.ib'::regclass and attname = 'id'), 'd',
  'B: the parent''s identity is still BY DEFAULT');
select is((select array[seqincrement, seqmin, seqmax, seqstart] from pg_sequence
            where seqrelid = pg_get_serial_sequence('public.ib', 'id')::regclass),
  array[-3, -1000, -1, -1]::bigint[], 'B: the parent''s sequence has the same increment, bounds and start');
select is((select seqcycle from pg_sequence where seqrelid = pg_get_serial_sequence('public.ib', 'id')::regclass), true,
  'B: and still cycles');
insert into public.ib (body) values ('d'), ('e');
select is((select array_agg(id order by id desc) from public.ib), array[-1, -4, -7, -12, -13, -16]::bigint[],
  'B: the next ids are -13 and -16: descending, on the -1 - 3k lattice, clear of the supplied -12');

-- (C)
create table public.ic (id bigint generated always as identity (maxvalue 5 increment by 2) primary key, body text);
insert into public.ic (body) values ('a'), ('b'), ('c');                       -- 1, 3, 5
select throws_ok($$ insert into public.ic (body) values ('over') $$, '2200H', NULL,
  'C LIVENESS: before the conversion the sequence is exhausted: the next insert fails');
call pgpm.transmute('public.ic', 'id', 1000::bigint, p_obtain => 2);
select is((select relkind::text from pg_class where oid = 'public.ic'::regclass), 'p', 'C: ic converted');
select is((select seqmax from pg_sequence where seqrelid = pg_get_serial_sequence('public.ic', 'id')::regclass), 5::bigint,
  'C: the parent''s sequence keeps MAXVALUE 5');
select throws_ok($$ insert into public.ic (body) values ('over') $$, '2200H', NULL,
  'C: and is exhausted exactly as the original was: the next insert fails the same way');
select is((select array_agg(id order by id) from public.ic), array[1, 3, 5]::bigint[],
  'C: ic still holds exactly 1, 3 and 5');

-- (D)
create table public.id2 (id bigint generated always as identity (start with 1 increment by 2) primary key, body text);
insert into public.id2 (body) values ('a'), ('b');                             -- 1, 3
call pgpm.transmute('public.id2', 'id', 1000::bigint, p_obtain => 2);
insert into public.id2 (body) values ('c');                                    -- 5, in the monolith
select is((select array_agg(id order by id) from public.id2), array[1, 3, 5]::bigint[],
  'D: after the conversion id2 handed out 5, on the lattice');
select lives_ok($$ select pgpm.untransmute('public.id2') $$, 'D: untransmute restores id2');
select is((select relkind::text from pg_class where oid = 'public.id2'::regclass), 'r', 'D: id2 is a plain table again');
select is((select seqincrement from pg_sequence where seqrelid = pg_get_serial_sequence('public.id2', 'id')::regclass),
  2::bigint, 'D: the restored identity sequence still increments by 2');
insert into public.id2 (body) values ('d');
select is((select array_agg(id order by id) from public.id2), array[1, 3, 5, 7]::bigint[],
  'D: and the next id is 7, on the lattice, after the round trip');

-- (E) CACHE 20, increment 2: the first nextval reserves 1 .. 39 on disk, so last_value reads 39 and the
-- sequence's next value (for any session but the one holding the cache) is 41. The reseed never moves a
-- sequence back past what it reserved, so 41 is exactly the next id after the conversion, and 81 after the
-- round trip (41 reserved 41 .. 79 in its turn).
create table public.ie (id bigint generated always as identity (increment by 2 cache 20) primary key, body text);
insert into public.ie (body) values ('a'), ('b');                               -- 1, 3
select is((select last_value from public.ie_id_seq), 39::bigint,
  'E LIVENESS: CACHE 20 reserved up to 39, so the sequence''s next value is 41');
call pgpm.transmute('public.ie', 'id', 1000::bigint, p_obtain => 2);
select is((select array[seqincrement, seqcache] from pg_sequence where seqrelid = pg_get_serial_sequence('public.ie', 'id')::regclass),
  array[2, 20]::bigint[], 'E: the parent''s sequence keeps INCREMENT 2 and CACHE 20');
insert into public.ie (body) values ('c');
select is((select array_agg(id order by id) from public.ie), array[1, 3, 41]::bigint[],
  'E: the next id is 41, the original''s next value, on the odd lattice');
select lives_ok($$ select pgpm.untransmute('public.ie') $$, 'E: untransmute restores ie');
select is((select array[seqincrement, seqcache] from pg_sequence where seqrelid = pg_get_serial_sequence('public.ie', 'id')::regclass),
  array[2, 20]::bigint[], 'E: the restored sequence keeps INCREMENT 2 and CACHE 20');
insert into public.ie (body) values ('d');
select is((select array_agg(id order by id) from public.ie), array[1, 3, 41, 81]::bigint[],
  'E: and the next id after the round trip is 81');

select * from finish();
