-- Issue #706: state transmute's cutover and the regrain janitor and reclaim read before the lock that
-- protects it, and trusted after it. The sites #630, #689 and #554 left.
--
-- (A) Grants. GRANT and REVOKE take no lock on the table at all, so the cutover's grant replay, which ran
--     with the staging work before the rename, missed a REVOKE or GRANT committed after it: it landed on the
--     original table alone (now the monolith), and the parent every query names kept the revoked privilege
--     or lacked the granted one. The replay now reads the grants after the rename and the attach, which
--     rewrite the catalog rows every GRANT and REVOKE on the table has to rewrite too, so one committed
--     before that is carried and one that has not cannot commit until the cutover has.
-- (B) Incoming keys under p_incoming_fks => 'error'. The gate was asked in the preflight only, and 0c runs
--     for 'preserve' alone, so a key added before the cutover's lock followed the rename onto the monolith.
--     It is asked again under the lock now, and refuses.
-- (C) The transition-table trigger refusal, asked again under the lock, so a row trigger with a transition
--     table created before it is refused by pgpm rather than failing the replay with a raw error.
-- (D) The key and identity steps 6 and 8 act on, planned in the preflight. A change committed while phases
--     1 and 2 had let go of the table went unseen (an identity made ALWAYS came back BY DEFAULT); it is
--     checked after the staging LIKE, under its ACCESS SHARE, and refuses.
-- (E) The regrain janitor judges a regrain's marks under pgpm.regrain_lock, so it cannot read a cursor that
--     predates a prepare committing around it; while a driver holds the lock it skips and says so.
-- (F) _regrain_reclaim (retire's drop of a regrain's source) reads the cursor and the copies under the same
--     lock, so it waits for a step in flight instead of reading around it.
--
-- (A) to (D) open their windows the way tests/159 does: an event trigger on the cutover's own DDL, after
-- the preflight (or after the old read) and before the lock that now protects the value, makes the change
-- there, through a second session over dblink where the change must COMMIT on its own (the grants), in
-- this session where the change is DDL a second session could only have committed earlier. (E) and (F)
-- hold the lock in a second session over dblink. Every negative is paired with a witness that the window
-- really opened, and the fixtures are asymmetric: two grants in and one out, two copies' worth of state
-- held and then released.
create extension if not exists pgtap;
create extension if not exists dblink;

select plan(35);

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 't185_r1') then create role t185_r1; end if;
  if not exists (select 1 from pg_roles where rolname = 't185_r2') then create role t185_r2; end if;
end $$;

-- ====================================================================================================
-- fixtures for (A) to (D), and the one event trigger that opens each window
-- ====================================================================================================
create table public.t185a (id bigint primary key, body text, note text);
insert into public.t185a values (1, 'a', 'x'), (2, 'b', 'y'), (5, 'c', 'z');
grant select on public.t185a to t185_r1;
grant update (body) on public.t185a to t185_r1;   -- a column grant the window's REVOKE does not touch
create policy t185a_p on public.t185a using (true);   -- RLS not enabled; the policy is (A)'s window hook
comment on table public.t185a is 't185a';             -- and its COMMENT replay is the hook after the read
create temp table orig185a as select 'public.t185a'::regclass::oid as oid;

create table public.t185b (id bigint primary key, body text);
insert into public.t185b values (1, 'a'), (2, 'b');
create table public.ref185b (rid int primary key, b_id bigint);
insert into public.ref185b values (10, 2);

create table public.t185c (id bigint primary key, body text);
insert into public.t185c values (1, 'a'), (2, 'b');
create function public.t185c_noop() returns trigger language plpgsql as $$ begin return null; end $$;

create table public.t185d (id bigint generated by default as identity primary key, body text);
insert into public.t185d (body) values ('a'), ('b'), ('c');

-- what each window did: which change, whether it committed, and the table's relkind at that moment
create table public.w185 (site text, outcome text, live_relkind text);
-- a rollback undoes an insert but not a nextval, so the windows whose cutover is refused witness on these
create sequence public.w185b_seq;
create sequence public.w185c_seq;
create sequence public.w185d_seq;

create function public.t185_inject() returns event_trigger language plpgsql as $$
declare r record; v_state text;
begin
  for r in select * from pg_event_trigger_ddl_commands() loop
    -- (A) the window: the staging parent's policy, after the old grant read, before the lock. A second
    -- session commits a REVOKE and two GRANTs on the live table, which take no lock it could wait on.
    if r.command_tag = 'CREATE POLICY' and r.object_identity like '%public.t185a_pgpm_new'
       and not exists (select 1 from public.w185 where site = 'A window') then
      perform dblink_exec('dbname=' || current_database() || ' user=postgres options=-cstatement_timeout=10000',
        'revoke select on public.t185a from t185_r1; grant insert on public.t185a to t185_r2; '
        || 'grant update (note) on public.t185a to t185_r2');
      insert into public.w185 select 'A window', 'committed', relkind::text from pg_class where oid = 'public.t185a'::regclass;
    -- (A) after the read: the parent's COMMENT replay. A second session's REVOKE now has to wait for the
    -- cutover (it rewrites a catalog row the cutover has rewritten), so with a short timeout it fails.
    elsif r.command_tag = 'COMMENT' and r.object_identity = 'public.t185a'
       and not exists (select 1 from public.w185 where site = 'A late') then
      begin
        perform dblink_exec('dbname=' || current_database() || ' user=postgres options=-cstatement_timeout=1000',
          'revoke update (note) on public.t185a from t185_r2');
        v_state := 'committed';
      exception when query_canceled then   -- OTHERS does not catch a cancel, and the timeout is one
        v_state := sqlstate;
      when others then
        v_state := sqlstate;
      end;
      insert into public.w185 select 'A late', v_state, relkind::text from pg_class where oid = (select oid from orig185a);
    -- (B) to (D): the staging CREATE TABLE, after the preflight, before the lock. Once each.
    elsif r.command_tag = 'CREATE TABLE' and r.object_identity = 'public.t185b_pgpm_new'
       and not (select is_called from public.w185b_seq) then
      perform nextval('public.w185b_seq');
      alter table public.ref185b add constraint ref185b_fk foreign key (b_id) references public.t185b (id);
    elsif r.command_tag = 'CREATE TABLE' and r.object_identity = 'public.t185c_pgpm_new'
       and not (select is_called from public.w185c_seq) then
      perform nextval('public.w185c_seq');
      create trigger t185c_tt after insert on public.t185c referencing new table as nt
        for each row execute function public.t185c_noop();
    elsif r.command_tag = 'CREATE TABLE' and r.object_identity = 'public.t185d_pgpm_new'
       and not (select is_called from public.w185d_seq) then
      perform nextval('public.w185d_seq');
      alter table public.t185d alter column id set generated always;
    end if;
  end loop;
end $$;
create event trigger t185_inject on ddl_command_end
  when tag in ('CREATE POLICY', 'COMMENT', 'CREATE TABLE') execute function public.t185_inject();

-- ====================================================================================================
-- (A) the parent carries the grants the table had at the rename
-- ====================================================================================================
call pgpm.transmute('public.t185a', 'id', 10::bigint, p_obtain => 2);

select is((select outcome || ':' || live_relkind from public.w185 where site = 'A window'), 'committed:r',
  'LIVENESS: (A) a second session committed its REVOKE and GRANTs mid-cutover, while t185a was the plain table');
select is((select relkind::text from pg_class where oid = 'public.t185a'::regclass), 'p',
  'LIVENESS: (A) t185a was converted');
select ok(not has_table_privilege('t185_r1', (select oid from orig185a), 'select')
          and has_table_privilege('t185_r2', (select oid from orig185a), 'insert')
          and has_column_privilege('t185_r2', (select oid from orig185a), 'note', 'update'),
  'LIVENESS: (A) the REVOKE and both GRANTs landed on the original table, now the monolith');
select ok(not has_table_privilege('t185_r1', 'public.t185a', 'select'),
  '(A) the REVOKE of SELECT from t185_r1 holds on the converted table');
select ok(has_table_privilege('t185_r2', 'public.t185a', 'insert'),
  '(A) the table-level GRANT of INSERT to t185_r2 holds on the converted table');
select ok(has_column_privilege('t185_r2', 'public.t185a', 'note', 'update'),
  '(A) the column-level GRANT of UPDATE (note) to t185_r2 holds on the converted table');
select ok(has_column_privilege('t185_r1', 'public.t185a', 'body', 'update'),
  '(A) and the column grant made before the conversion is carried too');
select is((select outcome || ':' || live_relkind from public.w185 where site = 'A late'), '57014:r',
  '(A) a REVOKE attempted after the grants were read waited for the cutover and timed out, not committing around it');
select is((select array_agg(id order by id) from public.t185a), array[1, 2, 5]::bigint[], '(A) the rows are intact');

-- ====================================================================================================
-- (B) an incoming key added before the cutover's lock is refused under p_incoming_fks => 'error'
-- ====================================================================================================
-- Through dblink, so the conversion runs as a top-level CALL whose phases can commit.
select dblink_connect('t185', 'dbname=' || current_database());
select throws_like(
  $$ select dblink_exec('t185', 'call pgpm.transmute(''public.t185b'', ''id'', 10::bigint, p_obtain => 2)') $$,
  '%t185b has incoming foreign key(s) (ref185b_fk on ref185b)%',
  '(B) the cutover refuses the incoming key added after the preflight');
select is((select last_value::int || ':' || is_called::text from public.w185b_seq), '1:true',
  'LIVENESS: (B) the window''s key went on once, inside the cutover');
select is((select relkind::text from pg_class where oid = 'public.t185b'::regclass), 'r',
  '(B) t185b is still the plain table');
select is((select count(*)::int from pg_constraint c join pg_inherits i on i.inhrelid = c.confrelid
            where c.conrelid = 'public.ref185b'::regclass), 0,
  '(B) and no key on ref185b references a partition of anything');
select is(
  (select convalidated from pg_constraint where conrelid = 'public.t185b'::regclass and conname = 'pgpm_monolith_bound'),
  true, '(B) phases 1 and 2 committed and stand: the refusal came from the cutover, leaving the resumable state');

-- ====================================================================================================
-- (C) a transition-table row trigger created before the lock is refused by pgpm, not by the replay
-- ====================================================================================================
select throws_like(
  $$ select dblink_exec('t185', 'call pgpm.transmute(''public.t185c'', ''id'', 10::bigint, p_obtain => 2)') $$,
  '%pg_partition_magician: cannot transmute t185c -- the row trigger(s) (t185c_tt) use a transition table%',
  '(C) the cutover refuses the transition-table row trigger created after the preflight, in pgpm''s words');
select is((select last_value::int || ':' || is_called::text from public.w185c_seq), '1:true',
  'LIVENESS: (C) the window''s trigger went on once, inside the cutover');
select is((select relkind::text from pg_class where oid = 'public.t185c'::regclass), 'r',
  '(C) t185c is still the plain table');

-- ====================================================================================================
-- (D) a change to the identity the preflight planned from refuses; the re-run carries the new one
-- ====================================================================================================
select throws_like(
  $$ select dblink_exec('t185', 'call pgpm.transmute(''public.t185d'', ''id'', 10::bigint, p_obtain => 2)') $$,
  '%pg_partition_magician: the primary key, a unique constraint, an identity column or the NOT NULL of id on t185d changed while this transmute ran%',
  '(D) the cutover refuses: the identity it planned (BY DEFAULT) is not the one the table has (ALWAYS)');
select is((select last_value::int || ':' || is_called::text from public.w185d_seq), '1:true',
  'LIVENESS: (D) the window re-declared the identity once, inside the cutover');
select is((select relkind::text from pg_class where oid = 'public.t185d'::regclass) || ':' ||
          (select attidentity::text from pg_attribute where attrelid = 'public.t185d'::regclass and attname = 'id'), 'r:d',
  '(D) t185d is still the plain table, its identity as it was (the refusal rolled the window back)');
select lives_ok(
  $$ select dblink_exec('t185', 'alter table public.t185d alter column id set generated always') $$,
  'LIVENESS: (D) the operator re-declares the identity ALWAYS, committed this time');
select lives_ok(
  $$ select dblink_exec('t185', 'call pgpm.transmute(''public.t185d'', ''id'', 10::bigint, p_obtain => 2)') $$,
  '(D) the re-run converts t185d');
select is((select relkind::text from pg_class where oid = 'public.t185d'::regclass) || ':' ||
          (select attidentity::text from pg_attribute where attrelid = 'public.t185d'::regclass and attname = 'id'), 'p:a',
  '(D) and the parent''s identity is ALWAYS, the one the table had');
select dblink_disconnect('t185');

drop event trigger t185_inject;

-- ====================================================================================================
-- (E) the janitor does not judge a regrain while a driver holds pgpm.regrain_lock
-- ====================================================================================================
-- The fixture is tests/135's: a monolith [0, 2000000) holding 300 rows, frozen by a row past it, its
-- regrain prepared (capture on the source) and the cursor then cleared by hand, which is the orphan the
-- janitor exists to reap. A second session holds the regrain lock, standing in for a prepare in flight.
create table public.j185 (id bigint primary key, payload text);
insert into public.j185 select g, 'orig' from generate_series(1000, 299000, 1000) g;
insert into public.j185 values (1999999, 'widen');
call pgpm.transmute('public.j185', 'id', 1000000);
insert into public.j185 values (3500000, 'frontier');
select child_name as jmono from pgpm.part
 where parent_table = 'public.j185'::regclass and attached order by lo::numeric limit 1 \gset
select is(pgpm.regrain_step('public.j185', :'jmono', '100000', 1000), 'prepared',
  'LIVENESS: (E) the regrain is prepared (capture installed on the source)');
update pgpm.config set regrain_cursor = null where parent_table = 'public.j185'::regclass;

select dblink_connect('j185', 'dbname=' || current_database());
select dblink_exec('j185', 'begin');
select dblink_exec('j185', 'do $$ begin perform pgpm._regrain_lock(''public.j185''::regclass); end $$');
select ok(not exists (select 1 from pgpm.regrain_lock where parent_table = 'public.j185'::regclass for update skip locked),
  'LIVENESS: (E) the other session holds the regrain lock');
select pgpm._enforce_regrain_capture('public.j185');
select ok(pgpm._regrain_capture_active('public.j185', :'jmono'),
  '(E) while another session holds the regrain lock, the janitor leaves the capture alone');
select is(
  (select array_agg(action order by id) from pgpm.log where parent_table = 'public.j185'::regclass
     and action in ('skip_regrain_capture', 'regrain_capture_orphan')),
  array['skip_regrain_capture'],
  '(E) and logs the skip, and no regrain_capture_orphan');
select dblink_exec('j185', 'commit');
select dblink_disconnect('j185');
select pgpm._enforce_regrain_capture('public.j185');
select is(
  (select array_agg(action || ':' || coalesce(method, '') order by id) from pgpm.log
    where parent_table = 'public.j185'::regclass and action = 'regrain_capture_orphan'),
  array['regrain_capture_orphan:' || :'jmono'],
  'LIVENESS: (E) once the lock is free the janitor does reap this capture (it was an orphan to reap)');
select ok(not pgpm._regrain_capture_active('public.j185', :'jmono'),
  'LIVENESS: (E) and the capture is gone');

-- ====================================================================================================
-- (F) reclaim waits for a regrain driver holding pgpm.regrain_lock, then reclaims
-- ====================================================================================================
create table public.k185 (id bigint primary key, payload text);
insert into public.k185 select g, 'orig' from generate_series(1000, 299000, 1000) g;
insert into public.k185 values (1999999, 'widen');
call pgpm.transmute('public.k185', 'id', 1000000);
insert into public.k185 values (3500000, 'frontier');
select child_name as kmono from pgpm.part
 where parent_table = 'public.k185'::regclass and attached order by lo::numeric limit 1 \gset
select pgpm.regrain_step('public.k185', :'kmono', '100000', 1000);
select is(pgpm.regrain_step('public.k185', :'kmono', '100000', 1000), 'copied:99',
  'LIVENESS: (F) a regrain is in flight: [0, 100000) copied');

select dblink_connect('k185', 'dbname=' || current_database());
select dblink_exec('k185', 'begin');
select dblink_exec('k185', 'do $$ begin perform pgpm._regrain_lock(''public.k185''::regclass); end $$');
select ok(not exists (select 1 from pgpm.regrain_lock where parent_table = 'public.k185'::regclass for update skip locked),
  'LIVENESS: (F) the other session holds the regrain lock');
set lock_timeout = '300ms';
select throws_ok(
  format($$ select pgpm._regrain_reclaim('public.k185', %L, '0', '2000000') $$, :'kmono'),
  '55P03', NULL,
  '(F) while another session holds the regrain lock, reclaim waits for it (here, until lock_timeout)');
reset lock_timeout;
select is(
  (select regrain_cursor from pgpm.config where parent_table = 'public.k185'::regclass) || '|' ||
  (select string_agg(lo || '-' || hi, ',') from pgpm.part where parent_table = 'public.k185'::regclass and not attached),
  '100000|0-100000',
  '(F) and has cleared nothing: the cursor and the copy are as the regrain left them');
select dblink_exec('k185', 'commit');
select dblink_disconnect('k185');
select is(pgpm._regrain_reclaim('public.k185', :'kmono', '0', '2000000'), 1,
  'LIVENESS: (F) once the lock is free, reclaim discards the one copy');
select is((select regrain_cursor from pgpm.config where parent_table = 'public.k185'::regclass), null,
  'LIVENESS: (F) and clears the cursor');

select * from finish();
