-- Issue #732: transmute's cutover and untransmute carry an identity sequence's options (#670) as the
-- sequence has them when the conversion commits, not as an earlier read saw them.
--
-- Both read the options (_identity_options: INCREMENT BY, MINVALUE/MAXVALUE, START, CACHE, CYCLE) before
-- their explicit ACCESS EXCLUSIVE on the table, under nothing that excludes ALTER SEQUENCE, and the position
-- they reseed from under it. So an INCREMENT BY committed while either was queued for its lock was dropped:
-- the parent (or the restored table) handed out ids on the old spacing. And a re-read under the table's
-- lock alone would not hold the options still either, because ALTER SEQUENCE takes no lock on the table,
-- only SHARE ROW EXCLUSIVE on the sequence. The fix reads them under the table's lock AND under a lock on
-- the sequence that ALTER SEQUENCE must wait for (_identity_options_locked), held to the commit.
--
-- Each half has two windows, opened by event triggers on the conversion's own DDL, with a second session
-- over dblink committing the ALTER SEQUENCE (it takes no lock this session holds, so it really commits):
--   the early window, after the old read and before the table lock: INCREMENT BY 7, which must be carried;
--   the late window, after the new read: INCREMENT BY 9, which must WAIT for the conversion, so with a
--   short statement_timeout it fails rather than committing around it.
-- Identity, not just the catalog: the ids handed out afterwards are asserted, on the 7-lattice. The
-- fixtures are asymmetric (the old spacing 1, the carried one 7, the refused one 9), so no two outcomes
-- give the same ids.
create extension if not exists pgtap;
create extension if not exists dblink;

select plan(13);

-- what each window did, and the converted table's relkind at that moment
create table public.w186 (site text, outcome text, live_relkind text);

-- (A) transmute
create table public.io186 (id bigint generated by default as identity primary key, v int);
insert into public.io186 (v) select g from generate_series(1, 5) g;   -- ids 1..5
create temp table orig186 as select 'public.io186'::regclass::oid as oid;

-- (B) untransmute, with a preserved and restored incoming key: dropping it is the reversal's own DDL
-- before its lock, which is the early window's hook.
create table public.ut186 (id bigint generated by default as identity primary key, v int);
insert into public.ut186 (v) select g from generate_series(1, 5) g;   -- ids 1..5
create table public.ref186 (rid int primary key, ut_id bigint references public.ut186 (id));
insert into public.ref186 values (1, 2);
create table public.arm186 (seq text);   -- the parent's identity sequence once (B) is armed

create function public.w186_alter(p_site text, p_sql text, p_timeout int, p_rel oid) returns void
language plpgsql as $$
declare v_state text;
begin
  begin
    perform dblink_exec(format('dbname=%s user=postgres options=-cstatement_timeout=%s', current_database(), p_timeout), p_sql);
    v_state := 'committed';
  exception when query_canceled then   -- OTHERS does not catch a cancel, and the timeout is one
    v_state := sqlstate;
  when others then
    v_state := sqlstate;
  end;
  insert into public.w186 select p_site, v_state, relkind::text from pg_class where oid = p_rel;
end $$;

create function public.w186_inject() returns event_trigger language plpgsql as $$
declare r record;
begin
  for r in select * from pg_event_trigger_ddl_commands() where command_tag = 'ALTER TABLE' loop
    -- (A) early: the staging parent's ADD GENERATED (step 6), which read the options just before it
    if r.object_identity = 'public.io186_pgpm_new'
       and exists (select 1 from pg_attribute where attrelid = r.objid and attidentity <> '')
       and not exists (select 1 from public.w186 where site = 'A early') then
      perform public.w186_alter('A early', 'alter sequence public.io186_id_seq increment by 7', 10000,
                                (select oid from orig186));
    -- (A) late: the rename of the original into the monolith, under the table's lock and after the re-read
    elsif r.objid = (select oid from orig186) and r.object_identity <> 'public.io186'
       and not exists (select 1 from public.w186 where site = 'A late') then
      perform public.w186_alter('A late', 'alter sequence public.io186_id_seq increment by 9', 1000, r.objid);
    -- (B) early: untransmute drops the restored incoming key, before its lock
    elsif exists (select 1 from public.arm186) and r.objid = to_regclass('public.ref186')
       and not exists (select 1 from public.w186 where site = 'B early') then
      perform public.w186_alter('B early', format('alter sequence %s increment by 7', (select seq from public.arm186)),
                                10000, to_regclass('public.ut186'));
    -- (B) late: untransmute's DETACH, under its lock and after the options read
    elsif exists (select 1 from public.arm186) and r.objid = to_regclass('public.ut186')
       and not exists (select 1 from public.w186 where site = 'B late') then
      perform public.w186_alter('B late', format('alter sequence %s increment by 9', (select seq from public.arm186)),
                                1000, r.objid);
    end if;
  end loop;
end $$;
create event trigger w186_inject on ddl_command_end when tag in ('ALTER TABLE')
  execute function public.w186_inject();

-- ============================ (A) transmute ============================
call pgpm.transmute('public.io186', 'id', 1000::bigint, p_obtain => 2);

select is((select outcome || ':' || live_relkind from public.w186 where site = 'A early'), 'committed:r',
  'LIVENESS: (A) INCREMENT BY 7 committed in another session after step 6 read the options, io186 still the plain table');
select is((select relkind::text from pg_class where oid = 'public.io186'::regclass), 'p',
  'LIVENESS: (A) io186 was converted');
select is((select seqincrement from pg_sequence where seqrelid = pg_get_serial_sequence('public.io186', 'id')::regclass),
  7::bigint, '(A) the parent''s identity sequence has INCREMENT BY 7, the spacing the table had at the rename');
select is((select outcome from public.w186 where site = 'A late'), '57014',
  '(A) an ALTER SEQUENCE attempted after the options were read waited for the cutover and timed out, not committing around it');
insert into public.io186 (v) values (100);
insert into public.io186 (v) values (101);
select is((select array_agg(id order by id) from public.io186 where v in (100, 101)),
  array[12, 19]::bigint[],
  '(A) the next two ids are 12 and 19: 5 + 7, then on the 7-lattice (not 12 and 13, not 14 and 23)');

-- ============================ (B) untransmute ============================
call pgpm.transmute('public.ut186', 'id', 1000::bigint, p_obtain => 2, p_incoming_fks => 'preserve');
select is(pgpm.restore_incoming_fks('public.ut186'), 1, 'LIVENESS: (B) the incoming key is restored on the parent');
insert into public.arm186 select pg_get_serial_sequence('public.ut186', 'id');
select is((select seqincrement from pg_sequence where seqrelid = (select seq::regclass from public.arm186)),
  1::bigint, 'LIVENESS: (B) the parent''s identity sequence has INCREMENT BY 1 before the reversal');

select is(pgpm.untransmute('public.ut186')::text, 'ut186', 'LIVENESS: (B) the reversal completed, handing back ut186');
select is((select outcome || ':' || live_relkind from public.w186 where site = 'B early'), 'committed:p',
  'LIVENESS: (B) INCREMENT BY 7 committed in another session before the reversal''s lock, ut186 still partitioned');
select is((select seqincrement from pg_sequence where seqrelid = pg_get_serial_sequence('public.ut186', 'id')::regclass),
  7::bigint, '(B) the restored table''s identity sequence has INCREMENT BY 7, the spacing the parent had at the reversal');
select is((select outcome from public.w186 where site = 'B late'), '57014',
  '(B) an ALTER SEQUENCE attempted after the options were read waited for the reversal and timed out');
select is((select relkind::text from pg_class where oid = 'public.ut186'::regclass), 'r',
  'LIVENESS: (B) ut186 is a plain table again');
insert into public.ut186 (v) values (100);
insert into public.ut186 (v) values (101);
select is((select array_agg(id order by id) from public.ut186 where v in (100, 101)),
  array[6, 13]::bigint[],
  '(B) the next two ids are 6 and 13: the parent''s next value, then on the 7-lattice (not 6 and 7)');

drop event trigger w186_inject;

select * from finish();
