-- Orphaned-child guard. The drain (and a failed regrain) create child partitions as standalone
-- tables (CREATE TABLE ... LIKE) before attaching them; an interrupted run can leave an un-attached
-- table behind, which DROP TABLE <parent> CASCADE does NOT remove. If the table is later re-transmuted,
-- the next run could reuse that orphan by name and INSERT colliding keys -> a cryptic later dup-key.
-- transmute() must refuse UP FRONT when a standalone table matching the child-partition naming exists.
-- The coarse monolith's _p<lo>_to_<hi> name must NOT be mistaken for an orphan (the guard regex matches
-- only the data-independent digit suffix). See REDESIGN.md and REDESIGN.md section 6.
create extension if not exists pgtap;

select plan(6);

create table public.og (id bigint generated by default as identity primary key, payload text);
insert into public.og (payload) select 'x' from generate_series(1, 300);
-- simulate the orphan an interrupted drain / regrain leaves behind: a standalone table whose
-- name matches a child partition (<rel>_p<19 digits> for the id grid)
create table public.og_p0000000000000000000 (like public.og);

select has_table('public', 'og_p0000000000000000000',
  'precondition: an orphaned child-partition-named table exists standalone');

-- Pinned by MESSAGE, not by SQLSTATE alone. In this fixture (300 ids, step 100000) the monolith is the
-- one-step cell [0, 100000), whose name is og_p0000000000000000000, the orphan's own name, so with the
-- orphan guard gone transmute is STILL refused with P0001, by the monolith-name guard. A bare 'P0001'
-- accepted that refusal and certified a guard that was not there; only the orphan guard says this.
select throws_like(
  $$ call pgpm.transmute('public.og', 'id', 100000) $$,
  'pg_partition_magician: public.og_p0000000000000000000 already exists as a standalone table matching this parent''s partition naming%',
  'transmute refuses when an orphaned child-partition table already exists (no cryptic later dup-key)');

select is(
  (select relkind::text from pg_class where oid = 'public.og'::regclass),
  'r', 'the refusal mutated nothing: og is still a plain (un-partitioned) table');

-- remedy: drop the orphan, then the same transmute succeeds
drop table public.og_p0000000000000000000;
call pgpm.transmute('public.og', 'id', 100000);
select pass('once the orphan is dropped, transmute succeeds');

-- no false positive (1): a sibling sharing the <rel>_p prefix but not partition-shaped (no digit suffix)
create table public.sib (id bigint generated by default as identity primary key, payload text);
insert into public.sib (payload) select 'x' from generate_series(1, 50);
create table public.sib_promotions (note text);   -- starts with sib_p, but 'romotions' are not digits
call pgpm.transmute('public.sib', 'id', 100000);
select pass('a sibling named <rel>_promotions does not trip the guard (requires <rel>_p<digits>)');

-- no false positive (2): a standalone table named like the coarse MONOLITH (_p<digits>_to_<digits>) is
-- NOT an orphan -- the digit-only suffix regex excludes the _to_ form.
create table public.z (id bigint generated by default as identity primary key, payload text);
insert into public.z (payload) select 'x' from generate_series(1, 50);
create table public.z_p0000000000000000000_to_0000000000000100000 (note text);
call pgpm.transmute('public.z', 'id', 100000);
select pass('a standalone table named like the coarse monolith (_to_) does not trip the orphan guard');

select * from finish();
