-- untransmute hands back a table whose parent was moved with ALTER TABLE ... SET SCHEMA (issue #827).
--
-- Moving the managed table is documented as safe (docs/guide.md, #727): SET SCHEMA moves the parent and
-- leaves every partition, the monolith among them, where it was. untransmute resolved the renamed monolith
-- as <the parent's CURRENT schema>.<name> and built the restored table's comment, grant, policy and
-- publication statements the same way, where nothing of that name exists once the parent is dropped, so
-- every reverse of a moved table died raw with 42P01 'relation "<new schema>.<name>" does not exist'.
--
-- Now the restored table is named by the identity transmute recorded (pgpm.config.monolith_oid) and moved
-- into the parent's schema, where the application has been finding it since the move. The fixture is one
-- table carrying something of every kind the reverse names: a carried secondary index, an identity column,
-- a trigger, a preserved incoming foreign key, and a comment, grant, policy, publication membership and
-- replica identity set on the managed table AFTER the move, so a reverse that replays any of them against
-- the wrong schema, or hands back the conversion-time state, fails a different assertion. Its rows are
-- 1, 2, 3, 5 and 8, so a lost or resurrected row cannot pass as the same set.
-- bench/untransmute_moved_parent.sh runs this file against a mutant that resolves the restored table in
-- the parent's schema again (untransmute_moved_parent_resolved_by_name), so it is also required to FAIL there.
create extension if not exists pgtap;
select plan(22);

do $$ begin
  if not exists (select 1 from pg_roles where rolname = 't220_reader') then create role t220_reader; end if;
end $$;

create schema um220a;
create schema um220b;
create table um220a.ev (id bigint generated by default as identity primary key, body text not null);
create index ev_body_idx on um220a.ev (body);
insert into um220a.ev (id, body) values (1, 'a'), (2, 'b'), (3, 'c'), (5, 'e'), (8, 'h');
create table um220a.items (id int primary key, ev_id bigint references um220a.ev (id));
insert into um220a.items values (10, 1), (11, 8);
create function um220a.touch() returns trigger language plpgsql as $f$ begin new.body := new.body || '!'; return new; end $f$;
create trigger ev_touch before insert on um220a.ev for each row execute function um220a.touch();
comment on table um220a.ev is 'at the conversion';

call pgpm.transmute('um220a.ev', 'id', 100::bigint, p_obtain => 2, p_incoming_fks => 'preserve');
select is(pgpm.restore_incoming_fks('um220a.ev'), 1, 'fixture: the preserved key from items is back on the parent');
select oid as mon_oid, relnamespace::regnamespace::text as mon_nsp from pg_class
 where oid = (select monolith_oid from pgpm.config where parent_table = 'um220a.ev'::regclass) \gset
select conindid as key_idx from pg_constraint where conrelid = :mon_oid and contype = 'p' \gset
select indexrelid as body_idx from pg_index where indrelid = :mon_oid
   and indexrelid = (select oid from pg_class where relname = 'ev_body_idx' and relnamespace = 'um220a'::regnamespace) \gset

alter table um220a.ev set schema um220b;
-- the operator's changes, all on the managed table after the move
comment on table um220b.ev is 'after the move';
grant select on um220b.ev to t220_reader;
alter table um220b.ev enable row level security;
create policy ev_after on um220b.ev for select to t220_reader using (id < 5);
create publication pub220 for table um220b.ev;
alter table um220b.ev replica identity full;

select is(:'mon_nsp'::text, 'um220a', 'LIVENESS: the monolith partition stayed in um220a');
select is((select relkind::text || ' ' || relnamespace::regnamespace::text from pg_class where oid = 'um220b.ev'::regclass),
  'p um220b', 'LIVENESS: the managed table is um220b.ev, still partitioned');
select ok(to_regclass('um220a.ev') is null and to_regclass('um220b.ev') is not null,
  'LIVENESS: nothing named ev is left in um220a, so a reverse that resolves it there or in um220b by name has nothing to find');
select is((select array_agg(id order by id) from um220b.ev), array[1, 2, 3, 5, 8]::bigint[],
  'LIVENESS: every row is inside the monolith, so the door is open');

select lives_ok($$ select pgpm.untransmute('um220b.ev') $$, 'untransmute of the moved table succeeds');
select is((select oid from pg_class where relname = 'ev' and relnamespace = 'um220b'::regnamespace), :mon_oid::oid,
  'the restored table is the monolith transmute recorded, by oid');
select is((select relkind::text || ' ' || relnamespace::regnamespace::text from pg_class where oid = :mon_oid),
  'r um220b', 'and it is a plain table in the parent''s schema, where the application found it since the move');
select ok(to_regclass('um220a.ev') is null and not exists (select 1 from pg_class where relnamespace = 'um220a'::regnamespace
            and relname like 'ev\_p%'),
  'nothing of it is left behind in um220a, under the table''s name or a partition''s');
select is((select array_agg(id order by id) from um220b.ev), array[1, 2, 3, 5, 8]::bigint[],
  'the restored table holds exactly ids 1, 2, 3, 5 and 8');
select is((select array_agg(c.relname::text || ' ' || c.relnamespace::regnamespace::text order by c.relname)
             from pg_index i join pg_class c on c.oid = i.indexrelid where i.indrelid = :mon_oid),
  array['ev_body_idx um220b', 'ev_pkey um220b'], 'its key and its carried index came with it, under their own names');
select is((select array[conindid = :key_idx, (select indexrelid from pg_index where indexrelid = :body_idx) is not null]
             from pg_constraint where conrelid = :mon_oid and contype = 'p'),
  array[true, true], 'and they are the original indexes, not rebuilt');
select is(obj_description(:mon_oid, 'pg_class'), 'after the move', 'the comment is the one set on the managed table after the move');
select ok(has_table_privilege('t220_reader', :mon_oid::oid, 'select'), 'the grant made after the move is on the restored table');
select is((select array_agg(policyname::text || ':' || qual) from pg_policies where schemaname = 'um220b' and tablename = 'ev')
           || (select relrowsecurity::text from pg_class where oid = :mon_oid),
  array['ev_after:(id < 5)', 'true'], 'and so is the policy, with row security on');
select is((select array_agg(schemaname::text || '.' || tablename::text) from pg_publication_tables where pubname = 'pub220'),
  array['um220b.ev'], 'the publication joined after the move publishes the restored table');
select is((select relreplident::text from pg_class where oid = :mon_oid), 'f', 'and its replica identity is the FULL set after the move');
select is((select array_agg(tgname::text) from pg_trigger where tgrelid = :mon_oid and not tgisinternal),
  array['ev_touch'], 'the trigger was replayed onto the restored table');
select is((select string_agg(confrelid::regclass::text || ' ' || convalidated::text, ', ') from pg_constraint
            where conrelid = 'um220a.items'::regclass and contype = 'f'),
  'um220b.ev false', 'the preserved key from items references the restored table again, NOT VALID (#577)');
select lives_ok($$ insert into um220b.ev (body) values ('new') $$, 'a write by the identity column succeeds');
select is((select id::text || ':' || body from um220b.ev where body like 'new%'), '9:new!',
  'the identity resumes past the highest id, and the replayed trigger fired');
select is((select relnamespace::regnamespace::text from pg_class
            where oid = pg_get_serial_sequence('um220b.ev', 'id')::regclass), 'um220b',
  'the identity sequence lives with the table');

select * from finish();
