-- The table's identity sequences keep their names through transmute and untransmute (issue #877, bullet 1).
--
-- transmute's step 6 re-adds identity on the parent while it is still named <table>_pgpm_new, so PostgreSQL
-- named the new sequence <table>_pgpm_new_<col>_seq, and step 3 dropped the original <table>_<col>_seq with
-- the monolith's identity. untransmute re-adds identity on the monolith before renaming it back, so the
-- restored table's sequence was <table>_p<label>_<col>_seq. Every statement that names the sequence (setval,
-- nextval or currval by name, GRANT ... ON SEQUENCE, ALTER SEQUENCE) failed with 42P01 after either, the #789
-- class (a name the table gave something, replaced by one pgpm's staging chose) for the identity sequence.
--
-- Now transmute hands the parent's sequence the original's name once step 3 has freed it, and untransmute
-- hands the restored table's the parent's (the name the managed table's sequence carries at the reverse, as
-- #830 does for indexes) once the parent's DROP has freed it. Fixtures, asymmetric so a reverse that renames
-- one column's sequence and not the other's, or names it by convention rather than identity, fails:
--   (A) sq258: two identity columns, id (ALWAYS, the default name sq258_id_seq) and n (BY DEFAULT, INCREMENT
--       BY 2, its sequence renamed sq258_n_custom before the conversion and sq258_n_live while managed), 3 rows;
--   (B) mv258: the parent moved to another schema while managed, and a squatter on mv258_id_seq left behind
--       in the old one, so the restored sequence is named in the schema it ends up in, 2 rows.
-- bench/identity_sequence_name.sh runs this file against two mutants (transmute's rename dropped, and
-- untransmute's), so it is also required to FAIL there.
create extension if not exists pgtap;
select plan(19);

-- ==================== (A) two identity columns, one named by the operator ====================
create table public.sq258 (id bigint generated always as identity, n bigint generated by default as identity (increment by 2),
                           v text, primary key (id));
alter sequence public.sq258_n_seq rename to sq258_n_custom;
insert into public.sq258 (v) values ('a'), ('b'), ('c');
select is(pg_get_serial_sequence('public.sq258', 'id') || ' ' || pg_get_serial_sequence('public.sq258', 'n'),
  'public.sq258_id_seq public.sq258_n_custom', 'LIVENESS: (A) the table''s identity sequences are sq258_id_seq and sq258_n_custom');
call pgpm.transmute('public.sq258', 'id', 100::bigint, p_obtain => 2);
select is((select relkind::text from pg_class where oid = 'public.sq258'::regclass), 'p', 'LIVENESS: (A) sq258 is converted');
select is((select array_agg(attname::text || ':' || attidentity::text order by attnum) from pg_attribute
            where attrelid = 'public.sq258'::regclass and attidentity <> ''),
  array['id:a', 'n:d'], 'LIVENESS: (A) the parent carries both identity columns, in their kinds');
select is(pg_get_serial_sequence('public.sq258', 'id') || ' ' || pg_get_serial_sequence('public.sq258', 'n'),
  'public.sq258_id_seq public.sq258_n_custom',
  'A: the converted table''s identity sequences keep the original''s names, sq258_id_seq and sq258_n_custom');
select is((select count(*)::int from pg_class where relnamespace = 'public'::regnamespace and relname like 'sq258\_pgpm\_new%'), 0,
  'A: no sequence is left under the staging name sq258_pgpm_new');
select lives_ok($$ grant usage on sequence public.sq258_id_seq, public.sq258_n_custom to public $$,
  'A: GRANT ... ON SEQUENCE naming them runs on the converted table');
insert into public.sq258 (v) values ('d');
select is((select id::text || ':' || n::text from public.sq258 where v = 'd'), '4:7',
  'A: and they are the parent''s, resuming where the originals stopped (id 4, n 7 on its INCREMENT BY 2)');
-- the operator renames one of them while the table is managed
alter sequence public.sq258_n_custom rename to sq258_n_live;
select is(pgpm.untransmute('public.sq258')::text, 'sq258', 'LIVENESS: (A) sq258 is restored');
select is((select relkind::text from pg_class where oid = 'public.sq258'::regclass), 'r', 'LIVENESS: (A) an ordinary table again');
select is(pg_get_serial_sequence('public.sq258', 'id') || ' ' || pg_get_serial_sequence('public.sq258', 'n'),
  'public.sq258_id_seq public.sq258_n_live',
  'A: the restored table''s identity sequences carry the managed table''s names, sq258_id_seq and sq258_n_live');
select is((select count(*)::int from pg_class where relnamespace = 'public'::regnamespace and relkind = 'S'
             and relname like 'sq258\_p0%'), 0,
  'A: no sequence is left under the monolith''s name');
insert into public.sq258 (v) values ('e');
select is((select array_agg(id::text || ':' || n::text || ':' || v order by id) from public.sq258),
  array['1:1:a', '2:3:b', '3:5:c', '4:7:d', '5:9:e'],
  'A: the restored sequences resume the lattice (id 5, n 9), so the table holds exactly its five rows');

-- ==================== (B) a moved parent, a squatter left in the old schema ====================
create schema s258;
create table public.mv258 (id bigint generated by default as identity primary key, v text);
insert into public.mv258 (v) values ('x'), ('y');
call pgpm.transmute('public.mv258', 'id', 100::bigint, p_obtain => 2);
select is(pg_get_serial_sequence('public.mv258', 'id'), 'public.mv258_id_seq',
  'B: the converted table''s identity sequence is mv258_id_seq');
alter table public.mv258 set schema s258;
create sequence public.mv258_id_seq;   -- not the table's: a squatter on the name in the schema it left
select is(pg_get_serial_sequence('s258.mv258', 'id'), 's258.mv258_id_seq',
  'LIVENESS: (B) the parent''s sequence moved with it, and public.mv258_id_seq is another sequence');
select lives_ok($$ select pgpm.untransmute('s258.mv258') $$,
  'B: untransmute runs, the name in the schema the table left in nobody''s way');
select is((select relkind::text from pg_class where oid = to_regclass('s258.mv258')), 'r',
  'LIVENESS: (B) mv258 is restored in s258, an ordinary table again');
select is(pg_get_serial_sequence('s258.mv258', 'id'), 's258.mv258_id_seq',
  'B: its identity sequence is s258.mv258_id_seq, named in the schema it ended up in');
select is((select count(*)::int from pg_depend d where d.refobjid = 's258.mv258'::regclass
             and d.objid = 'public.mv258_id_seq'::regclass), 0,
  'B: and the squatter is still not the table''s');
insert into s258.mv258 (v) values ('z');
select is((select array_agg(id::text || ':' || v order by id) from s258.mv258), array['1:x', '2:y', '3:z'],
  'B: the restored sequence resumes at 3');

select * from finish();
