-- The table's identity sequences keep their GRANTS through transmute and untransmute (issue #1076, review
-- pass 10 F1-03 and F1-04).
--
-- transmute's step 6 re-adds identity on the new parent, which makes a NEW sequence, and step 3a hands it the
-- original's name (#877). untransmute re-adds identity on the restored table and hands that sequence the
-- managed table's name. Neither carried the sequence's privileges: the new sequence was born with the
-- converting role's ALTER DEFAULT PRIVILEGES (on Supabase, anon and authenticated) and the original's own
-- grants went with it. So the app granted USAGE and SELECT on <table>_id_seq lost them (nextval or currval by
-- name, 42501) though reference.md says a GRANT ... ON SEQUENCE naming the sequence keeps working, and a role
-- the operator had REVOKEd from the sequence got UPDATE (setval) back. Both now carry the source sequence's
-- grants the way the table's are carried (#838, #875, #903): the destination's ACL reset first, the owner
-- included, then every grant of the source, table and column level, each under its grantor.
--
-- ASYMMETRIC FIXTURE. The default privileges give t297_stranger ALL on every sequence postgres creates in
-- public. sq297 has two identity columns whose sequences end with DIFFERENT ACLs, so a carry that swaps them,
-- or carries one onto both, fails:
--   id (ALWAYS):      the stranger's grant REVOKEd; t297_app USAGE and SELECT; t297_bob USAGE with grant
--                     option, through which bob grants t297_carol USAGE (grantor bob, not the owner);
--   n (BY DEFAULT, INCREMENT BY 2): the stranger's ALL kept; t297_app SELECT on the column last_value only.
-- (A) transmute, (B) untransmute after the operator changes both sequences' grants while managed, (C) nl297,
-- created BEFORE the default privileges, so its sequence has the owner's implicit NULL ACL, (D) a session that
-- cannot become bob, refused up front because a grant on the identity SEQUENCE needs bob to replay it.
-- WITNESSES: each source ACL is asserted before, each conversion is asserted to have happened, and each
-- destination sequence is asserted to be a new sequence under the source's name.
create extension if not exists pgtap;
select plan(29);

-- Roles are cluster-wide and the database is per-file, so they are created only when absent; dropped at the end.
do $$ begin
  if not exists (select 1 from pg_roles where rolname = 't297_app')      then create role t297_app;      end if;
  if not exists (select 1 from pg_roles where rolname = 't297_stranger') then create role t297_stranger; end if;
  if not exists (select 1 from pg_roles where rolname = 't297_bob')      then create role t297_bob;      end if;
  if not exists (select 1 from pg_roles where rolname = 't297_carol')    then create role t297_carol;    end if;
  if not exists (select 1 from pg_roles where rolname = 't297_owner')    then create role t297_owner;    end if;
end $$;
do $$ begin
  if pg_has_role('t297_owner', 't297_bob', 'member') then revoke t297_bob from t297_owner; end if;
end $$;
grant usage, create on schema public to t297_owner;
grant usage on schema public to t297_bob, t297_carol, t297_app, t297_stranger;
grant usage on schema pgpm to t297_owner;
grant all on all tables in schema pgpm to t297_owner;
grant all on all sequences in schema pgpm to t297_owner;

-- a sequence's ACL as text, GRANTOR included, column grants too (a NULL relacl read as the owner's default)
create function pg_temp.acl297(p regclass) returns text[] language sql stable as $$
  select array_agg(e order by e) from (
    select pg_get_userbyid(a.grantee) || ':' || a.privilege_type || case when a.is_grantable then '*' else '' end
           || '/' || pg_get_userbyid(a.grantor) as e
      from pg_class c, aclexplode(coalesce(c.relacl, acldefault('s', c.relowner))) a where c.oid = p
    union all
    select att.attname || '/' || pg_get_userbyid(a.grantee) || ':' || a.privilege_type
           || case when a.is_grantable then '*' else '' end || '/' || pg_get_userbyid(a.grantor)
      from pg_attribute att, aclexplode(att.attacl) a
     where att.attrelid = p and att.attnum > 0 and not att.attisdropped and att.attacl is not null) s
$$;
create function pg_temp.seq297(p_tbl text, p_col text) returns regclass language sql stable as $$
  select pg_get_serial_sequence(p_tbl, p_col)::regclass
$$;

-- (C)'s table, before the default privileges: its sequence keeps the NULL ACL
create table public.nl297 (id bigint generated always as identity primary key, v text);
insert into public.nl297 (v) values ('p'), ('q');

alter default privileges in schema public grant all on sequences to t297_stranger;

create table public.sq297 (id bigint generated always as identity, n bigint generated by default as identity (increment by 2),
                           v text, primary key (id));
insert into public.sq297 (v) values ('a'), ('b'), ('c');
revoke all on sequence public.sq297_id_seq from t297_stranger;
grant usage, select on sequence public.sq297_id_seq to t297_app;
grant usage on sequence public.sq297_id_seq to t297_bob with grant option;
set role t297_bob;
grant usage on sequence public.sq297_id_seq to t297_carol;
reset role;
grant select (last_value) on public.sq297_n_seq to t297_app;

create temp table before297 as
  select pg_temp.acl297('public.sq297_id_seq') as id_acl, pg_temp.acl297('public.sq297_n_seq') as n_acl,
         'public.sq297_id_seq'::regclass::oid as id_oid, 'public.sq297_n_seq'::regclass::oid as n_oid;
select is((select id_acl from before297),
  array['postgres:SELECT/postgres', 'postgres:UPDATE/postgres', 'postgres:USAGE/postgres',
        't297_app:SELECT/postgres', 't297_app:USAGE/postgres', 't297_bob:USAGE*/postgres',
        't297_carol:USAGE/t297_bob'],
  'LIVENESS: sq297_id_seq grants the app USAGE and SELECT, bob USAGE with grant option, carol USAGE from bob, the stranger nothing');
select is((select n_acl from before297),
  array['last_value/t297_app:SELECT/postgres',
        'postgres:SELECT/postgres', 'postgres:UPDATE/postgres', 'postgres:USAGE/postgres',
        't297_stranger:SELECT/postgres', 't297_stranger:UPDATE/postgres', 't297_stranger:USAGE/postgres'],
  'LIVENESS: sq297_n_seq keeps the stranger''s ALL and grants the app SELECT on last_value alone');
create sequence public.probe297;
select ok(has_sequence_privilege('t297_stranger', 'public.probe297', 'UPDATE'),
  'LIVENESS: a sequence created now is born with the stranger''s UPDATE (the default privileges apply)');
drop sequence public.probe297;

-- ================= (A) transmute =================
call pgpm.transmute('public.sq297', 'id', 100::bigint, p_obtain => 2);
select is((select relkind::text from pg_class where oid = 'public.sq297'::regclass), 'p',
  'A LIVENESS: sq297 was converted into a partitioned parent');
select ok(pg_temp.seq297('public.sq297', 'id')::text = 'sq297_id_seq'
          and pg_temp.seq297('public.sq297', 'n')::text = 'sq297_n_seq'
          and pg_temp.seq297('public.sq297', 'id')::oid <> (select id_oid from before297)
          and pg_temp.seq297('public.sq297', 'n')::oid <> (select n_oid from before297),
  'A LIVENESS: both of the parent''s identity sequences are new sequences under the original names');
select is(pg_temp.acl297('public.sq297_id_seq'), (select id_acl from before297),
  'A: the parent''s sq297_id_seq holds exactly the original''s grants, each under its grantor');
select is(pg_temp.acl297('public.sq297_n_seq'), (select n_acl from before297),
  'A: and sq297_n_seq exactly its own original''s, the column grant on last_value included');
select ok(has_sequence_privilege('t297_app', 'public.sq297_id_seq', 'USAGE')
          and has_sequence_privilege('t297_app', 'public.sq297_id_seq', 'SELECT'),
  'A: the app keeps USAGE and SELECT on sq297_id_seq');
select ok(not has_sequence_privilege('t297_stranger', 'public.sq297_id_seq', 'UPDATE')
          and not has_sequence_privilege('t297_stranger', 'public.sq297_id_seq', 'USAGE'),
  'A: the stranger the operator revoked gets neither UPDATE (setval) nor USAGE on sq297_id_seq back');
select ok(has_sequence_privilege('t297_stranger', 'public.sq297_n_seq', 'UPDATE'),
  'A LIVENESS: the stranger keeps UPDATE on sq297_n_seq, which the operator never revoked');
set role t297_bob;
revoke usage on sequence public.sq297_id_seq from t297_carol;
reset role;
select ok(not has_sequence_privilege('t297_carol', 'public.sq297_id_seq', 'USAGE')
          and has_sequence_privilege('t297_app', 'public.sq297_id_seq', 'USAGE'),
  'A: bob''s REVOKE takes carol''s USAGE away on the parent''s sequence, so it is still his grant');
insert into public.sq297 (v) values ('d');
select is((select id::text || ':' || n::text from public.sq297 where v = 'd'), '4:7',
  'A LIVENESS: the parent''s sequences resume where the originals stopped');

-- ================= (B) untransmute =================
-- the operator changes both sequences' grants while the table is managed
grant usage on sequence public.sq297_id_seq to t297_carol;
revoke select on sequence public.sq297_id_seq from t297_app;
revoke all on sequence public.sq297_n_seq from t297_stranger;
grant update on sequence public.sq297_n_seq to t297_app;
create temp table parent297 as
  select pg_temp.acl297('public.sq297_id_seq') as id_acl, pg_temp.acl297('public.sq297_n_seq') as n_acl,
         'public.sq297_id_seq'::regclass::oid as id_oid, 'public.sq297_n_seq'::regclass::oid as n_oid;
select ok((select id_acl from parent297) @> array['t297_carol:USAGE/postgres', 't297_app:USAGE/postgres']
          and not (select id_acl from parent297) @> array['t297_app:SELECT/postgres']
          and (select n_acl from parent297) @> array['t297_app:UPDATE/postgres']
          and not has_sequence_privilege('t297_stranger', 'public.sq297_n_seq', 'UPDATE'),
  'B LIVENESS: the managed sequences carry the operator''s changes, and the stranger holds nothing on sq297_n_seq');
select is(pgpm.untransmute('public.sq297')::text, 'sq297', 'B LIVENESS: untransmute restored sq297');
select is((select relkind::text from pg_class where oid = 'public.sq297'::regclass), 'r',
  'B LIVENESS: sq297 is an ordinary table again');
select ok(pg_temp.seq297('public.sq297', 'id')::text = 'sq297_id_seq'
          and pg_temp.seq297('public.sq297', 'n')::text = 'sq297_n_seq'
          and pg_temp.seq297('public.sq297', 'id')::oid <> (select id_oid from parent297)
          and pg_temp.seq297('public.sq297', 'n')::oid <> (select n_oid from parent297),
  'B LIVENESS: both restored identity sequences are new sequences under the managed table''s names');
select is(pg_temp.acl297('public.sq297_id_seq'), (select id_acl from parent297),
  'B: the restored sq297_id_seq holds exactly the managed sequence''s grants');
select is(pg_temp.acl297('public.sq297_n_seq'), (select n_acl from parent297),
  'B: and sq297_n_seq exactly its own managed sequence''s');
select ok(not has_sequence_privilege('t297_stranger', 'public.sq297_n_seq', 'UPDATE')
          and has_sequence_privilege('t297_app', 'public.sq297_n_seq', 'UPDATE'),
  'B: the stranger the operator revoked does not get UPDATE on sq297_n_seq back, and the app keeps the UPDATE it was given');

-- ================= (C) a sequence at the owner's implicit default =================
select ok((select relacl is null from pg_class where oid = 'public.nl297_id_seq'::regclass),
  'C LIVENESS: nl297_id_seq, created before the default privileges, has the NULL ACL');
call pgpm.transmute('public.nl297', 'id', 100::bigint, p_obtain => 2);
select ok((select relkind::text from pg_class where oid = 'public.nl297'::regclass) = 'p'
          and pg_temp.seq297('public.nl297', 'id')::text = 'nl297_id_seq',
  'C LIVENESS: nl297 was converted, its sequence under the original''s name');
select is(pg_temp.acl297('public.nl297_id_seq'), array['postgres:SELECT/postgres', 'postgres:UPDATE/postgres', 'postgres:USAGE/postgres'],
  'C: the parent''s nl297_id_seq holds the owner''s privileges and nothing the default privileges gave the stranger');
select is(pgpm.untransmute('public.nl297')::text, 'nl297', 'C LIVENESS: untransmute restored nl297');
select is(pg_temp.acl297('public.nl297_id_seq'), array['postgres:SELECT/postgres', 'postgres:UPDATE/postgres', 'postgres:USAGE/postgres'],
  'C: and so does the restored one');

-- ================= (D) a grant on the sequence the session cannot replay =================
create table public.gd297 (id bigint generated always as identity primary key, v text);
insert into public.gd297 (v) values ('x'), ('y'), ('z'), ('w');
alter table public.gd297 owner to t297_owner;
do $$ begin
  set local role t297_owner;
  grant usage on sequence public.gd297_id_seq to t297_bob with grant option;
  set local role t297_bob;
  grant usage on sequence public.gd297_id_seq to t297_carol;
  reset role;
end $$;
create temp table before297d as select pg_temp.acl297('public.gd297_id_seq') as acl;
select ok((select acl from before297d) @> array['t297_carol:USAGE/t297_bob']
          and not pg_has_role('t297_owner', 't297_bob', 'member')
          and (select relacl is null from pg_class where oid = 'public.gd297'::regclass),
  'D LIVENESS: gd297''s table carries no grant, its sequence carries carol''s from bob, and t297_owner is no member of bob');
set session authorization t297_owner;
select throws_like(
  $$ call pgpm.transmute('public.gd297', 'id', 100::bigint, p_obtain => 2) $$,
  'pg_partition_magician: cannot transmute gd297 as t297_owner -- grants on it were made by t297_bob through a grant option,%',
  'D: transmute refuses up front, naming bob, whose grant is on the identity sequence');
reset session authorization;
select is((select relkind::text || ' ' || (select string_agg(id::text, ',' order by id) from public.gd297)
                  || ' ' || exists (select 1 from pgpm.transmute_inflight where parent_table = 'public.gd297'::regclass)::text
                  || ' ' || exists (select 1 from pg_constraint where conrelid = 'public.gd297'::regclass and conname = 'pgpm_monolith_bound')::text
             from pg_class where oid = 'public.gd297'::regclass),
  'r 1,2,3,4 false false',
  'D: the table is left as it was, a plain table holding rows 1 to 4, with no claim and no bound');
grant t297_bob to t297_owner;
set session authorization t297_owner;
call pgpm.transmute('public.gd297', 'id', 100::bigint, p_obtain => 2);
reset session authorization;
select is((select relkind::text from pg_class where oid = 'public.gd297'::regclass), 'p',
  'D LIVENESS: as a member of bob the same session converts gd297');
select is(pg_temp.acl297('public.gd297_id_seq'), (select acl from before297d),
  'D: and the parent''s gd297_id_seq holds exactly the original''s grants, carol''s under bob');
revoke t297_bob from t297_owner;

select * from finish();

-- Roles are cluster-wide: take this file's out again, with what they hold in this database.
alter default privileges in schema public revoke all on sequences from t297_stranger;
reassign owned by t297_owner to postgres;
drop owned by t297_app, t297_stranger, t297_bob, t297_carol, t297_owner;
do $$
declare r text;
begin
  foreach r in array array['t297_app', 't297_stranger', 't297_carol', 't297_bob', 't297_owner'] loop
    begin
      execute format('drop role if exists %I', r);
    exception when dependent_objects_still_exist then
      raise notice 'role % still holds privileges elsewhere in the cluster, left in place', r;
    end;
  end loop;
end $$;
