-- regrain() splits a frozen coarse child (the monolith) into finer children by COPYING rows into
-- standalone children and swapping them in atomically, then DROPPING the vestigial source -- no DELETE,
-- so no dead tuples or bloat (REDESIGN.md section 10). It refuses while the child is still active.
create extension if not exists pgtap;
select plan(9);

-- a table whose history spans 5 grid steps: 50000 ids over a step of 10000, so the monolith covers
-- [0, 60000) (grid_floor(min=1)=0 up to B = grid boundary above max=50000, i.e. 60000) -- a coarse child.
create table public.rf (id bigint generated by default as identity primary key, payload text);
insert into public.rf (payload) select 'p' || g from generate_series(1, 50000) g;
-- Identity, not cardinality (#997): every row carries its own payload, and the rows are snapshotted
-- before the transmute, so a copy that rewrites a value while keeping every count is caught below.
create temporary table _rf_before as select id, payload from public.rf;
call pgpm.transmute('public.rf', 'id', 10000);   -- registers paused; monolith [0, 60000)
select pgpm.obtain('public.rf');                    -- empty forward partitions from B = 60000

select is(
  (select count(*)::int from pgpm.part p where p.parent_table = 'public.rf'::regclass and p.attached
     and pgpm._native_gt('id', p.hi, pgpm._grid_next('id', '10000', p.lo, 'UTC'))),
  1, 'transmute left exactly one coarse monolith child');

-- still active (the frontier has not crossed B): regrain refuses.
select throws_ok(
  $$ select pgpm.regrain_history('public.rf') $$,
  'P0001', NULL, 'regrain refuses while the monolith is still active (not frozen)');

-- advance the frontier past B = 60000 (a write into a forward partition), freezing the monolith.
insert into public.rf (id, payload) values (65000, 'frontier');

select is(
  (select pgpm.regrain_history('public.rf'))::int,
  6, 'regrain split the monolith into 6 fine children');

select is(
  (select count(*)::int from pgpm.part p where p.parent_table = 'public.rf'::regclass and p.attached
     and p.lo::numeric >= 0 and p.hi::numeric <= 60000
     and not pgpm._native_gt('id', p.hi, pgpm._grid_next('id', '10000', p.lo, 'UTC'))),
  6, 'six fine (one-step) children now cover the old monolith range');

select ok(
  to_regclass('public.rf_p' || lpad('0', 19, '0')) is not null,
  'the first fine child rf_p0 exists (attached)');

select ok(
  to_regclass('public.rf_p' || lpad('0', 19, '0') || '_to_' || lpad('60000', 19, '0')) is null,
  'the coarse monolith table is gone (dropped, never deleted-from)');

select is(
  (select count(*)::int from public.rf),
  50001, 'all rows conserved across the regrain (50000 history + 1 frontier row)');

select bag_eq(
  'select id, payload from public.rf',
  $$ select id, payload from _rf_before union all select 65000::bigint, 'frontier' $$,
  'every row survives the regrain by identity: the same (id, payload) rows, none lost, none added, none altered');

select is(
  (select count(*)::int from public.rf where id < 60000),
  50000, 'the 50000 original rows are all present in the regrained [0, 60000) range');

select * from finish();
