-- regrain() copies each sub-range in budget-sized microbatches (drain_batch, capped by drain_max_blocks),
-- not one statement per sub-range, so a wide sub-range can't become one giant copy. The whole call is one
-- transaction here (atomic, gap-free); the microbatching bounds per-statement footprint and reuses the
-- drain's budget so a maintain-driven auto-regrain can pace it across ticks. Each microbatch logs regrain_copy.
create extension if not exists pgtap;
select plan(5);

create table public.fw (id bigint generated by default as identity primary key, payload text);
insert into public.fw (payload) select 'p' || g from generate_series(1, 120) g;   -- ids 1..120
-- Identity, not cardinality (#997): distinct payloads, snapshotted before the transmute.
create temporary table _fw_before as select id, payload from public.fw;
call pgpm.transmute('public.fw', 'id', 50, p_regrain_batch => 10);   -- monolith [0, 150) -- 3 steps; batch 10
select pgpm.obtain('public.fw');
insert into public.fw (id, payload) values (1000, 'frontier');   -- advance frontier -> monolith frozen

select is(
  (select pgpm.regrain_history('public.fw'))::int,
  3, 'regrain splits the monolith into 3 fine children');

select cmp_ok(
  (select max(rows) from pgpm.log where parent_table = 'public.fw'::regclass and action = 'regrain_copy'),
  '<=', 10::bigint, 'every regrain microbatch is bounded by drain_batch (10 rows)');

select cmp_ok(
  (select count(*) from pgpm.log where parent_table = 'public.fw'::regclass and action = 'regrain_copy'),
  '>=', 12::bigint, 'the copy is microbatched (many bounded copies, not one statement per sub-range)');

select is(
  (select count(*)::int from public.fw where id < 150),
  120, 'all 120 rows conserved across the feathered regrain');

select bag_eq(
  'select id, payload from public.fw where id < 150',
  'select id, payload from _fw_before',
  'every history row survives the feathered regrain by identity: none lost, none added, none altered');

select * from finish();
