-- Auto-regrain maintain policy (REDESIGN.md section 12). With set_regrain() on, each maintain tick feathers
-- the oldest frozen coarse child one budget-sized microbatch toward the target step -- true cross-tick
-- pacing under the live workload, the way the drain is paced. Off by default. regrain_step enforces its own
-- preconditions (frozen, default-clear), so a tick that can't make progress just retries next tick.
create extension if not exists pgtap;
select plan(7);

create table public.ar (id bigint generated by default as identity primary key, payload text);
insert into public.ar (payload) select 'p' || g from generate_series(1, 200) g;   -- ids 1..200
-- Identity, not cardinality (#997): distinct payloads, snapshotted before the transmute.
create temporary table _ar_before as select id, payload from public.ar;
call pgpm.transmute('public.ar', 'id', 50, p_regrain_batch => 30, p_paused => false);   -- monolith [0, 250) -- 5 steps; batch 30
select pgpm.obtain('public.ar');
insert into public.ar (id, payload) values (1000, 'frontier');   -- advance frontier past B=250 -> monolith frozen
select pgpm.set_regrain('public.ar', '50');                        -- enable auto-regrain to step 50

select is(
  (select coarse_partitions from pgpm.status() where parent = 'public.ar'::regclass),
  1::bigint, 'a coarse monolith awaits regraining before any tick');

-- maintain ticks make PARTIAL progress (one microbatch each), not the whole regrain in a single tick.
-- The FIRST tick installs change capture and returns 'prepared' without copying (#267): CREATE TRIGGER
-- takes SHARE ROW EXCLUSIVE, and giving it its own tick keeps that hold O(1) instead of spanning a copy
-- batch. So the first copy microbatch lands on the second tick.
call pgpm.maintain('public.ar');
call pgpm.maintain('public.ar');
select cmp_ok(
  (select count(*) from pgpm.log where parent_table = 'public.ar'::regclass and action = 'regrain_copy'),
  '>', 0::bigint, 'maintain ticks feather regrain copy microbatches (cross-tick pacing)');
select is(
  (select coarse_partitions from pgpm.status() where parent = 'public.ar'::regclass),
  1::bigint, 'after a single tick the coarse child is still mid-regrain (not finished in one tick)');

-- drive ticks to completion
do $$ declare v_status text; begin for i in 1..40 loop call pgpm.maintain('public.ar', v_status); end loop; end $$;

select is(
  (select coarse_partitions from pgpm.status() where parent = 'public.ar'::regclass),
  0::bigint, 'repeated maintain ticks complete the regrain (no coarse partitions remain)');

select is(
  (select count(*)::int from public.ar where id < 250),
  200, 'all 200 history rows conserved across the feathered cross-tick regrain');

select bag_eq(
  'select id, payload from public.ar where id < 250',
  'select id, payload from _ar_before',
  'every history row survives the cross-tick regrain by identity: none lost, none added, none altered');

select cmp_ok(
  (select count(*) from pgpm.log where parent_table = 'public.ar'::regclass and action = 'regrain_copy'),
  '>=', 5::bigint, 'the regrain was paced across many copy microbatches, not one statement');

select * from finish();
