-- The copy contract (REDESIGN.md sections 9 and 10): regrain COPIES, it never moves. While a feathered
-- (cross-tick) regrain is mid-flight, the source monolith still holds every row and stays attached, so:
--   (1) a plain read of the parent is NEVER short (no undercount),
--   (2) the source is never deleted from (no dead tuples, no bloat),
--   (3) snapshot() does not union the in-flight copies (they would double-count rows still in the source).
-- These three assertions encode exactly what the move-model implementation got wrong. regrain never logs a
-- 'regrain_move' (the delete-and-move action); it logs 'regrain_copy'.
create extension if not exists pgtap;
select plan(9);

create table public.cc (id bigint generated by default as identity primary key, payload text);
insert into public.cc (payload) select 'p' || g from generate_series(1, 300) g;   -- history ids 1..300
-- Identity, not cardinality (#997): distinct payloads, snapshotted before the transmute.
create temporary table _cc_before as select id, payload from public.cc;
call pgpm.transmute('public.cc', 'id', 50, p_regrain_batch => 20, p_paused => false);  -- monolith [0,B); batch 20
select pgpm.obtain('public.cc');
insert into public.cc (id, payload) values (1000, 'frontier');   -- advance frontier past B -> monolith frozen
select pgpm.set_regrain('public.cc', '50');                        -- enable feathered auto-regrain to step 50

-- Two maintain ticks: the first installs change capture and returns 'prepared' without copying (#267 --
-- CREATE TRIGGER takes SHARE ROW EXCLUSIVE, so it gets its own tick to keep that hold O(1)), the second
-- does a partial COPY of one budget microbatch. The regrain is NOT finished and copies are in flight.
call pgpm.maintain('public.cc');
call pgpm.maintain('public.cc');

select is(
  (select coarse_partitions from pgpm.status() where parent = 'public.cc'::regclass),
  1::bigint, 'mid-regrain: the coarse monolith is still present (one tick does not finish the regrain)');

select cmp_ok(
  (select count(*) from pgpm.log where parent_table = 'public.cc'::regclass and action = 'regrain_copy'),
  '>', 0::bigint, 'mid-regrain: at least one copy microbatch has run (action regrain_copy)');

select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.cc'::regclass and action = 'regrain_move'),
  0, 'regrain never logs a move: it copies, it does not delete-and-move');

-- (1) NO UNDERCOUNT: every history row is still visible through the parent mid-regrain
select is(
  (select count(*)::int from public.cc where id <= 300),
  300, 'mid-regrain: a plain read of the parent returns all 300 history rows (no undercount)');

-- (2) NO DELETES: the source monolith table still holds all 300 history rows mid-regrain
create temporary table _moncnt (n int);
do $$
declare v_rel text; v_n int;
begin
  select quote_ident(n.nspname) || '.' || quote_ident(p.child_name) into v_rel
    from pgpm.part p
    join pg_class c on c.oid = p.parent_table
    join pg_namespace n on n.oid = c.relnamespace
   where p.parent_table = 'public.cc'::regclass and p.attached
     and pgpm._native_gt('id', p.hi, pgpm._grid_next('id', '50', p.lo, 'UTC'));   -- the coarse monolith
  execute 'select count(*) from ' || v_rel into v_n;
  insert into _moncnt values (v_n);
end $$;
select is((select n from _moncnt), 300, 'mid-regrain: the monolith source still holds all 300 rows (never deleted from)');

-- (3) NO DOUBLE-COUNT: snapshot() does not union the in-flight copies (their rows are still in the source)
select is(
  (select count(*)::int from public.cc where id <= 300),
  300, 'mid-regrain: snapshot() returns 300 history rows, not 300 + the in-flight copies');

-- drive the regrain to completion across ticks
do $$ declare v_status text; begin for i in 1..60 loop call pgpm.maintain('public.cc', v_status); end loop; end $$;

select is(
  (select coarse_partitions from pgpm.status() where parent = 'public.cc'::regclass),
  0::bigint, 'the regrain completes across ticks (no coarse partition remains)');

select is(
  (select count(*)::int from public.cc where id <= 300),
  300, 'all 300 history rows conserved across the feathered copy-regrain');

select bag_eq(
  'select id, payload from public.cc where id <= 300',
  'select id, payload from _cc_before',
  'every history row survives the feathered copy-regrain by identity: none lost, none added, none altered');

select * from finish();
