-- Retention against a table with an INCOMING foreign key (issue #268).
--
-- THE BUG. `p_incoming_fks => 'preserve'` and a `retain` policy were both supported and both
-- documented, and the combination never reclaimed anything. `DROP TABLE <partition>` is refused on a
-- pure CATALOG dependency -- an FK against a partitioned parent puts one pg_constraint row per
-- referenced partition ON the referencing table -- and the refusal is data-INDEPENDENT: identical
-- whether one row references, zero rows reference, or the referencing table is empty. So every
-- retain() call failed on the oldest eligible partition and returned 0, forever, while retire() had
-- ALREADY installed the write block. The partition ended up frozen AND unreclaimable: no writes in,
-- no storage back.
--
-- THE FIX is detach-then-drop. A successful DETACH severs the per-partition child constraint, after
-- which the DROP is completely unguarded. The referencing table's own FK survives and still enforces.
--
-- WHY RETIREMENT IS NOW ASYNCHRONOUS. The detach must be `CONCURRENTLY`: plain DETACH holds ACCESS
-- EXCLUSIVE on the MANAGED PARENT for the whole O(referencing table) scan, and a concurrent read of
-- the parent dies with 55P03 -- retention would block the table pgpm exists to keep online, for a
-- duration set by a table pgpm does not own. But `DETACH CONCURRENTLY` cannot run from a function or
-- a DO block or dynamic EXECUTE ("cannot be executed from a function"), and pgpm is pure SQL. So pgpm
-- DISPATCHES it: retire() repoints a standing pg_cron job at the specific detach, and completes the
-- DROP on a later tick. That contract lives in tests/78 (it needs pg_cron, which exists only in the
-- `postgres` database on these images). Here the detach is performed by hand at the top level,
-- exactly as cron would, so the rest of the state machine can be tested in a per-file database.
--
-- THE CROSSING. A live row genuinely referencing a doomed row is the one case where the operator's
-- two promises (the FK and the retention horizon) contradict. pgpm has NO policy decision to make:
-- the operator already chose in the FK's `ON DELETE` clause. `DELETE FROM <parent> WHERE <crossing
-- keys>` honours all five referential actions with no branching -- CASCADE clears the referencing
-- rows, SET NULL/SET DEFAULT sever them in place, NO ACTION/RESTRICT refuse the delete and block
-- retention with the operator's OWN error. That is asserted below for both ends of that range.
--
-- NOTE: `ALTER TABLE ... DETACH PARTITION ... CONCURRENTLY` cannot run inside a transaction block
-- at all (a PostgreSQL restriction, not just this suite's own convention), and the reaper section
-- needs a second session (dblink) to see committed state.
create extension if not exists pgtap;
create extension if not exists dblink;

select plan(50);

-- ============================ fixture 1: an incoming FK, no crossing ============================
-- 50000 rows -> monolith [0,60000); the frontier write at 110000 puts the horizon at 80000, so the
-- monolith is entirely past it and eligible. The referencing row points at 110000, a LIVE row, so
-- nothing references the doomed partition: this is the common case the wedge broke.
create table public.rw77 (id bigint generated by default as identity primary key, payload text);
insert into public.rw77 (payload) select 'x' from generate_series(1, 50000);
call pgpm.transmute('public.rw77', 'id', 10000, p_retain => 30000);
select pgpm.obtain('public.rw77');
insert into public.rw77 (id, payload) values (110000, 'frontier');

create table public.ref77 (id bigint primary key, p_id bigint not null references public.rw77(id));
insert into public.ref77 values (1, 110000);

-- child names captured up front, so assertions can still name the partition after it is gone
create schema pgpm_test77;
create table pgpm_test77.names as
  select lo, child_name from pgpm.part where parent_table = 'public.rw77'::regclass;

select child_name as doomed from pgpm_test77.names where lo = '0' \gset
-- and its oid, before anything touches it: "still attached" below is judged on THIS relation, not on
-- whatever holds the name by then
select format('public.%I', :'doomed')::regclass::oid as doomed_oid \gset

-- LIVENESS WITNESSES. Both negatives below ("retire did not drop it yet", "nothing was destroyed")
-- are satisfied by a run where retirement was never eligible at all, so pin the conditions first.
select cmp_ok(
  (select retain_backlog from pgpm.status() where parent = 'public.rw77'::regclass),
  '>=', 1::bigint,
  'LIVENESS: the doomed partition is genuinely eligible for retirement');

select cmp_ok(
  (select count(*) from pg_constraint
    where confrelid = format('public.%I', :'doomed')::regclass and contype = 'f'),
  '>=', 1::bigint,
  'LIVENESS: a per-partition FK constraint depends on it -- this is what refuses the bare DROP');

-- ============================ retirement is dispatched, not done inline ============================
select ok(not pgpm.retire('public.rw77', :'doomed'),
  'retire() does not drop a referenced partition inline: the detach it needs cannot run in-process');

select is(
  (select (retiring_at is not null) from pgpm.part
    where parent_table = 'public.rw77'::regclass and child_name = :'doomed'),
  true, 'it marks the partition retiring_at instead, so recovery never has to guess whose detach it is');

-- ONE AT A TIME. There is a single standing cron job, so a second dispatch would overwrite the first
-- and abandon it. retain()'s batch loop walks EVERY eligible partition (there are three here) and
-- maintain_all walks every managed parent, so without a guard one call marks the whole backlog as
-- retiring while only the last dispatch is real. This is a liveness-shaped trap in its own right: the
-- partitions still get retired eventually, one per tick, so only counting the marker catches it.
select cmp_ok(
  (select retain_backlog from pgpm.status() where parent = 'public.rw77'::regclass),
  '>', 1::bigint, 'LIVENESS: more than one partition is eligible, so the batch loop has a choice to make');

select pgpm.retain('public.rw77');
select is(
  (select count(*)::int from pgpm.part
    where parent_table = 'public.rw77'::regclass and retiring_at is not null),
  1, 'only ONE retirement is ever in flight: the single standing job cannot carry two detaches');

-- Nothing may be destroyed on the way. Identity, not cardinality: name the partition and its rows
-- (#1002). Attachment alone reads no row, so it would pass a retire() that emptied the partition when it
-- dispatched the detach. Rows are read THROUGH the parent, from that partition: ids 1, 25000 and 50000
-- by name, then every one of 1..50000.
select ok(exists (select 1 from pg_inherits where inhparent = 'public.rw77'::regclass
                   and inhrelid = :'doomed_oid'::oid and not inhdetachpending),
  'the partition is still attached, the same relation by oid and not detach-pending');
select is(
  (select array_agg(id order by id) from public.rw77
    where tableoid = to_regclass(format('public.%I', :'doomed')) and id in (1, 25000, 50000)),
  array[1, 25000, 50000]::bigint[],
  'the partition still holds its rows (ids 1, 25000 and 50000), until the detach actually happens');
select ok(
  (select array_agg(id order by id) from public.rw77 where tableoid = :'doomed_oid'::oid)
    = (select array_agg(g::bigint order by g) from generate_series(1, 50000) g),
  'and every one of them: exactly ids 1 to 50000, none lost, none invented');

-- ============================ the detach, exactly as cron performs it ============================
-- Top level, because that is the only context PostgreSQL permits it in -- \gexec rather than a literal
-- name so a change to the naming scheme fails here loudly instead of detaching nothing. tests/78
-- asserts pgpm asks cron for precisely this statement.
select format('alter table public.rw77 detach partition public.%I concurrently', :'doomed') \gexec

select is(
  (select count(*)::int from pg_constraint
    where confrelid = format('public.%I', :'doomed')::regclass and contype = 'f'),
  0, 'a successful DETACH severs the per-partition constraint, leaving the DROP unguarded');

-- ============================ and retire() completes the drop ============================
select ok(pgpm.retire('public.rw77', :'doomed'),
  'retire() returns true on the tick that finds it detached and drops it');

select is((select to_regclass(format('public.%I', :'doomed'))::text), NULL,
  'the specific partition is gone from the catalog');

select is(
  (select count(*)::int from pgpm.part
    where parent_table = 'public.rw77'::regclass and child_name = :'doomed'),
  0, 'and so is its pgpm.part row');

select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.rw77'::regclass and action = 'retain_drop'
      and lo = '0'),
  1, 'logged as exactly retain_drop -- the reclaim, not a deferral');

-- ============================ the FK still ENFORCES afterwards ============================
-- Behavioural on purpose. A structural "the constraint row is still there" check would pass against a
-- fix that severed RI to force the drop through, which is precisely the trap PostgreSQL's own
-- `HINT: Use DROP ... CASCADE` sets: that drops the CONSTRAINT and keeps the data, silently removing
-- referential integrity across the whole referencing table.
select throws_ok(
  $$ insert into public.ref77 values (999, 987654321) $$,
  '23503', NULL,
  'the referencing table''s FK survived the reclaim and still rejects an orphan');

select lives_ok(
  $$ insert into public.ref77 values (998, 110000) $$,
  'and still accepts a valid reference: it enforces, rather than being merely present');

-- ============================ no incoming FK: the path is untouched ============================
-- The common case must pay nothing at all -- no marker, no dispatch, no asynchrony.
create table public.nf77 (id bigint generated by default as identity primary key, payload text);
insert into public.nf77 (payload) select 'x' from generate_series(1, 50000);
call pgpm.transmute('public.nf77', 'id', 10000, p_retain => 30000);
select pgpm.obtain('public.nf77');
insert into public.nf77 (id, payload) values (110000, 'frontier');
select child_name as nf_doomed from pgpm.part
  where parent_table = 'public.nf77'::regclass and lo = '0' \gset

select ok(pgpm.retire('public.nf77', :'nf_doomed'),
  'with no incoming FK, retire() still drops on the FIRST call: a bare DROP, exactly as before');

select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.nf77'::regclass and action = 'retain_detach'),
  0, 'and dispatches no detach at all -- the unreferenced path is unchanged');

-- ============================ the crossing, ON DELETE CASCADE ============================
-- The operator declared what happens to a referencing row when the referenced row goes. pgpm executes
-- that declaration; it does not invent a policy.
create table public.cx77 (id bigint generated by default as identity primary key, payload text);
insert into public.cx77 (payload) select 'x' from generate_series(1, 50000);
call pgpm.transmute('public.cx77', 'id', 10000, p_retain => 30000);
select pgpm.obtain('public.cx77');
insert into public.cx77 (id, payload) values (110000, 'frontier');
create table public.cxref77 (id bigint primary key, p_id bigint not null
  references public.cx77(id) on delete cascade);
-- ASYMMETRIC fixture (2 in, 1 out): a crossing row pointing INTO the doomed partition, and a live row
-- that must survive. A compensating error cannot cancel out and leave the count right.
insert into public.cxref77 values (1, 42), (2, 110000);
select child_name as cx_doomed from pgpm.part
  where parent_table = 'public.cx77'::regclass and lo = '0' \gset

select ok(not pgpm.retire('public.cx77', :'cx_doomed'),
  'a crossing under ON DELETE CASCADE does not block retirement');

select is((select count(*)::int from public.cxref77 where id = 1), 0,
  'the CROSSING referencing row is gone: PostgreSQL applied the declared CASCADE');

select is((select count(*)::int from public.cxref77 where id = 2), 1,
  'and the non-crossing row is untouched -- the work is bounded by the crossing');

-- Carry this retirement through to the drop. Partly to prove the crossing was RESOLVED rather than
-- merely deferred, and partly because retire() dispatches at most one detach database-wide: a fixture
-- left mid-retirement would correctly short-circuit the next section before it reached the crossing.
select format('alter table public.cx77 detach partition public.%I concurrently', :'cx_doomed') \gexec
select ok(pgpm.retire('public.cx77', :'cx_doomed'),
  'and the retirement then completes, so the crossing was resolved and not just postponed');

-- ============================ the crossing, ON DELETE NO ACTION ============================
-- The same mechanism, the opposite declared outcome. Retention is refused, and it must be refused
-- LOUDLY and cleanly: PostgreSQL's own error, and a partition left whole rather than half-retired.
create table public.nx77 (id bigint generated by default as identity primary key, payload text);
insert into public.nx77 (payload) select 'x' from generate_series(1, 50000);
call pgpm.transmute('public.nx77', 'id', 10000, p_retain => 30000);
select pgpm.obtain('public.nx77');
insert into public.nx77 (id, payload) values (110000, 'frontier');
create table public.nxref77 (id bigint primary key, p_id bigint not null
  references public.nx77(id));   -- bare REFERENCES = ON DELETE NO ACTION
insert into public.nxref77 values (1, 42);
select child_name as nx_doomed from pgpm.part
  where parent_table = 'public.nx77'::regclass and lo = '0' \gset
select format('public.%I', :'nx_doomed')::regclass::oid as nx_doomed_oid \gset

select ok(not pgpm.retire('public.nx77', :'nx_doomed'),
  'a crossing under NO ACTION blocks retirement, which is what the operator asked for');

select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.nx77'::regclass and action = 'fail_retain_crossing'),
  1, 'refused as exactly fail_retain_crossing, distinct from a generic drop failure');

-- INTACT is about its rows, not only its attachment (#1002): a refused retire() that had already deleted
-- the rows nothing references would leave it attached and half-retired. Ids 1, 42 (the referenced one),
-- 25000 and 50000 by name, then every one of 1..50000.
select ok(exists (select 1 from pg_inherits where inhparent = 'public.nx77'::regclass
                   and inhrelid = :'nx_doomed_oid'::oid and not inhdetachpending),
  'and the partition is left attached, the same relation by oid and not detach-pending');
select is(
  (select array_agg(id order by id) from public.nx77
    where tableoid = to_regclass(format('public.%I', :'nx_doomed')) and id in (1, 42, 25000, 50000)),
  array[1, 42, 25000, 50000]::bigint[],
  'and the partition is left INTACT and attached, not half-retired: ids 1, 42, 25000 and 50000 are there');
select ok(
  (select array_agg(id order by id) from public.nx77 where tableoid = :'nx_doomed_oid'::oid)
    = (select array_agg(g::bigint order by g) from generate_series(1, 50000) g),
  'and every one of its rows: exactly ids 1 to 50000, none lost, none invented');

select is((select count(*)::int from public.nxref77 where id = 1), 1,
  'the referencing row is untouched: a refused DELETE severs nothing');

-- ============================ the reaper: an interrupted concurrent detach ============================
-- Killing a backend during the detach's WAIT phase leaves the partition pending AND its rows already
-- invisible through the parent -- neither detached nor dropped. That is strictly worse than the wedge
-- this issue is about: rows vanish from the user's table. FINALIZE completes it.
create table public.rp77 (id bigint generated by default as identity primary key, payload text);
insert into public.rp77 (payload) select 'x' from generate_series(1, 50000);
call pgpm.transmute('public.rp77', 'id', 10000, p_retain => 30000);
select pgpm.obtain('public.rp77');
insert into public.rp77 (id, payload) values (110000, 'frontier');
select child_name as rp_doomed from pgpm.part
  where parent_table = 'public.rp77'::regclass and lo = '0' \gset

-- A REPEATABLE READ holder pins one snapshot for its whole transaction, so the detach parks in its
-- wait phase deterministically -- no sleep, no timing race.
select dblink_connect('holder', 'dbname=' || current_database());
select dblink_exec('holder', 'begin isolation level repeatable read');
select * from dblink('holder', 'select count(*) from public.rp77') as t(c bigint);

select dblink_connect('det', 'dbname=' || current_database());
select * from dblink('det', 'select pg_backend_pid()') as t(pid int) \gset
select dblink_send_query('det',
  format('alter table public.rp77 detach partition public.%I concurrently', :'rp_doomed'));

-- inhdetachpending is set and COMMITTED by the detach's first transaction, before it starts waiting,
-- so polling on it is exact rather than a guess about how long the scan takes.
do $$
begin
  for i in 1 .. 600 loop
    exit when exists (select 1 from pg_inherits i join pg_class c on c.oid = i.inhrelid
                       where i.inhparent = 'public.rp77'::regclass and i.inhdetachpending);
    perform pg_sleep(0.05);
  end loop;
end $$;

select pg_terminate_backend(:pid);

-- LIVENESS WITNESS for the reaper: the hazard must actually be present, or "the reaper cleared it"
-- would pass against a run where there was never anything to clear.
select is(
  (select count(*)::int from pg_inherits
    where inhparent = 'public.rp77'::regclass and inhdetachpending),
  1, 'LIVENESS: the interrupted detach really did leave the partition pending');

select cmp_ok((select count(*) from public.rp77), '<', 50001::bigint,
  'LIVENESS: and its rows are ALREADY invisible through the parent -- the hazard is real');

-- The holder has served its purpose (it existed only to park the detach in its wait phase). It must go
-- BEFORE the reap: FINALIZE takes ACCESS EXCLUSIVE on the partition, which the holder's ACCESS SHARE
-- from the scan above conflicts with, so leaving it open deadlocks the thing under test against the
-- instrument measuring it.
select dblink_disconnect('holder');
select dblink_disconnect('det');

select cmp_ok(pgpm._detach_reap(), '>=', 1, '_detach_reap() finalizes the abandoned detach');

select is(
  (select count(*)::int from pg_inherits
    where inhparent = 'public.rp77'::regclass and inhdetachpending),
  0, 'and the parent no longer carries a pending detach');

-- pgpm did not start this retirement (no retiring_at), so the reaper finalizes and leaves it alone
-- rather than dropping a table it was not handed.
select isnt((select to_regclass(format('public.%I', :'rp_doomed'))::text), NULL,
  'a detach pgpm did not start is finalized but NOT dropped');

-- ================= the dispatch gap: a NAME stops meaning what it meant (issue #407) =================
-- Dispatching is the whole mechanism above, and it is also a time-of-check/time-of-use hole. The
-- command that leaves retire() is TEXT -- `alter table public.sb77 detach partition public.<child>
-- concurrently` -- and it sits on cron.job until pg_cron's scheduler runs it, later, in a session of
-- its own, holding no lock on the child in the meantime. A command text cannot carry an OID, so the
-- cron session re-resolves that name and has no way to notice it now answers to a different relation.
-- Same shape as the ALTER TABLE ... SPLIT/MERGE PARTITION bug the #346 audit went looking for.
--
-- pgpm cannot close the window (the reason the statement is dispatched at all is that PostgreSQL
-- refuses to let pgpm hold anything while it runs), so it anchors the retirement to the child's OID
-- in pgpm.part.retiring_oid and refuses to act when the name stops resolving to it. Two refusals are
-- exercised below, because a retirement passes through this function twice: once more while the
-- child is still attached (do not re-point the job at the substitute) and once after the detach has
-- landed (do not DROP the substitute). The second is the one that matters -- pre-fix, it returned
-- true and destroyed a table pgpm was never handed.
create table public.sb77 (id bigint generated by default as identity primary key, payload text);
insert into public.sb77 (payload) select 'x' from generate_series(1, 50000);
call pgpm.transmute('public.sb77', 'id', 10000, p_retain => 30000);
select pgpm.obtain('public.sb77');
insert into public.sb77 (id, payload) values (110000, 'frontier');
create table public.sbref77 (id bigint primary key, p_id bigint not null references public.sb77(id));
insert into public.sbref77 values (1, 110000);
select child_name as sb_doomed from pgpm.part
  where parent_table = 'public.sb77'::regclass and lo = '0' \gset
select format('public.%I', :'sb_doomed')::regclass::oid as sb_real \gset

select ok(not pgpm.retire('public.sb77', :'sb_doomed'),
  'retire() dispatches the detach for the referenced partition, as above');

-- LIVENESS. Every refusal below is "pgpm did NOT act on the substitute", which a run that never
-- recorded an identity in the first place satisfies just as well. Pin the anchor before disturbing it.
select is(
  (select retiring_oid from pgpm.part
    where parent_table = 'public.sb77'::regclass and child_name = :'sb_doomed'),
  :'sb_real'::oid,
  'LIVENESS: the dispatch recorded WHICH object it meant, by oid -- not merely that one was in flight');

-- THE SUBSTITUTION, in the only shape that matters: the impostor is a genuine partition of the same
-- parent under the same name, so the armed command detaches it without complaint. Anything less and
-- the detach fails loudly with `is not a partition of` and there is nothing to defend against. The
-- object pgpm meant is renamed aside rather than dropped, so "it was not destroyed" is checkable.
select format('alter table public.sb77 detach partition public.%I', :'sb_doomed') \gexec
select format('alter table public.%I rename to sb77_kept', :'sb_doomed') \gexec
select format('create table public.%I (like public.sb77)', :'sb_doomed') \gexec
select format('alter table public.sb77 attach partition public.%I for values from (0) to (60000)',
              :'sb_doomed') \gexec
select format('public.%I', :'sb_doomed')::regclass::oid as sb_impostor \gset

select isnt(:'sb_impostor'::oid, :'sb_real'::oid,
  'LIVENESS: the name now answers to a DIFFERENT relation than the detach was dispatched for');
select is((select to_regclass('public.sb77_kept')::oid), :'sb_real'::oid,
  'LIVENESS: and the one it did mean is still here, moved aside, so a wrong drop would be visible');
select is(
  (select count(*)::int from pg_inherits i join pg_class c on c.oid = i.inhrelid
    where i.inhparent = 'public.sb77'::regclass and c.oid = :'sb_impostor'::oid),
  1, 'LIVENESS: the impostor really is attached to the same parent -- the detach would succeed on it');

-- REFUSAL 1, while the impostor is still attached: do not re-point the standing job at it.
select ok(not pgpm.retire('public.sb77', :'sb_doomed'),
  'retire() refuses to carry the retirement on against a name that no longer resolves to its object');

select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.sb77'::regclass and action = 'fail_retain_identity'),
  1, 'refused as exactly fail_retain_identity, distinct from a crossing or a drop failure');

select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.sb77'::regclass
    and action in ('retain_detach', 'fail_retain_detach')),
  1, 'and dispatched nothing further: only the ORIGINAL dispatch is in the log');

select is(
  (select count(*)::int from pg_inherits i join pg_class c on c.oid = i.inhrelid
    where i.inhparent = 'public.sb77'::regclass and c.oid = :'sb_impostor'::oid),
  1, 'the impostor is left attached and whole: refusing means touching nothing, not tidying up');

-- REFUSAL 2, the one that matters. The armed command fires on its own schedule whatever pgpm decided
-- a moment ago, so run it exactly as cron would -- and it succeeds, because the impostor IS a
-- partition of this parent. retire() now meets the state it completes a retirement from.
select format('alter table public.sb77 detach partition public.%I concurrently', :'sb_doomed') \gexec

select ok(not pgpm.retire('public.sb77', :'sb_doomed'),
  'and refuses the DROP that normally follows a detach: pre-fix this returned true and dropped it');

-- to_regclass, not a ::regclass cast: a run in which the substitute WAS dropped must report a failed
-- assertion naming what happened, not die on an unresolvable name and take the rest of the file with it.
select is((select to_regclass(format('public.%I', :'sb_doomed'))::oid), :'sb_impostor'::oid,
  'the substitute is untouched -- the same relation, not merely a relation of that name');
select is((select to_regclass('public.sb77_kept')::oid), :'sb_real'::oid,
  'and so is the object pgpm did mean: refusing is not re-guessing');

select is(
  (select count(*)::int from pgpm.part
    where parent_table = 'public.sb77'::regclass and child_name = :'sb_doomed'),
  1, 'the pgpm.part row stays, so the retirement is visibly wedged rather than quietly finished');

select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.sb77'::regclass and action = 'fail_retain_identity'),
  2, 'both refusals are logged: this is a standing wedge, not a one-off deferral');

-- status() must class it with the other things that stall retention (fail_retain_drop,
-- fail_retain_crossing, fail_retain_detach), not leave it invisible. Exactly 3, not ">= 1": this
-- per-file database has no pg_cron, so the original dispatch already logged one fail_retain_detach,
-- and a lower bound would be satisfied by that alone. 1 + the two refusals above.
select is(
  (select retain_drop_failures from pgpm.status() where parent = 'public.sb77'::regclass),
  3::bigint, 'status() counts both refusals alongside the dispatch failure as retention failures');

-- ============================ two in-flight markers must not wedge ============================
-- Reachable without any exotic failure: two concurrent retire() calls can both pass the in-flight check
-- before either marks, and an operator can call retire() by hand alongside the scheduled tick. The
-- obvious guard -- "yield to any other in-flight retirement" -- then deadlocks permanently, because each
-- sees the other and neither ever proceeds. Yielding only to a strictly OLDER one on a total order
-- always leaves exactly one able to move. Run last, so these markers cannot starve the sections above.
select child_name as a77 from pgpm.part
  where parent_table = 'public.rw77'::regclass and lo = '60000' \gset
select child_name as b77 from pgpm.part
  where parent_table = 'public.rw77'::regclass and lo = '70000' \gset

update pgpm.part set retiring_at = now() - interval '1 minute'
  where parent_table = 'public.rw77'::regclass and child_name = :'a77';
update pgpm.part set retiring_at = now()
  where parent_table = 'public.rw77'::regclass and child_name = :'b77';

select pgpm.retire('public.rw77', :'a77');
select pgpm.retire('public.rw77', :'b77');

select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.rw77'::regclass
    and action in ('retain_detach', 'fail_retain_detach') and lo = '60000'),
  1, 'the OLDER of two in-flight retirements still makes progress: the order always leaves a winner');

select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.rw77'::regclass
    and action in ('retain_detach', 'fail_retain_detach') and lo = '70000'),
  0, 'and the newer one yields silently rather than clobbering the standing job');

-- clean up: this file shares no database, but it does leave large fixtures behind
drop table if exists public.ref77, public.rw77, public.nf77,
  public.cxref77, public.cx77, public.nxref77, public.nx77, public.rp77,
  public.sbref77, public.sb77, public.sb77_kept cascade;
-- the #407 impostor detached itself out of public.sb77's tree, so the cascade above does not reach it
select format('drop table if exists public.%I cascade', :'sb_doomed') \gexec
drop schema if exists pgpm_test77 cascade;

select * from finish();
