-- pgpm.status() survives a managed table being dropped out from under it (issue #296).
--
-- THE BUG. `pgpm.config.parent_table` is a `regclass`, and nothing stops the relation behind it being
-- dropped: `DROP TABLE` on a managed parent leaves the config row pointing at an oid with no pg_class
-- entry. `regclass::text` then renders the bare oid, which `pgpm._frontier_native` interpolates straight
-- into a `FROM` clause:
--
--   ERROR:  syntax error at or near "17379"
--   LINE 1: select t.id::text from 17379 t order by t.id desc limit 1
--
-- Because `status()` loops every config row and raises out of the whole set-returning function, ONE
-- dropped table meant `status()` returned NOTHING AT ALL -- for every managed table, healthy ones
-- included. Dropping a managed table is off-contract, so the state is self-inflicted; what made it worth
-- fixing is that the DIAGNOSTIC is what broke. Maintenance kept running (its per-step handlers absorb the
-- error) and logged `skip_obtain` / `skip_write_block` / `skip_retain` every tick forever, each giving a
-- syntax error as the reason, while the one tool that would explain it returned zero rows.
--
-- Narrow but common trigger, measured: only `id`/`uuidv7` kinds reach the failing EXECUTE (`time` returns
-- `now()` before it), and only when `config.retain` is set (otherwise `_retain_boundary` short-circuits
-- first). The fixture below therefore uses `id` WITH retention, deliberately.
--
-- THE FIX, three parts, all asserted here: `_frontier_native` refuses legibly instead of letting Postgres
-- report a syntax error against an oid; `status()` reports such a row rather than dying on it, via a new
-- `parent_missing` column; and `pgpm.forget_missing()` is the escape hatch that clears the dead state.
-- forget_missing() takes NO argument on purpose -- it can only ever match config rows whose relation is
-- already gone, so by construction it cannot harm a live managed table.
--
-- NOTE: transmute is a committing procedure, so -- like every file in this suite -- this one runs
-- in its own database rather than begin/rollback.
create extension if not exists pgtap;

select plan(27);

-- ============================ fixture: one healthy, one dropped ============================
-- Asymmetric on purpose (2 in, 1 out): a compensating error that wiped both, or neither, cannot pass.
create table public.keep79 (id bigint generated by default as identity primary key, payload text);
insert into public.keep79 (payload) select 'x' from generate_series(1, 5000);
call pgpm.transmute('public.keep79', 'id', 1000, p_retain => 3000);

create table public.gone79 (id bigint generated by default as identity primary key, payload text);
insert into public.gone79 (payload) select 'x' from generate_series(1, 5000);
call pgpm.transmute('public.gone79', 'id', 1000, p_retain => 3000);

-- capture identities BEFORE the drop: afterwards the oid is the only handle left on the dead row
select ('public.gone79'::regclass)::oid as gone_oid \gset
select count(*)::int as keep_parts from pgpm.part
  where parent_table = 'public.keep79'::regclass \gset
-- and WHICH rows they are (#998): the healthy table's pgpm.part rows by name, oid and bounds, so that
-- forget_missing() is held to leaving each of them as it was, not merely as many of them.
create table pgpm_t79_keep_parts as
  select child_name, child_oid, lo, hi from pgpm.part where parent_table = 'public.keep79'::regclass;
select count(*)::int as gone_parts from pgpm.part
  where parent_table = 'public.gone79'::regclass \gset

drop table public.gone79 cascade;   -- no untransmute: exactly the off-contract move

-- LIVENESS WITNESSES. Every assertion below is satisfied by a run where the dangling row never existed,
-- so pin both the row and the two conditions that make it fatal.
select is(
  (select count(*)::int from pgpm.config where not exists
     (select 1 from pg_class c where c.oid = parent_table)),
  1, 'LIVENESS: exactly one config row is left pointing at a relation that is gone');

select is(
  (select control_kind || '/' || (retain is not null)::text from pgpm.config
    where parent_table::oid = :gone_oid),
  'id/true', 'LIVENESS: and it is the id-kind-with-retention combination that reaches the failure');

-- ============================ status() reports it instead of dying ============================
-- Stated as the contract rather than a literal count: this file runs against a database cloned from the
-- fixture template, so other managed tables are already present. "One row per config row" is also the
-- stronger claim -- the bug was status() returning ZERO rows for every table because of one bad one.
select is((select count(*)::int from pgpm.status()), (select count(*)::int from pgpm.config),
  'status() returns a row for EVERY managed table -- one dead parent no longer takes them all down');

select is(
  (select count(*)::int from pgpm.status() where parent = 'public.keep79'::regclass),
  1, 'the healthy table is reported, by name');

select is(
  (select count(*)::int from pgpm.status() where parent::oid = :gone_oid),
  1, 'and so is the dead one, by the oid that is all that remains of it');

select is(
  (select parent_missing from pgpm.status() where parent::oid = :gone_oid),
  true, 'parent_missing flags exactly which table is gone -- the most useful thing status() can say here');

select is(
  (select parent_missing from pgpm.status() where parent = 'public.keep79'::regclass),
  false, 'and is false for a table that is fine');

-- retain_backlog is the one field that needs the frontier, so it is the one field that cannot be answered.
select is(
  (select retain_backlog from pgpm.status() where parent::oid = :gone_oid),
  NULL, 'retain_backlog is null for a dead parent: the horizon cannot be computed without the relation');

select isnt(
  (select retain_backlog from pgpm.status() where parent = 'public.keep79'::regclass),
  NULL, 'but is still computed for the healthy one -- status() degrades per row, not wholesale');

-- ============================ and everything else fails LEGIBLY ============================
-- The point is not that these raise (they did before); it is that the message names the cause and the
-- remedy instead of blaming a syntax error on an integer.
select throws_like(
  format($$ select pgpm._frontier_native(%s::regclass) $$, :gone_oid),
  '%no longer exists%',
  '_frontier_native says the relation is gone, rather than emitting a syntax error against its oid');

select throws_like(
  format($$ select pgpm.obtain(%s::regclass) $$, :gone_oid),
  '%no longer exists%',
  'and every caller inherits that: obtain reports the real cause too');

select throws_like(
  format($$ select pgpm._frontier_native(%s::regclass) $$, :gone_oid),
  '%forget_missing%',
  'and the message names the escape hatch, so an operator is not left guessing');

-- ============================ forget_missing(): the escape hatch ============================
-- Captured once, because the call is destructive: a second call has nothing left to report.
create table pgpm_t79_report as select * from pgpm.forget_missing();

select is((select count(*)::int from pgpm_t79_report), 1,
  'forget_missing() acts on exactly the one dead parent');

select is((select parent_oid from pgpm_t79_report), :gone_oid::oid,
  'and identifies WHICH parent it forgot, by oid');

select is((select partitions_forgotten from pgpm_t79_report), :gone_parts,
  'reporting how many pgpm.part rows went with it');

select is((select coalesce(array_length(orphan_tables, 1), 0) from pgpm_t79_report), 0,
  'and no orphan tables, since DROP TABLE takes the attached partitions with the parent');

-- Identity, not cardinality: name what survived and what did not.
select is(
  (select count(*)::int from pgpm.config where parent_table = 'public.keep79'::regclass),
  1, 'the healthy table is still managed');

select is(
  (select count(*)::int from pgpm.config where parent_table::oid = :gone_oid),
  0, 'and the dead row is gone');

select is(
  (select count(*)::int from pgpm.part where parent_table = 'public.keep79'::regclass),
  :keep_parts, 'the healthy table keeps every one of its pgpm.part rows');

select bag_eq(
  $$ select child_name, child_oid, lo, hi from pgpm.part where parent_table = 'public.keep79'::regclass $$,
  'select child_name, child_oid, lo, hi from pgpm_t79_keep_parts',
  'and each of them as it was: the same (child_name, child_oid, lo, hi), none rewritten, none added');

select is(
  (select count(*)::int from pgpm.part where parent_table::oid = :gone_oid),
  0, 'and the dead parent keeps none');

select is((select count(*)::int from pgpm.forget_missing()), 0,
  'forget_missing() is a no-op the second time: nothing is missing now');

select lives_ok($$ select * from pgpm.status() $$,
  'and status() is healthy again');

-- ============================ the orphan case: report, never drop ============================
-- A DETACHED partition SURVIVES its parent's DROP, still holding its rows (measured on PG 17.10) -- and
-- "detached, not yet dropped" is exactly the state a #268 retirement sits in between the cron detach and
-- the completing drop. So forget_missing() must NAME such a table, never drop it: destroying data as a
-- side effect of a cleanup command is the worst possible reading of "forget".
create table public.orph79 (id bigint generated by default as identity primary key, payload text);
insert into public.orph79 (payload) select 'x' from generate_series(1, 5000);
call pgpm.transmute('public.orph79', 'id', 1000, p_retain => 3000);
select child_name as orph_child from pgpm.part
  where parent_table = 'public.orph79'::regclass order by lo::bigint limit 1 \gset

-- \gexec so the detach is not pinned to a literal name; the guard below keeps the later literal honest.
-- both sides cast: is() is polymorphic, so two bare literals resolve to `unknown` and it cannot pick a type
select is(:'orph_child'::text, 'orph79_p0000000000000000000_to_0000000000000006000'::text,
  'GUARD: the monolith child is named as this file assumes, so the literals below address it');
select format('alter table public.orph79 detach partition public.%I', :'orph_child') \gexec
drop table public.orph79 cascade;

create table pgpm_t79_orphan as select * from pgpm.forget_missing();

-- schema-qualified, because pgpm.part records no namespace and the dropped parent's oid can no longer
-- supply one: the operator has to be able to see which table the report means before acting on it.
select is((select orphan_tables from pgpm_t79_orphan), array['public.' || :'orph_child']::text[],
  'the surviving detached partition is REPORTED, schema-qualified');

select isnt((select to_regclass('public.' || :'orph_child')::text), NULL,
  'and it still EXISTS: forget_missing cleared pgpm state, it did not drop a table holding data');

select is((select count(*)::int from public.orph79_p0000000000000000000_to_0000000000000006000), 5000,
  'with every one of its rows intact');

drop table if exists public.keep79,
  public.orph79_p0000000000000000000_to_0000000000000006000 cascade;
drop table if exists pgpm_t79_report, pgpm_t79_orphan, pgpm_t79_keep_parts;

select * from finish();
