-- config.archive_batch caps how many DIFFERENT partitions one _archive_step call touches (issue
-- #351), the same shape as retain_batch (nullable int, null = unlimited, same "caps attempts, not
-- successes" semantics) but a different DEFAULT: retain_batch's own unlimited default is safe
-- because DROP TABLE is cheap and roughly constant-cost regardless of how many run per tick;
-- archiving is not (a real read, encode, and -- with a real S3 strategy and compression on --
-- CPU-bound work per partition), so fanning out over an entire backlog in one tick makes a single
-- maintain() call's duration scale with how large that backlog is, not just with
-- archive_byte_budget's own per-partition cost. archive_batch defaults to 1: strictly sequential,
-- one partition fully archived (and so retirable) before the next is even touched.
create extension if not exists pgtap;
select plan(8);

create table public.ab93 (id bigint generated by default as identity primary key, payload text);
insert into public.ab93 (payload) select 'x' from generate_series(1, 5000);   -- ids 1..5000
call pgpm.transmute('public.ab93', 'id', 1000, p_retain => 3000, p_paused => false);   -- monolith [0, 6000)
insert into public.ab93 (id, payload) select g, 'y' from generate_series(6001, 6005) g;   -- into [6000,7000)
insert into public.ab93 (id, payload) select g, 'z' from generate_series(7001, 7005) g;   -- into [7000,8000)
insert into public.ab93 (id, payload) values (11000, 'frontier');   -- advances the frontier to 11000

update pgpm.config set archive_fn = 'pgpm._archive_noop(regclass,name,text,text)'::regprocedure,
       retain_batch = 0,
       archive_byte_budget = 2000   -- small enough that the monolith needs several chunks, not one
 where parent_table = 'public.ab93'::regclass;

select is(
  (select archive_batch from pgpm.config where parent_table = 'public.ab93'::regclass),
  1, 'archive_batch defaults to 1 for a freshly-managed table');

-- boundary = grid_floor(11000 - 3000, 1000) = 8000: eligible = monolith [0,6000), [6000,7000),
-- [7000,8000) -- three simultaneously-eligible partitions, the same fixture shape
-- tests/archive/db/08 uses (there, archive_batch is explicitly set to null to preserve its own
-- "one tick, three ledger rows" assertion; here the point is the DEFAULT).
call pgpm.maintain('public.ab93');

select is(
  (select count(*)::int from pgpm.archive_ledger where parent_table = 'public.ab93'::regclass),
  1, 'with the default archive_batch (1), one maintain() tick archives exactly one of the three eligible partitions');

select is(
  (select child_name from pgpm.archive_ledger where parent_table = 'public.ab93'::regclass),
  (select child_name from pgpm.part where parent_table = 'public.ab93'::regclass and lo = '0'),
  'and it is the OLDEST eligible one, matching retain()''s own oldest-first convention');

-- a second tick continues the SAME partition (it is not yet fully covered), not a different one --
-- archive_batch bounds how many partitions get a turn, not how many chunks any one gets.
call pgpm.maintain('public.ab93');

-- Identity, not cardinality (#1170): the chunks themselves, by partition and range. A count of distinct
-- partitions in the ledger is also 1 after a second tick that archived nothing, so it could not see an
-- archive that stalls after its first chunk. At archive_byte_budget = 2000 a chunk of this table is 58 rows:
-- [0, 59) on the first tick, then [59, 117), resuming exactly where it ended.
select is(
  (select string_agg(format('%s [%s,%s)', child_name, lo, hi), ' ' order by lo::bigint)
     from pgpm.archive_ledger where parent_table = 'public.ab93'::regclass),
  (select format('%1$s [0,59) %1$s [59,117)', child_name) from pgpm.part
    where parent_table = 'public.ab93'::regclass and lo = '0'),
  'a second tick continues the same (oldest, not-yet-covered) partition where its first chunk ended, not a new one');

delete from pgpm.archive_ledger where parent_table = 'public.ab93'::regclass;

-- archive_batch = null: the old unlimited behavior is still available as an explicit opt-in.
update pgpm.config set archive_batch = null where parent_table = 'public.ab93'::regclass;
call pgpm.maintain('public.ab93');

select is(
  (select count(*)::int from pgpm.archive_ledger where parent_table = 'public.ab93'::regclass),
  3, 'archive_batch = null restores fan-out across every eligible partition in one tick');

delete from pgpm.archive_ledger where parent_table = 'public.ab93'::regclass;

-- an explicit numeric cap in between the two extremes.
update pgpm.config set archive_batch = 2 where parent_table = 'public.ab93'::regclass;
call pgpm.maintain('public.ab93');

-- Identity, not cardinality (#1170): which partitions, by name. Two ledger rows would also be two chunks of
-- the monolith, a cap spent on chunks rather than on DIFFERENT partitions. The two oldest each get one chunk:
-- the monolith's first, [0, 59), and all of [6000, 7000), whose five rows fit the budget.
select is(
  (select string_agg(format('%s [%s,%s)', child_name, lo, hi), ' ' order by lo::bigint)
     from pgpm.archive_ledger where parent_table = 'public.ab93'::regclass),
  (select format('%s [0,59) %s [6000,7000)',
                 (select child_name from pgpm.part where parent_table = 'public.ab93'::regclass and lo = '0'),
                 (select child_name from pgpm.part where parent_table = 'public.ab93'::regclass and lo = '6000'))),
  'archive_batch = 2 archives exactly two of the three eligible partitions in one tick, the two oldest');

-- retain_batch is untouched by any of this (issue #351 only adds the archiving-side knob).
select is(
  (select retain_batch from pgpm.config where parent_table = 'public.ab93'::regclass),
  0, 'retain_batch keeps its own value, independent of archive_batch');

select is(
  (select count(*)::int from pgpm.part
    where parent_table = 'public.ab93'::regclass and attached and lo::numeric in (0, 6000, 7000)),
  3, 'all three originally-eligible partitions are still attached -- archive_batch paces archiving, not retention (retain_batch = 0 keeps drops separate)');

select * from finish();
