-- from_hypertable_cutover carries each identity column's KIND and its sequence's OPTIONS (issue #640).
--
-- THE BUG. CREATE TABLE ... LIKE does not carry identity, so the swap re-adds it on the copy. It re-added
-- every identity column as GENERATED BY DEFAULT with the default sequence options, and seeded it at
-- last_value + 1. A GENERATED ALWAYS column came out BY DEFAULT (an insert supplying the id was accepted, a
-- constraint the operator declared revoked without a word), an INCREMENT BY 2 sequence came out stepping by
-- 1, and the seed was off the lattice: after 1, 3, 5 the next id was 6. transmute and untransmute carry
-- both since #308 and #670 (_identity_options, _seq_next, _identity_reseed); the cutover now uses them too.
--
-- THE FIXTURE is asymmetric on every axis the old code could get right by accident: two identity columns
-- of opposite kind and opposite direction (ALWAYS ascending by 2, BY DEFAULT descending by 3), each
-- sequence burned AHEAD of its extreme id, so "max + 1", "last_value + 1", "max + increment" and the
-- source's own next value are four different numbers for each.
--
-- Autocommit, disposable-db. from_hypertable is called as a bare statement.
select plan(13);

create table public.hid27 (
  id   bigint generated always as identity (increment by 2 start with 1 maxvalue 999999),
  down int    generated by default as identity (increment by -3 start with -1 minvalue -9000 maxvalue -1),
  ts   timestamptz not null,
  v    text,
  primary key (id, ts));
select ok(create_hypertable('public.hid27', 'ts', chunk_time_interval => interval '1 day') is not null,
  'fixture: hid27 is a hypertable');
insert into public.hid27 (ts, v) values (now() - interval '3 days', 'a'), (now() - interval '2 days', 'b'),
                                        (now() - interval '1 day', 'c');
-- Burn each sequence two steps past its extreme id: id's next is 11 (max 5), down's is -16 (min -7).
do $$ begin
  perform nextval(pg_get_serial_sequence('public.hid27', 'id')) from generate_series(1, 2);
  perform nextval(pg_get_serial_sequence('public.hid27', 'down')) from generate_series(1, 2);
end $$;

-- The source's options, as the clause ADD GENERATED takes them, kept for the comparison after the swap.
create temp table hid27_opts as
  select a.attname::text as col, pgpm._identity_options(pg_get_serial_sequence('public.hid27', a.attname)::regclass) as opts
    from pg_attribute a where a.attrelid = 'public.hid27'::regclass and a.attidentity <> '';

select is((select string_agg(attname || ':' || attidentity::text, ',' order by attnum) from pg_attribute
            where attrelid = 'public.hid27'::regclass and attidentity <> ''),
  'id:a,down:d', 'LIVENESS: the source has an ALWAYS and a BY DEFAULT identity');
select is((select string_agg(col || '=' || opts, ' ' order by col) from hid27_opts),
  'down=(increment by -3 minvalue -9000 maxvalue -1 start with -1 cache 1 no cycle) '
  || 'id=(increment by 2 minvalue 1 maxvalue 999999 start with 1 cache 1 no cycle)',
  'LIVENESS: the source sequences step by 2 and by -3, with non-default bounds');
select is((select string_agg(id || '/' || down, ',' order by id) from public.hid27), '1/-1,3/-4,5/-7',
  'LIVENESS: the source handed out 1, 3, 5 and -1, -4, -7');

call pgpm.from_hypertable('public.hid27', 'ts', interval '1 day', p_paused => false);

select is((select relkind::text from pg_class where oid = 'public.hid27'::regclass), 'p',
  'LIVENESS: hid27 is now the partitioned parent');
select is((select string_agg(id || '/' || down, ',' order by id) from public.hid27), '1/-1,3/-4,5/-7',
  'LIVENESS: every source row is there, by identity');

-- ============================ the kind ============================
select is((select string_agg(attname || ':' || attidentity::text, ',' order by attnum) from pg_attribute
            where attrelid = 'public.hid27'::regclass and attidentity <> ''),
  'id:a,down:d', 'each identity keeps its kind: id still ALWAYS, down still BY DEFAULT');

-- ============================ the options ============================
select is(
  (select string_agg(o.col || '=' || coalesce(pgpm._identity_options(pg_get_serial_sequence('public.hid27', o.col)::regclass), 'none'),
                     ' ' order by o.col) from hid27_opts o),
  (select string_agg(col || '=' || opts, ' ' order by col) from hid27_opts),
  'each migrated sequence has the source''s options (increment, bounds, start, cache, cycle)');

-- ============================ the position, on the lattice ============================
insert into public.hid27 (ts, v) values (now() - interval '1 hour', 'd');
select is((select id from public.hid27 where v = 'd'), 11::bigint,
  'the next id is 11: the source''s own next value, on its odd lattice (not 6, 7 or 10)');
select is((select down from public.hid27 where v = 'd'), -16,
  'the next down is -16: the source''s own next value, counting down by 3 (not -8, -10 or -12)');
insert into public.hid27 (ts, v) values (now() - interval '30 minutes', 'e');
select is((select id || '/' || down from public.hid27 where v = 'e'), '13/-19',
  'and the one after steps by 2 and by -3 again');

-- ============================ the kind, by behaviour ============================
-- (after the position checks: the insert that supplies down still takes the next id)
select throws_ok(
  $$ insert into public.hid27 (id, ts, v) values (101, now() - interval '1 hour', 'x') $$,
  '428C9', NULL, 'an insert that supplies id is still refused');
insert into public.hid27 (down, ts, v) values (-5000, now() - interval '2 hours', 'w');
select is((select down from public.hid27 where v = 'w'), -5000,
  'one that supplies down is still accepted (BY DEFAULT stays BY DEFAULT)');

select * from finish();
-- no teardown: the harness runs each db/ test in a throwaway database (disposable-db).
