-- Fixtures for the `archive` test track (pgpm_archive against MinIO). Loaded BEFORE
-- pgpm_core/pgpm_archive are installed (test.sh's run_archive), so this file only
-- DEFINES functions and the vault stub -- any body referencing pgpm.*/archive.* is
-- plpgsql, not validated until called, and by the time a test file calls one of these
-- helpers both modules are already installed.

-- pgpm_archive's S3 hooks read credentials via `vault.decrypted_secrets` (Supabase
-- Vault's public read view). The test image is plain Postgres with no pgsodium/Vault
-- available, so stub just the one shape the module actually queries (name,
-- decrypted_secret), seeded with the MinIO root credentials test.sh's harness runs.
create schema if not exists vault;
create table if not exists vault.decrypted_secrets (
  name             text primary key,
  decrypted_secret text not null
);
insert into vault.decrypted_secrets (name, decrypted_secret) values
  ('s3_archive_access_key_id',     'minioadmin'),
  ('s3_archive_secret_access_key', 'minioadmin')
on conflict (name) do update set decrypted_secret = excluded.decrypted_secret;

-- a small bigint-id managed table: build, seed ids 1..p_rows, transmute + obtain. p_paused is
-- forwarded to transmute() (default true, matching transmute's own default) -- callers driving
-- pgpm.maintain() need p_paused => false, since maintain() no-ops entirely on a paused table.
-- A PROCEDURE, not a function: it calls pgpm.transmute, which COMMITs (#275), and a FUNCTION cannot
-- call a committing procedure at all -- not even outside an explicit transaction block.
drop function if exists mk_archive_table(text, int, bigint, bigint, boolean);
create or replace procedure mk_archive_table(p_name text, p_rows int default 50000, p_step bigint default 10000, p_retain bigint default null, p_paused boolean default true)
language plpgsql as $$
-- v_made/v_deferred exist only to receive obtain's INOUTs: PL/pgSQL requires a WRITABLE argument for an
-- output parameter, so the parameter defaults cannot be relied on from inside a function or procedure
-- the way they can from a top-level CALL.
declare v_made int; v_deferred boolean;
begin
  execute format('drop table if exists public.%I cascade', p_name);
  execute format('create table public.%I (id bigint generated by default as identity primary key, payload text)', p_name);
  execute format('insert into public.%I (payload) select %L from generate_series(1, %s)', p_name, 'x', p_rows);
  call pgpm.transmute('public.' || p_name, 'id', p_step, p_retain => p_retain, p_paused => p_paused);
  perform pgpm.obtain('public.' || p_name);
end;
$$;

-- an archive.config row wired to the test MinIO bucket/endpoint (test.sh creates
-- archive-test-bucket via `mc mb` before any test file runs), via the archive.configure()
-- operator interface (reintroduced, narrower than the paced-worker-era one issue #240 deleted:
-- connection settings only, no scheduling knob).
create or replace function mk_archive_config(p_name text, p_compress boolean default false)
returns void language plpgsql as $$
begin
  perform archive.configure(('public.' || p_name)::regclass, 'archive-test-bucket',
    p_endpoint => 'http://minio:9000', p_prefix => p_name || '/', p_compress => p_compress);
end;
$$;

-- Puts <p_schema>.http(http_request), a test's stand-in for the store, in the place of pgpm_archive's
-- transport (#984). The module reaches the http extension only through archive._s3_send, in the extension's
-- own schema and never through search_path, so a stand-in can no longer be slipped ahead of it on the path.
-- Instead the real transport is renamed aside to archive._s3_send_real, and a replacement routes each
-- request to the stand-in while the setting <p_schema>.standin is 'on', and to the real transport
-- otherwise. The replacement keeps the search_path it is created under (FROM CURRENT, the test's own), so
-- the http types it and the stand-in name resolve there: the signers that call it run under pg_catalog
-- alone. For a test's own database only; returns nothing.
create or replace function mk_transport_standin(p_schema name) returns void language plpgsql as $fn$
begin
  alter function archive._s3_send(text, text, text, text, text, text, bytea) rename to _s3_send_real;
  execute format($f$
    create function archive._s3_send(p_method text, p_url text, p_amz_date text, p_payload_hash text, p_auth text,
                                     p_ctype text, p_body bytea)
    returns http_response language plpgsql set search_path from current as $b$
    begin
      if current_setting(%L, true) = 'on' then
        perform http_set_curlopt('CURLOPT_TIMEOUT_MS', '300000');   -- as the real transport does, for a forwarding stand-in
        return %I.http((p_method::http_method, p_url,
                        array[http_header('x-amz-date', p_amz_date), http_header('x-amz-content-sha256', p_payload_hash),
                              http_header('authorization', p_auth)],
                        p_ctype, bytea_to_text(p_body))::http_request);
      end if;
      return archive._s3_send_real(p_method, p_url, p_amz_date, p_payload_hash, p_auth, p_ctype, p_body);
    end $b$ $f$, p_schema || '.standin', p_schema);
end;
$fn$;
