-- =============================================================================
-- Test/demo fixtures for pg_partition_magician.
--
-- Builds three unpartitioned tables and transmutes one of each kind, so the pgTAP
-- suite has realistic data to exercise. Load it AFTER the module is installed:
--
--   psql -f pgpm_core/install.sql        # (or any install channel)
--   psql -f fixtures/demo.sql
--   pg_prove tests/*.sql
--
-- Row counts are tunable without editing this file:
--   ALTER DATABASE postgres SET poc.seed_count   = 50000;   -- messages
--   ALTER DATABASE postgres SET poc.events_count = 45000;   -- events_id / events_uuid
-- =============================================================================

-- ---- time dimension: messages ----------------------------------------------
create table public.messages (
  id          bigint      generated by default as identity,
  tenant_id   uuid        not null,
  created_at  timestamptz not null default now(),
  body        text        not null,
  -- the partition key (created_at) is part of the PK, so transmute reuses it in place (no rewrite)
  constraint messages_pkey primary key (created_at, id)
);
create index messages_tenant_created_idx on public.messages (tenant_id, created_at desc);

-- Deterministic generator: spreads p_count rows across the last p_months months
-- for a fixed set of synthetic tenants (a hash, not random(), so reseeds match).
create or replace function public.generate_messages(p_count int default 50000, p_months int default 6)
returns bigint language plpgsql as $$
declare
  v_tenants uuid[] := array[
    '00000000-0000-0000-0000-0000000000a1','00000000-0000-0000-0000-0000000000a2',
    '00000000-0000-0000-0000-0000000000a3','00000000-0000-0000-0000-0000000000a4',
    '00000000-0000-0000-0000-0000000000a5']::uuid[];
  v_start timestamptz := date_trunc('month', now()) - make_interval(months => p_months - 1);
  v_span  interval    := now() - v_start;
begin
  insert into public.messages (tenant_id, created_at, body)
  select v_tenants[1 + (g % array_length(v_tenants, 1))],
         v_start + v_span * (((g::bigint * 2654435761) % 1000000)::double precision / 1000000.0),
         'message body #' || g
  from generate_series(1, p_count) as g;
  return p_count;
end;
$$;

select public.generate_messages(coalesce(current_setting('poc.seed_count', true)::int, 50000), 6);
analyze public.messages;

call pgpm.transmute('public.messages', 'created_at', interval '1 month',
                  p_obtain => 4, p_retain => null, p_regrain_batch => 5000, p_paused => true);
-- transmute() does the cutover only; obtain the future partitions separately (online)
select pgpm.obtain('public.messages');

-- ---- integer/id dimension: events_id ---------------------------------------
create table public.events_id (
  id      bigint generated by default as identity primary key,
  payload text not null
);
insert into public.events_id (payload)
  select 'evt ' || g from generate_series(1, coalesce(current_setting('poc.events_count', true)::int, 45000)) g;
analyze public.events_id;
-- The seeded rows, captured BEFORE the migration, so tests/11 can hold the converted table to them by
-- identity. A snapshot taken after this file runs is a snapshot of the migration's output, and comparing
-- the table to that compares it to itself. Dropped first because test.sh's reset_demo and the review
-- harness drop only the three demo tables between loads.
drop table if exists public.events_id_seeded;
create table public.events_id_seeded as select id, payload from public.events_id;
call pgpm.transmute('public.events_id', 'id', 10000, p_obtain => 2, p_regrain_batch => 5000);
select pgpm.obtain('public.events_id');

-- ---- uuidv7 dimension: events_uuid -----------------------------------------
create table public.events_uuid (
  id      uuid primary key,
  payload text not null
);
-- uuidv7-shaped ids: 48-bit ms prefix (spread over the last 6 months) + random
-- low bits for uniqueness (no native uuidv7() needed on PG 15).
insert into public.events_uuid (id, payload)
select (substr(h,1,8)||'-'||substr(h,9,4)||'-'||substr(h,13,4)||'-'||substr(h,17,4)||'-'||substr(h,21,12))::uuid,
       'evt ' || g
from (
  select g,
    lpad(to_hex(floor(extract(epoch from (
        (date_trunc('month', now()) - make_interval(months => 5))
        + (now() - (date_trunc('month', now()) - make_interval(months => 5)))
          * (((g::bigint * 2654435761) % 1000000)::double precision / 1000000.0)
    )) * 1000)::bigint), 12, '0')
    || substr(replace(gen_random_uuid()::text, '-', ''), 13) as h
  from generate_series(1, coalesce(current_setting('poc.events_count', true)::int, 45000)) g
) s;
analyze public.events_uuid;
-- The seeded rows, captured before the migration, for tests/12 (see events_id_seeded above).
drop table if exists public.events_uuid_seeded;
create table public.events_uuid_seeded as select id, payload from public.events_uuid;
call pgpm.transmute('public.events_uuid', 'id', interval '1 month', p_obtain => 2, p_regrain_batch => 5000);
select pgpm.obtain('public.events_uuid');
